// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hermes_jwt_keys.sql

package hermes

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveJWTKeys = `-- name: GetActiveJWTKeys :many
SELECT kid, alg, public_key_pem, valid_from, valid_until, revoked_at, created_at
FROM hermes_jwt_keys
WHERE valid_from <= NOW()
  AND (valid_until IS NULL OR valid_until > NOW())
  AND revoked_at IS NULL
ORDER BY valid_from DESC, kid ASC
`

func (q *Queries) GetActiveJWTKeys(ctx context.Context) ([]HermesJwtKey, error) {
	rows, err := q.db.Query(ctx, getActiveJWTKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HermesJwtKey
	for rows.Next() {
		var i HermesJwtKey
		if err := rows.Scan(
			&i.Kid,
			&i.Alg,
			&i.PublicKeyPem,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJWTKeyByKid = `-- name: GetJWTKeyByKid :one
SELECT kid, alg, public_key_pem, valid_from, valid_until, revoked_at, created_at
FROM hermes_jwt_keys
WHERE kid = $1::text
`

func (q *Queries) GetJWTKeyByKid(ctx context.Context, kid string) (HermesJwtKey, error) {
	row := q.db.QueryRow(ctx, getJWTKeyByKid, kid)
	var i HermesJwtKey
	err := row.Scan(
		&i.Kid,
		&i.Alg,
		&i.PublicKeyPem,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertJWTKey = `-- name: InsertJWTKey :one

INSERT INTO hermes_jwt_keys (kid, alg, public_key_pem, valid_until)
VALUES (
    $1::text,
    $2::text,
    $3::text,
    $4::timestamptz
)
RETURNING kid, alg, public_key_pem, valid_from, valid_until, revoked_at, created_at
`

type InsertJWTKeyParams struct {
	Kid          string             `db:"kid" json:"kid"`
	Alg          string             `db:"alg" json:"alg"`
	PublicKeyPem string             `db:"public_key_pem" json:"public_key_pem"`
	ValidUntil   pgtype.Timestamptz `db:"valid_until" json:"valid_until"`
}

// Hermes Runner JWT 公钥查询。
func (q *Queries) InsertJWTKey(ctx context.Context, arg InsertJWTKeyParams) (HermesJwtKey, error) {
	row := q.db.QueryRow(ctx, insertJWTKey,
		arg.Kid,
		arg.Alg,
		arg.PublicKeyPem,
		arg.ValidUntil,
	)
	var i HermesJwtKey
	err := row.Scan(
		&i.Kid,
		&i.Alg,
		&i.PublicKeyPem,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeJWTKey = `-- name: RevokeJWTKey :execrows
UPDATE hermes_jwt_keys
SET revoked_at = NOW()
WHERE kid = $1::text
  AND revoked_at IS NULL
RETURNING kid
`

func (q *Queries) RevokeJWTKey(ctx context.Context, kid string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeJWTKey, kid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
