// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hermes.sql

package hermes

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO hermes_api_profiles (
    tenant_id, owner_user_id, name, profile_kind, base_url,
    encrypted_api_key, encryption_scheme, key_id, nonce, aad_hash,
    api_key_fingerprint, api_key_hint, credential_version, secret_binding_id
)
VALUES (
    $1::bigint,
    $2::bigint,
    $3::text,
    $4::text,
    $5::text,
    $6::bytea,
    $7::text,
    $8::text,
    $9::bytea,
    $10::text,
    $11::text,
    $12::text,
    $13::integer,
    $14::bigint
)
RETURNING id, tenant_id, owner_user_id, name, profile_kind, created_at, updated_at, base_url, encrypted_api_key, encryption_scheme, key_id, nonce, aad_hash, api_key_fingerprint, api_key_hint, credential_version, secret_binding_id
`

type CreateProfileParams struct {
	TenantID          int64  `db:"tenant_id" json:"tenant_id"`
	OwnerUserID       int64  `db:"owner_user_id" json:"owner_user_id"`
	Name              string `db:"name" json:"name"`
	ProfileKind       string `db:"profile_kind" json:"profile_kind"`
	BaseUrl           string `db:"base_url" json:"base_url"`
	EncryptedApiKey   []byte `db:"encrypted_api_key" json:"encrypted_api_key"`
	EncryptionScheme  string `db:"encryption_scheme" json:"encryption_scheme"`
	KeyID             string `db:"key_id" json:"key_id"`
	Nonce             []byte `db:"nonce" json:"nonce"`
	AadHash           string `db:"aad_hash" json:"aad_hash"`
	ApiKeyFingerprint string `db:"api_key_fingerprint" json:"api_key_fingerprint"`
	ApiKeyHint        string `db:"api_key_hint" json:"api_key_hint"`
	CredentialVersion int32  `db:"credential_version" json:"credential_version"`
	SecretBindingID   int64  `db:"secret_binding_id" json:"secret_binding_id"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (HermesApiProfile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.TenantID,
		arg.OwnerUserID,
		arg.Name,
		arg.ProfileKind,
		arg.BaseUrl,
		arg.EncryptedApiKey,
		arg.EncryptionScheme,
		arg.KeyID,
		arg.Nonce,
		arg.AadHash,
		arg.ApiKeyFingerprint,
		arg.ApiKeyHint,
		arg.CredentialVersion,
		arg.SecretBindingID,
	)
	var i HermesApiProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerUserID,
		&i.Name,
		&i.ProfileKind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.EncryptionScheme,
		&i.KeyID,
		&i.Nonce,
		&i.AadHash,
		&i.ApiKeyFingerprint,
		&i.ApiKeyHint,
		&i.CredentialVersion,
		&i.SecretBindingID,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :execrows
DELETE FROM hermes_api_profiles
WHERE id = $1::bigint
  AND tenant_id = $2::bigint
`

type DeleteProfileParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteProfile(ctx context.Context, arg DeleteProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProfile, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableHermes = `-- name: DisableHermes :one
UPDATE hermes_settings
SET enabled = FALSE,
    updated_at = NOW()
WHERE tenant_id = $1::bigint
  AND user_id = $2::bigint
RETURNING tenant_id, user_id, enabled, api_source, profile_id, created_at, updated_at, model_key
`

type DisableHermesParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DisableHermes(ctx context.Context, arg DisableHermesParams) (HermesSetting, error) {
	row := q.db.QueryRow(ctx, disableHermes, arg.TenantID, arg.UserID)
	var i HermesSetting
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Enabled,
		&i.APISource,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelKey,
	)
	return i, err
}

const enableHermes = `-- name: EnableHermes :one
UPDATE hermes_settings
SET enabled = TRUE,
    updated_at = NOW()
WHERE tenant_id = $1::bigint
  AND user_id = $2::bigint
RETURNING tenant_id, user_id, enabled, api_source, profile_id, created_at, updated_at, model_key
`

type EnableHermesParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) EnableHermes(ctx context.Context, arg EnableHermesParams) (HermesSetting, error) {
	row := q.db.QueryRow(ctx, enableHermes, arg.TenantID, arg.UserID)
	var i HermesSetting
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Enabled,
		&i.APISource,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelKey,
	)
	return i, err
}

const getAuditEventByCorrelation = `-- name: GetAuditEventByCorrelation :many
SELECT id, ts, tenant_id, actor_source, actor_id, actor_role, action,
       sanitized_args, result, correlation_id, request_id, log_category
FROM hermes_audit_events
WHERE tenant_id = $1::bigint
  AND correlation_id = $2::text
ORDER BY ts DESC, id DESC
`

type GetAuditEventByCorrelationParams struct {
	TenantID      int64  `db:"tenant_id" json:"tenant_id"`
	CorrelationID string `db:"correlation_id" json:"correlation_id"`
}

type GetAuditEventByCorrelationRow struct {
	ID            int64              `db:"id" json:"id"`
	Ts            pgtype.Timestamptz `db:"ts" json:"ts"`
	TenantID      int64              `db:"tenant_id" json:"tenant_id"`
	ActorSource   string             `db:"actor_source" json:"actor_source"`
	ActorID       int64              `db:"actor_id" json:"actor_id"`
	ActorRole     *string            `db:"actor_role" json:"actor_role"`
	Action        string             `db:"action" json:"action"`
	SanitizedArgs []byte             `db:"sanitized_args" json:"sanitized_args"`
	Result        string             `db:"result" json:"result"`
	CorrelationID *string            `db:"correlation_id" json:"correlation_id"`
	RequestID     *string            `db:"request_id" json:"request_id"`
	LogCategory   string             `db:"log_category" json:"log_category"`
}

func (q *Queries) GetAuditEventByCorrelation(ctx context.Context, arg GetAuditEventByCorrelationParams) ([]GetAuditEventByCorrelationRow, error) {
	rows, err := q.db.Query(ctx, getAuditEventByCorrelation, arg.TenantID, arg.CorrelationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditEventByCorrelationRow
	for rows.Next() {
		var i GetAuditEventByCorrelationRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.TenantID,
			&i.ActorSource,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.SanitizedArgs,
			&i.Result,
			&i.CorrelationID,
			&i.RequestID,
			&i.LogCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfile = `-- name: GetProfile :one
SELECT id, tenant_id, owner_user_id, name, profile_kind, created_at, updated_at, base_url, encrypted_api_key, encryption_scheme, key_id, nonce, aad_hash, api_key_fingerprint, api_key_hint, credential_version, secret_binding_id
FROM hermes_api_profiles
WHERE id = $1::bigint
  AND tenant_id = $2::bigint
`

type GetProfileParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetProfile(ctx context.Context, arg GetProfileParams) (HermesApiProfile, error) {
	row := q.db.QueryRow(ctx, getProfile, arg.ID, arg.TenantID)
	var i HermesApiProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerUserID,
		&i.Name,
		&i.ProfileKind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.EncryptionScheme,
		&i.KeyID,
		&i.Nonce,
		&i.AadHash,
		&i.ApiKeyFingerprint,
		&i.ApiKeyHint,
		&i.CredentialVersion,
		&i.SecretBindingID,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one

SELECT tenant_id, user_id, enabled, api_source, profile_id, created_at, updated_at, model_key
FROM hermes_settings
WHERE tenant_id = $1::bigint
  AND user_id = $2::bigint
`

type GetSettingsParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

// Hermes 设置、模型档案与日志查询。
func (q *Queries) GetSettings(ctx context.Context, arg GetSettingsParams) (HermesSetting, error) {
	row := q.db.QueryRow(ctx, getSettings, arg.TenantID, arg.UserID)
	var i HermesSetting
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Enabled,
		&i.APISource,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelKey,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO hermes_audit_events (
    ts, tenant_id, actor_source, actor_id, actor_role, action,
    sanitized_args, result, correlation_id, request_id, log_category
) VALUES (
    $1::timestamptz,
    $2::bigint,
    $3::text,
    $4::bigint,
    $5::text,
    $6::text,
    $7::jsonb,
    $8::text,
    $9::text,
    $10::text,
    $11::text
)
RETURNING id, ts, tenant_id, action, sanitized_args, result, correlation_id, request_id, ingested_at, log_category, actor_source, actor_id, actor_role
`

type InsertAuditEventParams struct {
	Ts            pgtype.Timestamptz `db:"ts" json:"ts"`
	TenantID      int64              `db:"tenant_id" json:"tenant_id"`
	ActorSource   string             `db:"actor_source" json:"actor_source"`
	ActorID       int64              `db:"actor_id" json:"actor_id"`
	ActorRole     string             `db:"actor_role" json:"actor_role"`
	Action        string             `db:"action" json:"action"`
	SanitizedArgs []byte             `db:"sanitized_args" json:"sanitized_args"`
	Result        string             `db:"result" json:"result"`
	CorrelationID *string            `db:"correlation_id" json:"correlation_id"`
	RequestID     *string            `db:"request_id" json:"request_id"`
	LogCategory   string             `db:"log_category" json:"log_category"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (HermesAuditEvent, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.Ts,
		arg.TenantID,
		arg.ActorSource,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.SanitizedArgs,
		arg.Result,
		arg.CorrelationID,
		arg.RequestID,
		arg.LogCategory,
	)
	var i HermesAuditEvent
	err := row.Scan(
		&i.ID,
		&i.Ts,
		&i.TenantID,
		&i.Action,
		&i.SanitizedArgs,
		&i.Result,
		&i.CorrelationID,
		&i.RequestID,
		&i.IngestedAt,
		&i.LogCategory,
		&i.ActorSource,
		&i.ActorID,
		&i.ActorRole,
	)
	return i, err
}

const listAuditEventsByTenant = `-- name: ListAuditEventsByTenant :many
SELECT id, ts, tenant_id, actor_source, actor_id, actor_role, action,
       sanitized_args, result, correlation_id, request_id, log_category
FROM hermes_audit_events
WHERE tenant_id = $1::bigint
ORDER BY ts DESC, id DESC
LIMIT $3::integer
OFFSET $2::integer
`

type ListAuditEventsByTenantParams struct {
	TenantID   int64 `db:"tenant_id" json:"tenant_id"`
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

type ListAuditEventsByTenantRow struct {
	ID            int64              `db:"id" json:"id"`
	Ts            pgtype.Timestamptz `db:"ts" json:"ts"`
	TenantID      int64              `db:"tenant_id" json:"tenant_id"`
	ActorSource   string             `db:"actor_source" json:"actor_source"`
	ActorID       int64              `db:"actor_id" json:"actor_id"`
	ActorRole     *string            `db:"actor_role" json:"actor_role"`
	Action        string             `db:"action" json:"action"`
	SanitizedArgs []byte             `db:"sanitized_args" json:"sanitized_args"`
	Result        string             `db:"result" json:"result"`
	CorrelationID *string            `db:"correlation_id" json:"correlation_id"`
	RequestID     *string            `db:"request_id" json:"request_id"`
	LogCategory   string             `db:"log_category" json:"log_category"`
}

func (q *Queries) ListAuditEventsByTenant(ctx context.Context, arg ListAuditEventsByTenantParams) ([]ListAuditEventsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByTenant, arg.TenantID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditEventsByTenantRow
	for rows.Next() {
		var i ListAuditEventsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.TenantID,
			&i.ActorSource,
			&i.ActorID,
			&i.ActorRole,
			&i.Action,
			&i.SanitizedArgs,
			&i.Result,
			&i.CorrelationID,
			&i.RequestID,
			&i.LogCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByOwner = `-- name: ListProfilesByOwner :many
SELECT id, tenant_id, owner_user_id, name, profile_kind, created_at, updated_at, base_url, encrypted_api_key, encryption_scheme, key_id, nonce, aad_hash, api_key_fingerprint, api_key_hint, credential_version, secret_binding_id
FROM hermes_api_profiles
WHERE tenant_id = $1::bigint
  AND owner_user_id = $2::bigint
ORDER BY created_at DESC, id DESC
`

type ListProfilesByOwnerParams struct {
	TenantID    int64 `db:"tenant_id" json:"tenant_id"`
	OwnerUserID int64 `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) ListProfilesByOwner(ctx context.Context, arg ListProfilesByOwnerParams) ([]HermesApiProfile, error) {
	rows, err := q.db.Query(ctx, listProfilesByOwner, arg.TenantID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HermesApiProfile
	for rows.Next() {
		var i HermesApiProfile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OwnerUserID,
			&i.Name,
			&i.ProfileKind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseUrl,
			&i.EncryptedApiKey,
			&i.EncryptionScheme,
			&i.KeyID,
			&i.Nonce,
			&i.AadHash,
			&i.ApiKeyFingerprint,
			&i.ApiKeyHint,
			&i.CredentialVersion,
			&i.SecretBindingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByTenant = `-- name: ListProfilesByTenant :many
SELECT id, tenant_id, owner_user_id, name, profile_kind, created_at, updated_at, base_url, encrypted_api_key, encryption_scheme, key_id, nonce, aad_hash, api_key_fingerprint, api_key_hint, credential_version, secret_binding_id
FROM hermes_api_profiles
WHERE tenant_id = $1::bigint
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListProfilesByTenant(ctx context.Context, tenantID int64) ([]HermesApiProfile, error) {
	rows, err := q.db.Query(ctx, listProfilesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HermesApiProfile
	for rows.Next() {
		var i HermesApiProfile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OwnerUserID,
			&i.Name,
			&i.ProfileKind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaseUrl,
			&i.EncryptedApiKey,
			&i.EncryptionScheme,
			&i.KeyID,
			&i.Nonce,
			&i.AadHash,
			&i.ApiKeyFingerprint,
			&i.ApiKeyHint,
			&i.CredentialVersion,
			&i.SecretBindingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const profileInUse = `-- name: ProfileInUse :one
SELECT EXISTS (
    SELECT 1
    FROM hermes_settings
    WHERE tenant_id = $1::bigint
      AND profile_id = $2::bigint
    LIMIT 1
)::boolean
`

type ProfileInUseParams struct {
	TenantID  int64 `db:"tenant_id" json:"tenant_id"`
	ProfileID int64 `db:"profile_id" json:"profile_id"`
}

func (q *Queries) ProfileInUse(ctx context.Context, arg ProfileInUseParams) (bool, error) {
	row := q.db.QueryRow(ctx, profileInUse, arg.TenantID, arg.ProfileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const rotateProfileCredential = `-- name: RotateProfileCredential :one
UPDATE hermes_api_profiles
SET name = $1::text,
    base_url = $2::text,
    encrypted_api_key = $3::bytea,
    encryption_scheme = $4::text,
    key_id = $5::text,
    nonce = $6::bytea,
    aad_hash = $7::text,
    api_key_fingerprint = $8::text,
    api_key_hint = $9::text,
    credential_version = $10::integer,
    updated_at = NOW()
WHERE id = $11::bigint
  AND tenant_id = $12::bigint
  AND credential_version = $13::integer
RETURNING id, tenant_id, owner_user_id, name, profile_kind, created_at, updated_at, base_url, encrypted_api_key, encryption_scheme, key_id, nonce, aad_hash, api_key_fingerprint, api_key_hint, credential_version, secret_binding_id
`

type RotateProfileCredentialParams struct {
	Name                      string `db:"name" json:"name"`
	BaseUrl                   string `db:"base_url" json:"base_url"`
	EncryptedApiKey           []byte `db:"encrypted_api_key" json:"encrypted_api_key"`
	EncryptionScheme          string `db:"encryption_scheme" json:"encryption_scheme"`
	KeyID                     string `db:"key_id" json:"key_id"`
	Nonce                     []byte `db:"nonce" json:"nonce"`
	AadHash                   string `db:"aad_hash" json:"aad_hash"`
	ApiKeyFingerprint         string `db:"api_key_fingerprint" json:"api_key_fingerprint"`
	ApiKeyHint                string `db:"api_key_hint" json:"api_key_hint"`
	NewCredentialVersion      int32  `db:"new_credential_version" json:"new_credential_version"`
	ID                        int64  `db:"id" json:"id"`
	TenantID                  int64  `db:"tenant_id" json:"tenant_id"`
	ExpectedCredentialVersion int32  `db:"expected_credential_version" json:"expected_credential_version"`
}

func (q *Queries) RotateProfileCredential(ctx context.Context, arg RotateProfileCredentialParams) (HermesApiProfile, error) {
	row := q.db.QueryRow(ctx, rotateProfileCredential,
		arg.Name,
		arg.BaseUrl,
		arg.EncryptedApiKey,
		arg.EncryptionScheme,
		arg.KeyID,
		arg.Nonce,
		arg.AadHash,
		arg.ApiKeyFingerprint,
		arg.ApiKeyHint,
		arg.NewCredentialVersion,
		arg.ID,
		arg.TenantID,
		arg.ExpectedCredentialVersion,
	)
	var i HermesApiProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerUserID,
		&i.Name,
		&i.ProfileKind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseUrl,
		&i.EncryptedApiKey,
		&i.EncryptionScheme,
		&i.KeyID,
		&i.Nonce,
		&i.AadHash,
		&i.ApiKeyFingerprint,
		&i.ApiKeyHint,
		&i.CredentialVersion,
		&i.SecretBindingID,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO hermes_settings (tenant_id, user_id, enabled, api_source, profile_id, model_key)
VALUES (
    $1::bigint,
    $2::bigint,
    $3::boolean,
    $4::text,
    $5::bigint,
    $6::text
)
ON CONFLICT (tenant_id, user_id)
DO UPDATE SET enabled = EXCLUDED.enabled,
              api_source = EXCLUDED.api_source,
              profile_id = EXCLUDED.profile_id,
              model_key = EXCLUDED.model_key,
              updated_at = NOW()
RETURNING tenant_id, user_id, enabled, api_source, profile_id, created_at, updated_at, model_key
`

type UpsertSettingsParams struct {
	TenantID  int64  `db:"tenant_id" json:"tenant_id"`
	UserID    int64  `db:"user_id" json:"user_id"`
	Enabled   bool   `db:"enabled" json:"enabled"`
	APISource string `db:"api_source" json:"api_source"`
	ProfileID *int64 `db:"profile_id" json:"profile_id"`
	ModelKey  string `db:"model_key" json:"model_key"`
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (HermesSetting, error) {
	row := q.db.QueryRow(ctx, upsertSettings,
		arg.TenantID,
		arg.UserID,
		arg.Enabled,
		arg.APISource,
		arg.ProfileID,
		arg.ModelKey,
	)
	var i HermesSetting
	err := row.Scan(
		&i.TenantID,
		&i.UserID,
		&i.Enabled,
		&i.APISource,
		&i.ProfileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelKey,
	)
	return i, err
}
