// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package registry

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// F-PROTO-002: versioned policy. Usage Records reference the version active at translation time for replay correctness.
type ProtocolPolicyVersion struct {
	ID             int64              `db:"id" json:"id"`
	TenantID       int64              `db:"tenant_id" json:"tenant_id"`
	Version        string             `db:"version" json:"version"`
	PolicyData     []byte             `db:"policy_data" json:"policy_data"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `db:"effective_to" json:"effective_to"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedByActor *string            `db:"created_by_actor" json:"created_by_actor"`
}
