// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package registry

import (
	"context"
)

type Querier interface {
	ExpireCurrentProtocolPolicy(ctx context.Context, arg ExpireCurrentProtocolPolicyParams) error
	// F-PROTO-002 protocol policy version registry queries.
	// Backed by protocol_policy_versions table in docs/schema/protocol-translation.sql.
	GetActiveProtocolPolicy(ctx context.Context, tenantID int64) (ProtocolPolicyVersion, error)
	// Resolves the canonical model row, constrained to the requesting tenant
	// (scope='tenant' AND tenant_id=$tenant) OR scope='global'. This blocks
	// a misconfigured tenant alias from reaching another tenant's model row
	// admin-write-time validation).
	GetModelByID(ctx context.Context, arg GetModelByIDParams) (GetModelByIDRow, error)
	GetProtocolPolicyByVersion(ctx context.Context, arg GetProtocolPolicyByVersionParams) (ProtocolPolicyVersion, error)
	// Returns whether a tenant has opted into global-catalog inheritance.
	// Missing row -> nothing returned -> resolver treats as false.
	GetTenantInheritGlobal(ctx context.Context, tenantID int64) (bool, error)
	// Returns the per-tenant registry version stamp. Missing row means the
	// tenant has no admin writes yet; resolver treats as version 1.
	GetTenantSnapshotVersion(ctx context.Context, tenantID int64) (int64, error)
	InsertProtocolPolicyVersion(ctx context.Context, arg InsertProtocolPolicyVersionParams) (InsertProtocolPolicyVersionRow, error)
	// F-PROTO-002 protocol capability matrix queries.
	// Backed by docs/schema/protocol-translation.sql (capability + policy tables).
	ListCapabilityCellsForPair(ctx context.Context, arg ListCapabilityCellsForPairParams) ([]ListCapabilityCellsForPairRow, error)
	ListCapabilityCellsForTenant(ctx context.Context, tenantID int64) ([]ListCapabilityCellsForTenantRow, error)
	ListLossyCellsForOperatorUI(ctx context.Context, tenantID int64) ([]ListLossyCellsForOperatorUIRow, error)
	// Returns capability rows visible to (tenant_id, model_id), including
	// global capabilities for the same model. enabled rows only.
	ListModelCapabilities(ctx context.Context, arg ListModelCapabilitiesParams) ([]ListModelCapabilitiesRow, error)
	// Returns enabled bindings ordered by priority then id, filtered by the
	// effective_from/until time window. ALWAYS tenant-scoped: pool_groups
	// are tenant-owned so a global binding would leak pool_group ids across
	// tenants (addressed by removing the
	// scope column from model_pool_bindings entirely; bindings are inherently
	// tenant-local even for global models). Slice 2 emits all candidates;
	// Router selects index 0 only at L0 (AttemptBudget=1).
	ListModelPoolBindings(ctx context.Context, arg ListModelPoolBindingsParams) ([]ListModelPoolBindingsRow, error)
	// Step 2 of resolve. Only called when tenant lookup misses AND the tenant
	// policy permits global inheritance.
	LookupGlobalAlias(ctx context.Context, aliasLower string) (LookupGlobalAliasRow, error)
	// Slice 2 (N+5a) Model Registry queries.
	// Per docs/process/plans/2026-04-30-n5-model-registry.md.
	// SELECT-only at request time. Snapshot version increments
	// happen via a future Phase E admin writer outside this package.
	// NEVER select credentials; this package never joins
	// provider_accounts.credentials, OAuth tokens, or api_keys.key_hash.
	// Step 1 of resolve. Returns the tenant-scoped alias row regardless of
	// status (active/disabled/deleted-protected). The Go resolver checks
	// status: tenant disabled is an EXPLICIT DENY that blocks global fallback
	// per D3 invariant (integration test).
	LookupTenantAlias(ctx context.Context, arg LookupTenantAliasParams) (LookupTenantAliasRow, error)
	UpsertCapabilityCell(ctx context.Context, arg UpsertCapabilityCellParams) error
}

var _ Querier = (*Queries)(nil)
