// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: billing_settings.sql

package billing

import (
	"context"
)

const getBillingSetting = `-- name: GetBillingSetting :one

SELECT id, tenant_id, setting_key, setting_value, updated_at, updated_by
FROM billing_settings
WHERE tenant_id = $1 AND setting_key = $2
`

type GetBillingSettingParams struct {
	TenantID   int64  `db:"tenant_id" json:"tenant_id"`
	SettingKey string `db:"setting_key" json:"setting_key"`
}

// Case C 计费策略租户级设置的增删改查。表见 migration 0046。
// 按租户和设置键读取单个计费设置。
func (q *Queries) GetBillingSetting(ctx context.Context, arg GetBillingSettingParams) (BillingSetting, error) {
	row := q.db.QueryRow(ctx, getBillingSetting, arg.TenantID, arg.SettingKey)
	var i BillingSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SettingKey,
		&i.SettingValue,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const listBillingSettingsByTenant = `-- name: ListBillingSettingsByTenant :many
SELECT id, tenant_id, setting_key, setting_value, updated_at, updated_by
FROM billing_settings
WHERE tenant_id = $1
ORDER BY setting_key
`

// 列出一个租户的全部计费设置。
func (q *Queries) ListBillingSettingsByTenant(ctx context.Context, tenantID int64) ([]BillingSetting, error) {
	rows, err := q.db.Query(ctx, listBillingSettingsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingSetting
	for rows.Next() {
		var i BillingSetting
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.SettingKey,
			&i.SettingValue,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBillingSetting = `-- name: UpsertBillingSetting :one
INSERT INTO billing_settings (tenant_id, setting_key, setting_value, updated_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, setting_key)
DO UPDATE SET setting_value = EXCLUDED.setting_value,
              updated_at = now(),
              updated_by = EXCLUDED.updated_by
RETURNING id, tenant_id, setting_key, setting_value, updated_at, updated_by
`

type UpsertBillingSettingParams struct {
	TenantID     int64  `db:"tenant_id" json:"tenant_id"`
	SettingKey   string `db:"setting_key" json:"setting_key"`
	SettingValue string `db:"setting_value" json:"setting_value"`
	UpdatedBy    string `db:"updated_by" json:"updated_by"`
}

// 写入或更新单个计费设置; updated_at 总是以数据库时间刷新。
func (q *Queries) UpsertBillingSetting(ctx context.Context, arg UpsertBillingSettingParams) (BillingSetting, error) {
	row := q.db.QueryRow(ctx, upsertBillingSetting,
		arg.TenantID,
		arg.SettingKey,
		arg.SettingValue,
		arg.UpdatedBy,
	)
	var i BillingSetting
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.SettingKey,
		&i.SettingValue,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
