// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package billing

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// Case C 计费策略的租户级设置表, 保存每个租户可配置的计费行为。
type BillingSetting struct {
	ID           int64              `db:"id" json:"id"`
	TenantID     int64              `db:"tenant_id" json:"tenant_id"`
	SettingKey   string             `db:"setting_key" json:"setting_key"`
	SettingValue string             `db:"setting_value" json:"setting_value"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    string             `db:"updated_by" json:"updated_by"`
}

// F-POOL-001 §1: logical capacity grouping; routing policy + Q1..Q4 owner decisions live here.
type PoolGroup struct {
	ID                          int64              `db:"id" json:"id"`
	TenantID                    int64              `db:"tenant_id" json:"tenant_id"`
	Name                        string             `db:"name" json:"name"`
	RoutingPolicyVersion        string             `db:"routing_policy_version" json:"routing_policy_version"`
	TopKDefault                 int32              `db:"top_k_default" json:"top_k_default"`
	CapabilityDefault           string             `db:"capability_default" json:"capability_default"`
	AllowTenantOperatorForce    bool               `db:"allow_tenant_operator_force" json:"allow_tenant_operator_force"`
	AllowLastResort             bool               `db:"allow_last_resort" json:"allow_last_resort"`
	StickyWaitMaxWaiting        int32              `db:"sticky_wait_max_waiting" json:"sticky_wait_max_waiting"`
	FallbackWaitMaxWaiting      int32              `db:"fallback_wait_max_waiting" json:"fallback_wait_max_waiting"`
	StickyWaitTimeoutMs         int32              `db:"sticky_wait_timeout_ms" json:"sticky_wait_timeout_ms"`
	FallbackWaitTimeoutMs       int32              `db:"fallback_wait_timeout_ms" json:"fallback_wait_timeout_ms"`
	ForcedRouteRateLimitPerHour int32              `db:"forced_route_rate_limit_per_hour" json:"forced_route_rate_limit_per_hour"`
	Enabled                     bool               `db:"enabled" json:"enabled"`
	CreatedAt                   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

type SettlementIntent struct {
	ID                 int64              `db:"id" json:"id"`
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	RequestID          string             `db:"request_id" json:"request_id"`
	LogicalRequestID   *string            `db:"logical_request_id" json:"logical_request_id"`
	AttemptSeq         int32              `db:"attempt_seq" json:"attempt_seq"`
	ClaimID            int64              `db:"claim_id" json:"claim_id"`
	APIKeyID           *int64             `db:"api_key_id" json:"api_key_id"`
	RequestFingerprint string             `db:"request_fingerprint" json:"request_fingerprint"`
	Status             string             `db:"status" json:"status"`
	PredictedCost      decimal.Decimal    `db:"predicted_cost" json:"predicted_cost"`
	ActualCost         decimal.Decimal    `db:"actual_cost" json:"actual_cost"`
	HoldID             *int64             `db:"hold_id" json:"hold_id"`
	FirstByteAt        pgtype.Timestamptz `db:"first_byte_at" json:"first_byte_at"`
	RetryCount         int32              `db:"retry_count" json:"retry_count"`
	Version            int32              `db:"version" json:"version"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SettledAt          pgtype.Timestamptz `db:"settled_at" json:"settled_at"`
}
