// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pool_accounts.sql

package billing

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEligibleAccounts = `-- name: ListEligibleAccounts :many
SELECT
    id,
    tenant_id,
    provider_id,
    channel_id,
    name,
    account_type,
    enabled,
    expires_at,
    health_state,
    health_state_until,
    credential_state,
    credentials,
    cap_concurrency,
    in_flight_count,
    cap_queue_sticky,
    cap_queue_fallback,
    queue_depth,
    priority,
    last_dispatch_at,
    model_allow_list,
    capability_flags,
    cap_quota_total,
    quota_used_total,
    cap_quota_daily,
    quota_used_daily,
    quota_window_daily_start,
    cap_quota_weekly,
    quota_used_weekly,
    quota_window_weekly_start,
    quota_status,
    created_at,
    updated_at,
    deleted_at,
    created_by_actor,
    last_modified_by_actor,
    rate_limited_at,
    rate_limit_reset_at,
    rate_limit_reason,
    overload_until,
    temp_unschedulable_until,
    temp_unschedulable_reason,
    temp_unschedulable_rule_index,
    session_window_5h_start,
    session_window_5h_end,
    session_window_5h_status,
    openai_403_counter,
    openai_403_window_start,
    custom_error_codes_enabled,
    custom_error_codes,
    pool_mode,
    temp_unschedulable_enabled,
    temp_unschedulable_rules,
    model_rate_limits,
    refresh_attempt_count,
    refresh_attempt_window_start,
    token_version,
    refresh_token_fingerprint,
    last_refresh_at,
    last_refresh_outcome,
    oauth_endpoint_health
FROM provider_accounts pa
WHERE pa.tenant_id = $1
  AND pa.channel_id = $2
  AND pa.enabled = true
  AND pa.deleted_at IS NULL
  AND (
      pa.health_state = 'healthy'
      OR (
          pa.health_state IN ('throttled', 'revoked', 'cooldown')
          AND pa.health_state_until IS NOT NULL
          AND pa.health_state_until <= NOW()
      )
  )
  -- 凭据真相门:只放至少有一条可服务凭据的账号。真相在 account_credentials.state
  -- (credentialstore 写生命周期),不是冻死的 provider_accounts.credential_state
  -- (无生命周期写点、恒 'valid' → 虚设过滤且放空壳账号进池)。谓词逐字匹配物化
  -- resolveActiveQuery 的可服务判定(active / grace 未过期),使"选到却物化不出"归零。
  AND EXISTS (
      SELECT 1 FROM account_credentials ac
      WHERE ac.provider_account_id = pa.id
        AND ac.tenant_id = pa.tenant_id
        AND ac.deleted_at IS NULL
        AND (
            ac.state = 'active'
            OR (ac.state = 'refreshing_with_grace' AND (ac.grace_until IS NULL OR ac.grace_until > NOW()))
        )
  )
ORDER BY priority, last_dispatch_at NULLS FIRST
`

type ListEligibleAccountsParams struct {
	TenantID  int64 `db:"tenant_id" json:"tenant_id"`
	ChannelID int64 `db:"channel_id" json:"channel_id"`
}

type ListEligibleAccountsRow struct {
	ID                         int64              `db:"id" json:"id"`
	TenantID                   int64              `db:"tenant_id" json:"tenant_id"`
	ProviderID                 int64              `db:"provider_id" json:"provider_id"`
	ChannelID                  int64              `db:"channel_id" json:"channel_id"`
	Name                       string             `db:"name" json:"name"`
	AccountType                string             `db:"account_type" json:"account_type"`
	Enabled                    bool               `db:"enabled" json:"enabled"`
	ExpiresAt                  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	HealthState                string             `db:"health_state" json:"health_state"`
	HealthStateUntil           pgtype.Timestamptz `db:"health_state_until" json:"health_state_until"`
	CredentialState            string             `db:"credential_state" json:"credential_state"`
	Credentials                []byte             `db:"credentials" json:"credentials"`
	CapConcurrency             int32              `db:"cap_concurrency" json:"cap_concurrency"`
	InFlightCount              int32              `db:"in_flight_count" json:"in_flight_count"`
	CapQueueSticky             int32              `db:"cap_queue_sticky" json:"cap_queue_sticky"`
	CapQueueFallback           int32              `db:"cap_queue_fallback" json:"cap_queue_fallback"`
	QueueDepth                 int32              `db:"queue_depth" json:"queue_depth"`
	Priority                   int32              `db:"priority" json:"priority"`
	LastDispatchAt             pgtype.Timestamptz `db:"last_dispatch_at" json:"last_dispatch_at"`
	ModelAllowList             []string           `db:"model_allow_list" json:"model_allow_list"`
	CapabilityFlags            []string           `db:"capability_flags" json:"capability_flags"`
	CapQuotaTotal              pgtype.Numeric     `db:"cap_quota_total" json:"cap_quota_total"`
	QuotaUsedTotal             pgtype.Numeric     `db:"quota_used_total" json:"quota_used_total"`
	CapQuotaDaily              pgtype.Numeric     `db:"cap_quota_daily" json:"cap_quota_daily"`
	QuotaUsedDaily             pgtype.Numeric     `db:"quota_used_daily" json:"quota_used_daily"`
	QuotaWindowDailyStart      pgtype.Timestamptz `db:"quota_window_daily_start" json:"quota_window_daily_start"`
	CapQuotaWeekly             pgtype.Numeric     `db:"cap_quota_weekly" json:"cap_quota_weekly"`
	QuotaUsedWeekly            pgtype.Numeric     `db:"quota_used_weekly" json:"quota_used_weekly"`
	QuotaWindowWeeklyStart     pgtype.Timestamptz `db:"quota_window_weekly_start" json:"quota_window_weekly_start"`
	QuotaStatus                string             `db:"quota_status" json:"quota_status"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedByActor             *string            `db:"created_by_actor" json:"created_by_actor"`
	LastModifiedByActor        *string            `db:"last_modified_by_actor" json:"last_modified_by_actor"`
	RateLimitedAt              pgtype.Timestamptz `db:"rate_limited_at" json:"rate_limited_at"`
	RateLimitResetAt           pgtype.Timestamptz `db:"rate_limit_reset_at" json:"rate_limit_reset_at"`
	RateLimitReason            *string            `db:"rate_limit_reason" json:"rate_limit_reason"`
	OverloadUntil              pgtype.Timestamptz `db:"overload_until" json:"overload_until"`
	TempUnschedulableUntil     pgtype.Timestamptz `db:"temp_unschedulable_until" json:"temp_unschedulable_until"`
	TempUnschedulableReason    *string            `db:"temp_unschedulable_reason" json:"temp_unschedulable_reason"`
	TempUnschedulableRuleIndex *int32             `db:"temp_unschedulable_rule_index" json:"temp_unschedulable_rule_index"`
	SessionWindow5hStart       pgtype.Timestamptz `db:"session_window_5h_start" json:"session_window_5h_start"`
	SessionWindow5hEnd         pgtype.Timestamptz `db:"session_window_5h_end" json:"session_window_5h_end"`
	SessionWindow5hStatus      *string            `db:"session_window_5h_status" json:"session_window_5h_status"`
	OpenAI403Counter           int32              `db:"openai_403_counter" json:"openai_403_counter"`
	Openai403WindowStart       pgtype.Timestamptz `db:"openai_403_window_start" json:"openai_403_window_start"`
	CustomErrorCodesEnabled    bool               `db:"custom_error_codes_enabled" json:"custom_error_codes_enabled"`
	CustomErrorCodes           []int32            `db:"custom_error_codes" json:"custom_error_codes"`
	PoolMode                   bool               `db:"pool_mode" json:"pool_mode"`
	TempUnschedulableEnabled   bool               `db:"temp_unschedulable_enabled" json:"temp_unschedulable_enabled"`
	TempUnschedulableRules     []byte             `db:"temp_unschedulable_rules" json:"temp_unschedulable_rules"`
	ModelRateLimits            []byte             `db:"model_rate_limits" json:"model_rate_limits"`
	RefreshAttemptCount        int32              `db:"refresh_attempt_count" json:"refresh_attempt_count"`
	RefreshAttemptWindowStart  pgtype.Timestamptz `db:"refresh_attempt_window_start" json:"refresh_attempt_window_start"`
	TokenVersion               int32              `db:"token_version" json:"token_version"`
	RefreshTokenFingerprint    *string            `db:"refresh_token_fingerprint" json:"refresh_token_fingerprint"`
	LastRefreshAt              pgtype.Timestamptz `db:"last_refresh_at" json:"last_refresh_at"`
	LastRefreshOutcome         *string            `db:"last_refresh_outcome" json:"last_refresh_outcome"`
	OAuthEndpointHealth        string             `db:"oauth_endpoint_health" json:"oauth_endpoint_health"`
}

func (q *Queries) ListEligibleAccounts(ctx context.Context, arg ListEligibleAccountsParams) ([]ListEligibleAccountsRow, error) {
	rows, err := q.db.Query(ctx, listEligibleAccounts, arg.TenantID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleAccountsRow
	for rows.Next() {
		var i ListEligibleAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderID,
			&i.ChannelID,
			&i.Name,
			&i.AccountType,
			&i.Enabled,
			&i.ExpiresAt,
			&i.HealthState,
			&i.HealthStateUntil,
			&i.CredentialState,
			&i.Credentials,
			&i.CapConcurrency,
			&i.InFlightCount,
			&i.CapQueueSticky,
			&i.CapQueueFallback,
			&i.QueueDepth,
			&i.Priority,
			&i.LastDispatchAt,
			&i.ModelAllowList,
			&i.CapabilityFlags,
			&i.CapQuotaTotal,
			&i.QuotaUsedTotal,
			&i.CapQuotaDaily,
			&i.QuotaUsedDaily,
			&i.QuotaWindowDailyStart,
			&i.CapQuotaWeekly,
			&i.QuotaUsedWeekly,
			&i.QuotaWindowWeeklyStart,
			&i.QuotaStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedByActor,
			&i.LastModifiedByActor,
			&i.RateLimitedAt,
			&i.RateLimitResetAt,
			&i.RateLimitReason,
			&i.OverloadUntil,
			&i.TempUnschedulableUntil,
			&i.TempUnschedulableReason,
			&i.TempUnschedulableRuleIndex,
			&i.SessionWindow5hStart,
			&i.SessionWindow5hEnd,
			&i.SessionWindow5hStatus,
			&i.OpenAI403Counter,
			&i.Openai403WindowStart,
			&i.CustomErrorCodesEnabled,
			&i.CustomErrorCodes,
			&i.PoolMode,
			&i.TempUnschedulableEnabled,
			&i.TempUnschedulableRules,
			&i.ModelRateLimits,
			&i.RefreshAttemptCount,
			&i.RefreshAttemptWindowStart,
			&i.TokenVersion,
			&i.RefreshTokenFingerprint,
			&i.LastRefreshAt,
			&i.LastRefreshOutcome,
			&i.OAuthEndpointHealth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleAccountsByPoolGroup = `-- name: ListEligibleAccountsByPoolGroup :many
WITH target_channels AS (
    SELECT c.id
    FROM channels c
    WHERE c.pool_group_id = $3
      AND c.tenant_id = $2
      AND c.enabled = true
      AND c.deleted_at IS NULL
)
SELECT
    pa.id,
    pa.tenant_id,
    pa.provider_id,
    p.upstream_protocol,
    pa.channel_id,
    pa.cap_concurrency,
    pa.in_flight_count,
    pa.priority,
    pa.static_weight,
    pa.upstream_cost_ratio,
    pa.last_dispatch_at,
    pa.health_state,
    pa.health_state_until,
    pa.model_rate_limits,
    pa.model_allow_list,
    pa.capability_flags,
    pa.cap_queue_sticky,
    pa.cap_queue_fallback,
    pa.window_cost_limit_cents,
    pa.max_sessions,
    pa.disable_cooling,
    pa.rpm_limit,
    pa.tpm_limit,
    rs.success_ewma,
    rs.error_ewma,
    rs.response_latency_ms_ewma,
    rs.sample_count AS routing_signal_sample_count,
    rs.observed_at AS routing_signal_observed_at,
    quota.state AS upstream_quota_state,
    CASE WHEN quota.remaining_percent IS NULL THEN false ELSE true END AS upstream_quota_remaining_known,
    COALESCE(quota.remaining_percent, 0::double precision) AS upstream_quota_remaining_percent,
    quota.resets_at AS upstream_quota_resets_at,
    quota.observed_at AS upstream_quota_observed_at
FROM provider_accounts pa
INNER JOIN channels c
    ON c.id = pa.channel_id
   AND c.enabled = true
   AND c.deleted_at IS NULL
INNER JOIN providers p
    ON p.id = pa.provider_id
   AND p.tenant_id = pa.tenant_id
   AND p.deleted_at IS NULL
LEFT JOIN provider_account_routing_signals rs
    ON rs.tenant_id = pa.tenant_id
   AND rs.provider_account_id = pa.id
LEFT JOIN LATERAL (
    SELECT
        CASE
            WHEN bool_or(q.state = 'exhausted') THEN 'exhausted'
            WHEN bool_or(q.state = 'available') THEN 'available'
            WHEN bool_or(q.state = 'error') THEN 'error'
            ELSE 'unknown'
        END::text AS state,
        (min(q.remaining_percent) FILTER (WHERE q.state IN ('available', 'exhausted')))::double precision AS remaining_percent,
        (min(q.resets_at) FILTER (WHERE q.state IN ('available', 'exhausted')))::timestamptz AS resets_at,
        max(q.observed_at)::timestamptz AS observed_at
    FROM provider_account_quota_facts q
    WHERE q.tenant_id = pa.tenant_id
      AND q.provider_account_id = pa.id
      AND q.metric_key <> 'probe_status'
      AND (q.model_key = '' OR q.model_key = $1::text)
      AND q.observed_at > NOW() - INTERVAL '2 hours'
      AND (q.valid_until IS NULL OR q.valid_until > NOW())
) quota ON true
WHERE pa.tenant_id = $2
  AND c.pool_group_id = $3
  AND c.tenant_id = $2
  AND pa.enabled = true
  AND pa.deleted_at IS NULL
  -- 未设过期时间(NULL)的账号不受影响;已过期账号排除出选号候选。
  AND (pa.expires_at IS NULL OR pa.expires_at > NOW())
  AND (
      pa.health_state = 'healthy'
      OR (
          pa.health_state IN ('throttled', 'revoked', 'cooldown')
          AND pa.health_state_until IS NOT NULL
          AND pa.health_state_until <= NOW()
      )
  )
  AND (cardinality(pa.model_allow_list) = 0
       OR pa.model_allow_list @> ARRAY[$1::text])
  AND ($4::text = ''
       OR p.upstream_protocol = $4::text)
  AND pa.capability_flags @> $5::text[]
  -- 凭据真相门:只放至少有一条可服务凭据的账号。此前过滤 pa.credential_state
  -- (冻死列、无生命周期写点、恒 'valid') 是虚设过滤且放空壳账号进池;改读真相
  -- account_credentials.state(credentialstore 写生命周期)。谓词逐字匹配物化
  -- resolveActiveQuery 的可服务判定(active / grace 未过期),防 selector 选到无
  -- 可用凭据账号 → 物化落空浪费一轮。EXISTS 保一账号一行(多凭据不放大行数)。
  AND EXISTS (
      SELECT 1 FROM account_credentials ac
      WHERE ac.provider_account_id = pa.id
        AND ac.tenant_id = pa.tenant_id
        AND ac.deleted_at IS NULL
        AND (
            ac.state = 'active'
            OR (ac.state = 'refreshing_with_grace' AND (ac.grace_until IS NULL OR ac.grace_until > NOW()))
        )
  )
ORDER BY pa.priority, pa.last_dispatch_at NULLS FIRST
`

type ListEligibleAccountsByPoolGroupParams struct {
	RequestedModel          string   `db:"requested_model" json:"requested_model"`
	TenantID                int64    `db:"tenant_id" json:"tenant_id"`
	PoolGroupID             int64    `db:"pool_group_id" json:"pool_group_id"`
	RequestedProtocolFamily string   `db:"requested_protocol_family" json:"requested_protocol_family"`
	RequiredCapabilities    []string `db:"required_capabilities" json:"required_capabilities"`
}

type ListEligibleAccountsByPoolGroupRow struct {
	ID                            int64              `db:"id" json:"id"`
	TenantID                      int64              `db:"tenant_id" json:"tenant_id"`
	ProviderID                    int64              `db:"provider_id" json:"provider_id"`
	UpstreamProtocol              string             `db:"upstream_protocol" json:"upstream_protocol"`
	ChannelID                     int64              `db:"channel_id" json:"channel_id"`
	CapConcurrency                int32              `db:"cap_concurrency" json:"cap_concurrency"`
	InFlightCount                 int32              `db:"in_flight_count" json:"in_flight_count"`
	Priority                      int32              `db:"priority" json:"priority"`
	StaticWeight                  int32              `db:"static_weight" json:"static_weight"`
	UpstreamCostRatio             *float64           `db:"upstream_cost_ratio" json:"upstream_cost_ratio"`
	LastDispatchAt                pgtype.Timestamptz `db:"last_dispatch_at" json:"last_dispatch_at"`
	HealthState                   string             `db:"health_state" json:"health_state"`
	HealthStateUntil              pgtype.Timestamptz `db:"health_state_until" json:"health_state_until"`
	ModelRateLimits               []byte             `db:"model_rate_limits" json:"model_rate_limits"`
	ModelAllowList                []string           `db:"model_allow_list" json:"model_allow_list"`
	CapabilityFlags               []string           `db:"capability_flags" json:"capability_flags"`
	CapQueueSticky                int32              `db:"cap_queue_sticky" json:"cap_queue_sticky"`
	CapQueueFallback              int32              `db:"cap_queue_fallback" json:"cap_queue_fallback"`
	WindowCostLimitCents          int64              `db:"window_cost_limit_cents" json:"window_cost_limit_cents"`
	MaxSessions                   int32              `db:"max_sessions" json:"max_sessions"`
	DisableCooling                bool               `db:"disable_cooling" json:"disable_cooling"`
	RpmLimit                      int64              `db:"rpm_limit" json:"rpm_limit"`
	TpmLimit                      int64              `db:"tpm_limit" json:"tpm_limit"`
	SuccessEwma                   *float64           `db:"success_ewma" json:"success_ewma"`
	ErrorEwma                     *float64           `db:"error_ewma" json:"error_ewma"`
	ResponseLatencyMsEwma         *float64           `db:"response_latency_ms_ewma" json:"response_latency_ms_ewma"`
	RoutingSignalSampleCount      *int64             `db:"routing_signal_sample_count" json:"routing_signal_sample_count"`
	RoutingSignalObservedAt       pgtype.Timestamptz `db:"routing_signal_observed_at" json:"routing_signal_observed_at"`
	UpstreamQuotaState            string             `db:"upstream_quota_state" json:"upstream_quota_state"`
	UpstreamQuotaRemainingKnown   bool               `db:"upstream_quota_remaining_known" json:"upstream_quota_remaining_known"`
	UpstreamQuotaRemainingPercent float64            `db:"upstream_quota_remaining_percent" json:"upstream_quota_remaining_percent"`
	UpstreamQuotaResetsAt         pgtype.Timestamptz `db:"upstream_quota_resets_at" json:"upstream_quota_resets_at"`
	UpstreamQuotaObservedAt       pgtype.Timestamptz `db:"upstream_quota_observed_at" json:"upstream_quota_observed_at"`
}

// Phase C.2: pool-group-keyed eligibility lookup for the gateway selector.
// Joins channels → provider_accounts so a SelectionRequest with PoolGroupID
// (and no explicit ChannelID) can resolve to the candidate account set.
// cap_queue_sticky/fallback are returned so the selector can construct
// WaitPlan fallback when every eligible account is at concurrency cap.
//
// 2026-05-19 codex review P1 fix: 之前不过滤 model_allow_list /
// capability_flags, production gate AllowAll 全过, request 能 reserve
// 到明确不被该 account 允许的 model / 缺能力。两个 filter 直接在 SQL
// 层做 (Postgres array @> 子集 + cardinality empty bypass):
//   - model_allow_list 空 数组 → 无限制
//   - model_allow_list 非空 → 必须包含 requested_model
//   - capability_flags 必须包含 required_capabilities 全集 (空 req → 自动 true)
//   - requested_protocol_family 为空 → legacy bypass
//   - requested_protocol_family 非空 → 必须匹配 providers.upstream_protocol
func (q *Queries) ListEligibleAccountsByPoolGroup(ctx context.Context, arg ListEligibleAccountsByPoolGroupParams) ([]ListEligibleAccountsByPoolGroupRow, error) {
	rows, err := q.db.Query(ctx, listEligibleAccountsByPoolGroup,
		arg.RequestedModel,
		arg.TenantID,
		arg.PoolGroupID,
		arg.RequestedProtocolFamily,
		arg.RequiredCapabilities,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleAccountsByPoolGroupRow
	for rows.Next() {
		var i ListEligibleAccountsByPoolGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderID,
			&i.UpstreamProtocol,
			&i.ChannelID,
			&i.CapConcurrency,
			&i.InFlightCount,
			&i.Priority,
			&i.StaticWeight,
			&i.UpstreamCostRatio,
			&i.LastDispatchAt,
			&i.HealthState,
			&i.HealthStateUntil,
			&i.ModelRateLimits,
			&i.ModelAllowList,
			&i.CapabilityFlags,
			&i.CapQueueSticky,
			&i.CapQueueFallback,
			&i.WindowCostLimitCents,
			&i.MaxSessions,
			&i.DisableCooling,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.SuccessEwma,
			&i.ErrorEwma,
			&i.ResponseLatencyMsEwma,
			&i.RoutingSignalSampleCount,
			&i.RoutingSignalObservedAt,
			&i.UpstreamQuotaState,
			&i.UpstreamQuotaRemainingKnown,
			&i.UpstreamQuotaRemainingPercent,
			&i.UpstreamQuotaResetsAt,
			&i.UpstreamQuotaObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
