// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package billing

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Tx2 abort path: terminal upstream failure or AMBIGUOUS_USAGE end class.
	// codex chunk7 P1#4: tenant_id 必须显式预先 caller 提供, 防全局 id 跨租户误改。
	AbortClaim(ctx context.Context, arg AbortClaimParams) (int64, error)
	// 首次写入时目标行还不存在, FOR UPDATE 无法锁住空行; 先拿事务级顾问锁
	// 按租户和设置键串行化同一设置的读改写, 提交或回滚后自动释放。
	AcquireBillingSettingLock(ctx context.Context, arg AcquireBillingSettingLockParams) error
	AcquireBindingConcurrencyLock(ctx context.Context, bindingID int64) error
	// Usage analytics: aggregation queries over settled usage_records.
	// SELECT-only. Self-serve queries carry a non-nullable tenant_id
	// predicate (cross-tenant prevention). Admin leaderboard queries are
	// platform-admin-only and intentionally aggregate across tenants for operator
	// cost visibility. No query selects credential columns.
	// usage_records.settled_at is NOT NULL DEFAULT now() and indexed by
	// idx_usage_records_tenant_settled (tenant_id, settled_at DESC), so these
	// aggregations need no new index in the pre-launch first cut.
	// Self-serve daily usage time-series for ONE API key: cost + token totals
	// bucketed by UTC calendar day and requested_model. Always scoped by
	// (tenant_id, api_key_id) so cross-key reads are structurally impossible —
	// the handler passes ident.APIKeyID, never a client-supplied value.
	AggregateMyUsageByDay(ctx context.Context, arg AggregateMyUsageByDayParams) ([]AggregateMyUsageByDayRow, error)
	// Self-serve monthly usage time-series for ONE API key: cost + token totals
	// bucketed by UTC month start and requested_model. Always scoped by
	// (tenant_id, api_key_id) so cross-key reads are structurally impossible —
	// the handler passes ident.APIKeyID, never a client-supplied value.
	AggregateMyUsageByMonth(ctx context.Context, arg AggregateMyUsageByMonthParams) ([]AggregateMyUsageByMonthRow, error)
	// Self-serve weekly usage time-series for ONE API key: cost + token totals
	// bucketed by UTC week start and requested_model. Always scoped by
	// (tenant_id, api_key_id) so cross-key reads are structurally impossible —
	// the handler passes ident.APIKeyID, never a client-supplied value.
	AggregateMyUsageByWeek(ctx context.Context, arg AggregateMyUsageByWeekParams) ([]AggregateMyUsageByWeekRow, error)
	// Self-serve single-row usage totals for one caller-owned API key. The handler
	// first verifies (tenant_id, user_id, api_key_id) ownership through userkey
	// service; this query still carries tenant_id + api_key_id predicates so a
	// handler bug cannot widen the read to another tenant or another key.
	AggregateMyUsageTotals(ctx context.Context, arg AggregateMyUsageTotalsParams) (AggregateMyUsageTotalsRow, error)
	// Platform-admin read-only usage count/cost totals by provider account over a
	// bounded settled_at window. Optional tenant_id narrows operator analysis
	// without changing money-path writes or settlement behavior.
	AggregateUsageCountsByProviderAccount(ctx context.Context, arg AggregateUsageCountsByProviderAccountParams) ([]AggregateUsageCountsByProviderAccountRow, error)
	// Global/requested_model TTFT percentiles for the recent settled usage window.
	// The array keeps the percentile definition adjacent so P50/P95/P99 cannot
	// drift independently.
	AggregateUsageLatencyPercentiles(ctx context.Context, arg AggregateUsageLatencyPercentilesParams) (AggregateUsageLatencyPercentilesRow, error)
	// Platform-admin cost leaderboard by api_key_id. Passing tenant_id=0 keeps
	// the existing global admin leaderboard behavior; a positive tenant_id narrows
	// the read-only rollup to that tenant for tenant-focused ops drilldown.
	AggregateUsageLeaderboardByApiKey(ctx context.Context, arg AggregateUsageLeaderboardByApiKeyParams) ([]AggregateUsageLeaderboardByApiKeyRow, error)
	// Platform-admin cost leaderboard by requested_model.
	AggregateUsageLeaderboardByModel(ctx context.Context, arg AggregateUsageLeaderboardByModelParams) ([]AggregateUsageLeaderboardByModelRow, error)
	// Platform-admin cost leaderboard by provider_account_id. Provider-less
	// usage, such as cache-only settlement, is grouped under "unassigned".
	AggregateUsageLeaderboardByProviderAccount(ctx context.Context, arg AggregateUsageLeaderboardByProviderAccountParams) ([]AggregateUsageLeaderboardByProviderAccountRow, error)
	// Platform-admin cost leaderboard by user_id. This is the operator surface:
	// actual_cost is intentionally used to show real upstream spend.
	AggregateUsageLeaderboardByUser(ctx context.Context, arg AggregateUsageLeaderboardByUserParams) ([]AggregateUsageLeaderboardByUserRow, error)
	// Platform-admin overview totals across the recent settled usage window.
	// Operator surface: actual_cost is intentionally exposed as decimal text.
	AggregateUsageOverviewTotals(ctx context.Context, settledSince pgtype.Timestamptz) (AggregateUsageOverviewTotalsRow, error)
	// Platform-admin overview daily trend across the recent settled usage window.
	AggregateUsageOverviewTrendByDay(ctx context.Context, settledSince pgtype.Timestamptz) ([]AggregateUsageOverviewTrendByDayRow, error)
	// Platform-admin performance panel by requested_model. Read-only operator
	// surface: latency, throughput, and error rate inputs only; no cost fields.
	AggregateUsagePerformanceByModel(ctx context.Context, arg AggregateUsagePerformanceByModelParams) ([]AggregateUsagePerformanceByModelRow, error)
	// Platform-admin performance panel by UTC requested_at bucket and
	// requested_model. The caller must validate bucket is one of hour/day before
	// calling this query.
	AggregateUsagePerformanceByModelBucketed(ctx context.Context, arg AggregateUsagePerformanceByModelBucketedParams) ([]AggregateUsagePerformanceByModelBucketedRow, error)
	// Platform-admin performance panel by provider_account_id. Provider-less
	// usage, such as cache-only settlement, is grouped under "unassigned".
	AggregateUsagePerformanceByProviderAccount(ctx context.Context, arg AggregateUsagePerformanceByProviderAccountParams) ([]AggregateUsagePerformanceByProviderAccountRow, error)
	// Platform-admin performance summary across the recent settled usage window,
	// optionally narrowed to one requested_model. Read-only operator surface:
	// latency, throughput, request count, and error count only; no cost fields.
	AggregateUsagePerformanceSummary(ctx context.Context, arg AggregateUsagePerformanceSummaryParams) (AggregateUsagePerformanceSummaryRow, error)
	ApplyBalanceHoldCapture(ctx context.Context, arg ApplyBalanceHoldCaptureParams) (ApplyBalanceHoldCaptureRow, error)
	ApplyBalanceHoldRelease(ctx context.Context, arg ApplyBalanceHoldReleaseParams) (ApplyBalanceHoldReleaseRow, error)
	CaptureBalanceHold(ctx context.Context, arg CaptureBalanceHoldParams) (int64, error)
	CountActiveBindingAcquisitions(ctx context.Context, bindingID int64) (int64, error)
	CountAuditEvents(ctx context.Context, arg CountAuditEventsParams) (int64, error)
	CountBillingClaims(ctx context.Context, arg CountBillingClaimsParams) (int64, error)
	CountPendingReconciliationUsageRecords(ctx context.Context) (int64, error)
	CountUnhealthyAccountsByTenant(ctx context.Context, tenantID int64) ([]CountUnhealthyAccountsByTenantRow, error)
	CountUnresolvedSettlementIntentsForClaim(ctx context.Context, arg CountUnresolvedSettlementIntentsForClaimParams) (int64, error)
	CountUsageRecords(ctx context.Context, arg CountUsageRecordsParams) (int64, error)
	DecrementInFlightCount(ctx context.Context, id int64) error
	DeleteExpiredStickyBindings(ctx context.Context) error
	DeletePool(ctx context.Context, arg DeletePoolParams) (PoolGroup, error)
	ExpediteAbortLease(ctx context.Context, arg ExpediteAbortLeaseParams) (int64, error)
	GetAccountForRevalidation(ctx context.Context, arg GetAccountForRevalidationParams) (GetAccountForRevalidationRow, error)
	GetBalanceHoldForUpdate(ctx context.Context, claimID int64) (GetBalanceHoldForUpdateRow, error)
	// Case C 计费策略租户级设置的增删改查。表见 migration 0046。
	// 按租户和设置键读取单个计费设置。
	GetBillingSetting(ctx context.Context, arg GetBillingSettingParams) (BillingSetting, error)
	// 事务内按租户和设置键读取并锁住现有计费设置。
	GetBillingSettingForUpdate(ctx context.Context, arg GetBillingSettingForUpdateParams) (BillingSetting, error)
	// 结算意图追平只读取权威 claim 的终态、尝试序号和实际费用，并强制租户隔离。
	GetClaimByID(ctx context.Context, arg GetClaimByIDParams) (GetClaimByIDRow, error)
	// F-OBS-001 Tx1/Tx2 billing ledger claim queries.
	// Backed by billing_ledger_claims in docs/schema/observability-billing.sql.
	// Hot-path Tx1 lookup with FOR UPDATE row lock per spec §Tx1 step 2.
	// Selects ONLY the columns the gate needs to make a control-flow decision;
	// nullable money/token fields (actual_cost, acquisition_token) are populated
	// in Tx2 and would otherwise force NullDecimal/pgtype.UUID round-trips on
	// every replay lookup. Other audit fields are queried separately when needed.
	GetClaimByIdempotency(ctx context.Context, arg GetClaimByIdempotencyParams) (GetClaimByIdempotencyRow, error)
	// Replay-attack detection: same logical_request_id with different fingerprint
	// means an attacker reused the request id across different payloads. Spec §Tx1 step 3
	// third bullet → return FINGERPRINT_CONFLICT (409). Hash differs so the unique
	// idempotency index does NOT catch this; we scan by logical_request_id.
	GetClaimFingerprintByLogicalRequestID(ctx context.Context, arg GetClaimFingerprintByLogicalRequestIDParams) ([]GetClaimFingerprintByLogicalRequestIDRow, error)
	// F-OBS-001 Tx2 Settler queries.
	// Backed by billing_ledger_claims + usage_records + billing_events tables
	// in docs/schema/observability-billing.sql + scheduler_outbox in
	// docs/schema/pool-routing.sql.
	// Tx2 entry: lock the claim row + verify still-settle-able state.
	// Spec §Tx2 step 9: re-fetch claim row; verify status='reserving' AND
	// acquisition_token matches.
	GetClaimForSettle(ctx context.Context, arg GetClaimForSettleParams) (GetClaimForSettleRow, error)
	GetModelRoutingForGroup(ctx context.Context, arg GetModelRoutingForGroupParams) ([]GetModelRoutingForGroupRow, error)
	GetPool(ctx context.Context, arg GetPoolParams) (PoolGroup, error)
	GetSettlementIntentByClaimAttempt(ctx context.Context, arg GetSettlementIntentByClaimAttemptParams) (SettlementIntent, error)
	GetStickyBinding(ctx context.Context, arg GetStickyBindingParams) (int64, error)
	GetUsageRecordByRequestID(ctx context.Context, arg GetUsageRecordByRequestIDParams) (GetUsageRecordByRequestIDRow, error)
	GetUserBalance(ctx context.Context, arg GetUserBalanceParams) (GetUserBalanceRow, error)
	IncrementInFlightCount(ctx context.Context, arg IncrementInFlightCountParams) (int64, error)
	// Spec §Tx2 step 13: audit-grade event row in same Tx; survives Usage Record
	// async failure (per F-OBS-001 H8). event_type per CHECK constraint.
	InsertBillingEvent(ctx context.Context, arg InsertBillingEventParams) (InsertBillingEventRow, error)
	// Insert a new reserving claim. Caller MUST hold the row lock acquired via
	// GetClaimByIdempotency (which returns 0 rows when no prior claim exists),
	// so this insert is conflict-free under serializable isolation.
	InsertClaim(ctx context.Context, arg InsertClaimParams) (InsertClaimRow, error)
	// Admin Pool Group CRUD (F-POOL-001).
	InsertPool(ctx context.Context, arg InsertPoolParams) (PoolGroup, error)
	InsertPoolRoutingAuditEvent(ctx context.Context, arg InsertPoolRoutingAuditEventParams) error
	// Spec §Tx2 step 11: cross-threshold notification, in same Tx.
	// For Phase B.5 v0.1, the threshold detection itself is stubbed (operator
	// policy returns false unless explicitly forced in test); when the policy
	// returns true, this query enqueues the row.
	InsertSchedulerOutboxRow(ctx context.Context, arg InsertSchedulerOutboxRowParams) (InsertSchedulerOutboxRowRow, error)
	// 结算意图在首个业务字节前写入。balance_holds 以 claim_id 为主键，
	// 因此这里只在真实 hold 行存在时记录该稳定标识；未启用余额强制的请求保持 NULL。
	InsertSettlementIntent(ctx context.Context, arg InsertSettlementIntentParams) (int64, error)
	InsertSlotAcquisition(ctx context.Context, arg InsertSlotAcquisitionParams) (int64, error)
	// Spec §Tx2 step 12: write Usage Record into the same Tx as everything else.
	// Slice 2 (N+5b 2026-05-01): added snapshot_version (column from migration
	// 0008). Format documented there as "registry:<tid>:<v>;router:<rv>".
	InsertUsageRecord(ctx context.Context, arg InsertUsageRecordParams) (int64, error)
	ListAccountsForRefresh(ctx context.Context, arg ListAccountsForRefreshParams) ([]ListAccountsForRefreshRow, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error)
	ListBillingClaims(ctx context.Context, arg ListBillingClaimsParams) ([]ListBillingClaimsRow, error)
	// 列出一个租户的全部计费设置。
	ListBillingSettingsByTenant(ctx context.Context, tenantID int64) ([]BillingSetting, error)
	ListEligibleAccounts(ctx context.Context, arg ListEligibleAccountsParams) ([]ListEligibleAccountsRow, error)
	// Phase C.2: pool-group-keyed eligibility lookup for the gateway selector.
	// Joins channels → provider_accounts so a SelectionRequest with PoolGroupID
	// (and no explicit ChannelID) can resolve to the candidate account set.
	// cap_queue_sticky/fallback are returned so the selector can construct
	// WaitPlan fallback when every eligible account is at concurrency cap.
	//
	// 2026-05-19 codex review P1 fix: 之前不过滤 model_allow_list /
	// capability_flags, production gate AllowAll 全过, request 能 reserve
	// 到明确不被该 account 允许的 model / 缺能力。两个 filter 直接在 SQL
	// 层做 (Postgres array @> 子集 + cardinality empty bypass):
	//   - model_allow_list 空 数组 → 无限制
	//   - model_allow_list 非空 → 必须包含 requested_model
	//   - capability_flags 必须包含 required_capabilities 全集 (空 req → 自动 true)
	//   - requested_protocol_family 为空 → legacy bypass
	//   - requested_protocol_family 非空 → 必须匹配 providers.upstream_protocol
	ListEligibleAccountsByPoolGroup(ctx context.Context, arg ListEligibleAccountsByPoolGroupParams) ([]ListEligibleAccountsByPoolGroupRow, error)
	ListOrphanedAcquisitions(ctx context.Context) ([]ListOrphanedAcquisitionsRow, error)
	ListPools(ctx context.Context, arg ListPoolsParams) ([]PoolGroup, error)
	// 账号健康诊断只读取请求结果与时延信号，刻意不选择 actual_cost 等钱字段。
	// tenant_id 与 provider_account_id 同时下推，避免仅靠处理器作用域保护租户边界。
	ListProviderAccountRecentRequests(ctx context.Context, arg ListProviderAccountRecentRequestsParams) ([]ListProviderAccountRecentRequestsRow, error)
	ListStaleNonTerminalSettlementIntents(ctx context.Context, arg ListStaleNonTerminalSettlementIntentsParams) ([]ListStaleNonTerminalSettlementIntentsRow, error)
	// F-OBS-001 admin read APIs. SELECT-only: no hot-path, quota, billing,
	// auth, or trust-chain mutation is allowed here.
	ListUsageRecords(ctx context.Context, arg ListUsageRecordsParams) ([]ListUsageRecordsRow, error)
	// Sibling of ListUsageRecords with display names joined for admin/operator UI.
	// Tenant predicates on api_keys/users are deliberate defense-in-depth even
	// though those ids are globally unique today.
	ListUsageRecordsWithNames(ctx context.Context, arg ListUsageRecordsWithNamesParams) ([]ListUsageRecordsWithNamesRow, error)
	MarkSettlementIntentAborted(ctx context.Context, arg MarkSettlementIntentAbortedParams) (int32, error)
	MarkSettlementIntentAbortedIfStale(ctx context.Context, arg MarkSettlementIntentAbortedIfStaleParams) (int32, error)
	MarkSettlementIntentDelivering(ctx context.Context, arg MarkSettlementIntentDeliveringParams) (int32, error)
	MarkSettlementIntentFailed(ctx context.Context, arg MarkSettlementIntentFailedParams) (int32, error)
	MarkSettlementIntentSettled(ctx context.Context, arg MarkSettlementIntentSettledParams) (int32, error)
	MarkSettlementIntentSettledIfStale(ctx context.Context, arg MarkSettlementIntentSettledIfStaleParams) (int32, error)
	MarkSettlementIntentSettling(ctx context.Context, arg MarkSettlementIntentSettlingParams) (int32, error)
	MarkSettlementIntentSupersededIfStale(ctx context.Context, arg MarkSettlementIntentSupersededIfStaleParams) (int32, error)
	// Usage-log retention only. Deletes bounded batches from usage_records and
	// deliberately does not touch billing_ledger_claims, billing_events, audit
	// tables, or other money/trust-chain records.
	PurgeUsageRecordsBefore(ctx context.Context, arg PurgeUsageRecordsBeforeParams) (int64, error)
	// Re-attempt path: an earlier attempt aborted (transient upstream failure,
	// not FINGERPRINT_CONFLICT). Operator policy allows resurrecting the row
	// under the same idempotency_key rather than inserting a duplicate (which
	// would violate uq_claims_idempotency). attempt_seq increments so audits
	// can count retries. Returns the row's id and bumped attempt_seq.
	ReReserveAbortedClaim(ctx context.Context, arg ReReserveAbortedClaimParams) (ReReserveAbortedClaimRow, error)
	// Alerting per-tenant recent usage rollup. This is intentionally tenant-only
	// and SELECT-only: the scheduler passes one enabled-rule tenant at a time, and
	// this query never accepts tenant_id=0/global mode.
	RecentUsageRollupByTenant(ctx context.Context, arg RecentUsageRollupByTenantParams) (RecentUsageRollupByTenantRow, error)
	ReleaseBalanceHold(ctx context.Context, claimID int64) (int64, error)
	ReleaseBindingConcurrencyLock(ctx context.Context, bindingID int64) (bool, error)
	ReleaseSlotAcquisition(ctx context.Context, arg ReleaseSlotAcquisitionParams) error
	// Tx2 槽释放原语：只有 acquired 行成功翻到指定终态后才递减账号在途数。
	// 重放同一 token 时内层 UPDATE 为 0 行，外层自然不递减，保持幂等。
	// 参数使用具名绑定；acquisition_token 由目标列推导 UUID 类型并套用统一类型覆盖。
	ReleaseSlotAndDecrementInFlight(ctx context.Context, arg ReleaseSlotAndDecrementInFlightParams) (int64, error)
	// F-OBS-001 balance hold queries for durable atomic debit.
	ReserveBalanceHold(ctx context.Context, arg ReserveBalanceHoldParams) (ReserveBalanceHoldRow, error)
	SelectExpiredReservingClaims(ctx context.Context, batchSize int32) ([]SelectExpiredReservingClaimsRow, error)
	SetProviderAccountModelRateLimit(ctx context.Context, arg SetProviderAccountModelRateLimitParams) error
	SweepOrphanedSlotAcquisitions(ctx context.Context, arg SweepOrphanedSlotAcquisitionsParams) (int64, error)
	TryAcquireBindingConcurrencyLock(ctx context.Context, bindingID int64) (bool, error)
	// Abort path: claim status reserving → aborted; usage_record/billing_event
	// still written (with zero cost) for audit completeness.
	// Tenant-scoped to prevent cross-tenant abort via stale claim id.
	UpdateClaimAbortedWithReason(ctx context.Context, arg UpdateClaimAbortedWithReasonParams) (int64, error)
	// Spec §Tx2 step 15: claim status reserving → committed.
	// codex chunk7 P1#4: tenant_id 显式 caller 提供, 防全局 id 跨租户误 commit。
	UpdateClaimCommitted(ctx context.Context, arg UpdateClaimCommittedParams) (int64, error)
	UpdatePool(ctx context.Context, arg UpdatePoolParams) (PoolGroup, error)
	UpsertBalanceHold(ctx context.Context, arg UpsertBalanceHoldParams) error
	// 写入或更新单个计费设置; updated_at 总是以数据库时间刷新。
	UpsertBillingSetting(ctx context.Context, arg UpsertBillingSettingParams) (BillingSetting, error)
	UpsertStickyBinding(ctx context.Context, arg UpsertStickyBindingParams) error
	// 区分 ReserveBalanceHold 返 0 行的两种情形:无余额行 vs 行在但
	// (balance-held)<cost。mandatory 由调用方将两者都映射为 402; opt_in 只
	// 对已有余额行不足返回 402。
	UserBalanceExists(ctx context.Context, arg UserBalanceExistsParams) (bool, error)
	// Pattern B placeholder writeback per F-POOL-001 §6 + F-OBS-001 §Tx1 step 6.
	// Pool acquire returns; we set provider_account_id + acquisition_token onto
	// the existing reserving claim row.
	WriteAcquisitionToken(ctx context.Context, arg WriteAcquisitionTokenParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
