// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hermes_tool_calls.sql

package hermestoolsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertHermesToolCall = `-- name: InsertHermesToolCall :one

INSERT INTO hermes_tool_calls (
    tenant_id, actor_user_id, admin_actor_token_id, tool_name,
    requested_args, result_status, result_summary, error_class,
    correlation_id, request_id, called_at, returned_at, dry_run
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::text,
    $5::jsonb,
    $6::text,
    $7::jsonb,
    $8::text,
    $9::text,
    $10::text,
    $11::timestamptz,
    $12::timestamptz,
    $13::boolean
)
RETURNING id, called_at
`

type InsertHermesToolCallParams struct {
	TenantID          int64              `db:"tenant_id" json:"tenant_id"`
	ActorUserID       int64              `db:"actor_user_id" json:"actor_user_id"`
	AdminActorTokenID *int64             `db:"admin_actor_token_id" json:"admin_actor_token_id"`
	ToolName          string             `db:"tool_name" json:"tool_name"`
	RequestedArgs     []byte             `db:"requested_args" json:"requested_args"`
	ResultStatus      string             `db:"result_status" json:"result_status"`
	ResultSummary     []byte             `db:"result_summary" json:"result_summary"`
	ErrorClass        *string            `db:"error_class" json:"error_class"`
	CorrelationID     *string            `db:"correlation_id" json:"correlation_id"`
	RequestID         *string            `db:"request_id" json:"request_id"`
	CalledAt          pgtype.Timestamptz `db:"called_at" json:"called_at"`
	ReturnedAt        pgtype.Timestamptz `db:"returned_at" json:"returned_at"`
	DryRun            bool               `db:"dry_run" json:"dry_run"`
}

type InsertHermesToolCallRow struct {
	ID       int64              `db:"id" json:"id"`
	CalledAt pgtype.Timestamptz `db:"called_at" json:"called_at"`
}

// Hermes WAVE H3 tool-call audit ledger queries.
//
// These mirror the append-only audit shape of hermes.sql / admin_audit.sql: a
// single INSERT per tool invocation, written inside the same transaction as the
// tool's execution + the mirrored hermes_audit_events / admin_audit_events rows,
// so the tool-call trail is atomic with the action (or denial).
//
// requested_args / result_summary are SANITIZED by the application before this
// INSERT — only system-diagnostic enums / counts / ids / fingerprints, never
// prompts / completions / raw bodies / secrets / PII.
func (q *Queries) InsertHermesToolCall(ctx context.Context, arg InsertHermesToolCallParams) (InsertHermesToolCallRow, error) {
	row := q.db.QueryRow(ctx, insertHermesToolCall,
		arg.TenantID,
		arg.ActorUserID,
		arg.AdminActorTokenID,
		arg.ToolName,
		arg.RequestedArgs,
		arg.ResultStatus,
		arg.ResultSummary,
		arg.ErrorClass,
		arg.CorrelationID,
		arg.RequestID,
		arg.CalledAt,
		arg.ReturnedAt,
		arg.DryRun,
	)
	var i InsertHermesToolCallRow
	err := row.Scan(&i.ID, &i.CalledAt)
	return i, err
}

const listHermesToolCallsByTenant = `-- name: ListHermesToolCallsByTenant :many
SELECT id, tenant_id, actor_user_id, admin_actor_token_id, tool_name,
       requested_args, result_status, result_summary, error_class,
       correlation_id, request_id, called_at, returned_at, dry_run
FROM hermes_tool_calls
WHERE tenant_id = $1::bigint
ORDER BY called_at DESC, id DESC
LIMIT $2::int
`

type ListHermesToolCallsByTenantParams struct {
	TenantID  int64 `db:"tenant_id" json:"tenant_id"`
	PageLimit int32 `db:"page_limit" json:"page_limit"`
}

func (q *Queries) ListHermesToolCallsByTenant(ctx context.Context, arg ListHermesToolCallsByTenantParams) ([]HermesToolCall, error) {
	rows, err := q.db.Query(ctx, listHermesToolCallsByTenant, arg.TenantID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HermesToolCall
	for rows.Next() {
		var i HermesToolCall
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorUserID,
			&i.AdminActorTokenID,
			&i.ToolName,
			&i.RequestedArgs,
			&i.ResultStatus,
			&i.ResultSummary,
			&i.ErrorClass,
			&i.CorrelationID,
			&i.RequestID,
			&i.CalledAt,
			&i.ReturnedAt,
			&i.DryRun,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
