// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: hermes_tool_calls.sql

package hermestoolsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertHermesToolCall = `-- name: InsertHermesToolCall :one

INSERT INTO hermes_tool_calls (
    operation_id, tenant_id, actor_source, actor_id, actor_role, tool_name,
    requested_args, result_status, result_summary, error_class,
    correlation_id, request_id, called_at, returned_at, dry_run, log_category
) VALUES (
    $1::uuid,
    $2::bigint,
    $3::text,
    $4::bigint,
    $5::text,
    $6::text,
    $7::jsonb,
    $8::text,
    $9::jsonb,
    $10::text,
    $11::text,
    $12::text,
    $13::timestamptz,
    $14::timestamptz,
    $15::boolean,
    $16::text
)
RETURNING id, called_at
`

type InsertHermesToolCallParams struct {
	OperationID   pgtype.UUID        `db:"operation_id" json:"operation_id"`
	TenantID      int64              `db:"tenant_id" json:"tenant_id"`
	ActorSource   string             `db:"actor_source" json:"actor_source"`
	ActorID       int64              `db:"actor_id" json:"actor_id"`
	ActorRole     string             `db:"actor_role" json:"actor_role"`
	ToolName      string             `db:"tool_name" json:"tool_name"`
	RequestedArgs []byte             `db:"requested_args" json:"requested_args"`
	ResultStatus  string             `db:"result_status" json:"result_status"`
	ResultSummary []byte             `db:"result_summary" json:"result_summary"`
	ErrorClass    *string            `db:"error_class" json:"error_class"`
	CorrelationID *string            `db:"correlation_id" json:"correlation_id"`
	RequestID     *string            `db:"request_id" json:"request_id"`
	CalledAt      pgtype.Timestamptz `db:"called_at" json:"called_at"`
	ReturnedAt    pgtype.Timestamptz `db:"returned_at" json:"returned_at"`
	DryRun        bool               `db:"dry_run" json:"dry_run"`
	LogCategory   string             `db:"log_category" json:"log_category"`
}

type InsertHermesToolCallRow struct {
	ID       int64              `db:"id" json:"id"`
	CalledAt pgtype.Timestamptz `db:"called_at" json:"called_at"`
}

// Hermes 工具调用日志查询。
//
// 普通改动工具在同一事务内先写工具调用和管理员操作日志，执行成功后再更新结果并共同提交。
// 含外部副作用或独立事务的工具先写恢复日志，结果明确后由恢复流程补齐两类日志。
//
// 应用层在写入前清洗 requested_args 和 result_summary，只允许系统诊断枚举、计数、标识符
// 和指纹，不持久化提示词、模型回复、原始请求体、秘密或个人信息。
func (q *Queries) InsertHermesToolCall(ctx context.Context, arg InsertHermesToolCallParams) (InsertHermesToolCallRow, error) {
	row := q.db.QueryRow(ctx, insertHermesToolCall,
		arg.OperationID,
		arg.TenantID,
		arg.ActorSource,
		arg.ActorID,
		arg.ActorRole,
		arg.ToolName,
		arg.RequestedArgs,
		arg.ResultStatus,
		arg.ResultSummary,
		arg.ErrorClass,
		arg.CorrelationID,
		arg.RequestID,
		arg.CalledAt,
		arg.ReturnedAt,
		arg.DryRun,
		arg.LogCategory,
	)
	var i InsertHermesToolCallRow
	err := row.Scan(&i.ID, &i.CalledAt)
	return i, err
}

const listHermesToolCallsByTenant = `-- name: ListHermesToolCallsByTenant :many
SELECT id, operation_id, tenant_id, actor_source, actor_id, actor_role, tool_name,
       requested_args, result_status, result_summary, error_class,
       correlation_id, request_id, called_at, returned_at, dry_run, log_category
FROM hermes_tool_calls
WHERE tenant_id = $1::bigint
ORDER BY called_at DESC, id DESC
LIMIT $2::int
`

type ListHermesToolCallsByTenantParams struct {
	TenantID  int64 `db:"tenant_id" json:"tenant_id"`
	PageLimit int32 `db:"page_limit" json:"page_limit"`
}

type ListHermesToolCallsByTenantRow struct {
	ID            int64              `db:"id" json:"id"`
	OperationID   pgtype.UUID        `db:"operation_id" json:"operation_id"`
	TenantID      int64              `db:"tenant_id" json:"tenant_id"`
	ActorSource   string             `db:"actor_source" json:"actor_source"`
	ActorID       int64              `db:"actor_id" json:"actor_id"`
	ActorRole     *string            `db:"actor_role" json:"actor_role"`
	ToolName      string             `db:"tool_name" json:"tool_name"`
	RequestedArgs []byte             `db:"requested_args" json:"requested_args"`
	ResultStatus  string             `db:"result_status" json:"result_status"`
	ResultSummary []byte             `db:"result_summary" json:"result_summary"`
	ErrorClass    *string            `db:"error_class" json:"error_class"`
	CorrelationID *string            `db:"correlation_id" json:"correlation_id"`
	RequestID     *string            `db:"request_id" json:"request_id"`
	CalledAt      pgtype.Timestamptz `db:"called_at" json:"called_at"`
	ReturnedAt    pgtype.Timestamptz `db:"returned_at" json:"returned_at"`
	DryRun        bool               `db:"dry_run" json:"dry_run"`
	LogCategory   string             `db:"log_category" json:"log_category"`
}

func (q *Queries) ListHermesToolCallsByTenant(ctx context.Context, arg ListHermesToolCallsByTenantParams) ([]ListHermesToolCallsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listHermesToolCallsByTenant, arg.TenantID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHermesToolCallsByTenantRow
	for rows.Next() {
		var i ListHermesToolCallsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.TenantID,
			&i.ActorSource,
			&i.ActorID,
			&i.ActorRole,
			&i.ToolName,
			&i.RequestedArgs,
			&i.ResultStatus,
			&i.ResultSummary,
			&i.ErrorClass,
			&i.CorrelationID,
			&i.RequestID,
			&i.CalledAt,
			&i.ReturnedAt,
			&i.DryRun,
			&i.LogCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHermesToolCallOutcome = `-- name: UpdateHermesToolCallOutcome :execrows
UPDATE hermes_tool_calls
SET result_status = $1::text,
    result_summary = $2::jsonb,
    error_class = $3::text,
    returned_at = $4::timestamptz,
    log_category = $5::text
WHERE id = $6::bigint
  AND operation_id = $7::uuid
`

type UpdateHermesToolCallOutcomeParams struct {
	ResultStatus  string             `db:"result_status" json:"result_status"`
	ResultSummary []byte             `db:"result_summary" json:"result_summary"`
	ErrorClass    *string            `db:"error_class" json:"error_class"`
	ReturnedAt    pgtype.Timestamptz `db:"returned_at" json:"returned_at"`
	LogCategory   string             `db:"log_category" json:"log_category"`
	ID            int64              `db:"id" json:"id"`
	OperationID   pgtype.UUID        `db:"operation_id" json:"operation_id"`
}

func (q *Queries) UpdateHermesToolCallOutcome(ctx context.Context, arg UpdateHermesToolCallOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateHermesToolCallOutcome,
		arg.ResultStatus,
		arg.ResultSummary,
		arg.ErrorClass,
		arg.ReturnedAt,
		arg.LogCategory,
		arg.ID,
		arg.OperationID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
