// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package hermestoolsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HermesToolCall struct {
	ID                int64              `db:"id" json:"id"`
	TenantID          int64              `db:"tenant_id" json:"tenant_id"`
	ActorUserID       int64              `db:"actor_user_id" json:"actor_user_id"`
	AdminActorTokenID *int64             `db:"admin_actor_token_id" json:"admin_actor_token_id"`
	ToolName          string             `db:"tool_name" json:"tool_name"`
	RequestedArgs     []byte             `db:"requested_args" json:"requested_args"`
	ResultStatus      string             `db:"result_status" json:"result_status"`
	ResultSummary     []byte             `db:"result_summary" json:"result_summary"`
	ErrorClass        *string            `db:"error_class" json:"error_class"`
	CorrelationID     *string            `db:"correlation_id" json:"correlation_id"`
	RequestID         *string            `db:"request_id" json:"request_id"`
	CalledAt          pgtype.Timestamptz `db:"called_at" json:"called_at"`
	ReturnedAt        pgtype.Timestamptz `db:"returned_at" json:"returned_at"`
}
