// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package hermestoolsdb

import (
	"context"
)

type Querier interface {
	// Hermes WAVE H3 tool-call audit ledger queries.
	//
	// These mirror the append-only audit shape of hermes.sql / admin_audit.sql: a
	// single INSERT per tool invocation, written inside the same transaction as the
	// tool's execution + the mirrored hermes_audit_events / admin_audit_events rows,
	// so the tool-call trail is atomic with the action (or denial).
	//
	// requested_args / result_summary are SANITIZED by the application before this
	// INSERT — only system-diagnostic enums / counts / ids / fingerprints, never
	// prompts / completions / raw bodies / secrets / PII.
	InsertHermesToolCall(ctx context.Context, arg InsertHermesToolCallParams) (InsertHermesToolCallRow, error)
	ListHermesToolCallsByTenant(ctx context.Context, arg ListHermesToolCallsByTenantParams) ([]HermesToolCall, error)
}

var _ Querier = (*Queries)(nil)
