// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package quotaadmin

import (
	"context"
)

type Querier interface {
	// 硬删 (quota_policies 无 deleted_at); 若有 quota_windows 引用, FK ON DELETE
	// RESTRICT 触发 23503 -> handler 归一 409 quota_policy_in_use。双定位
	// tenant_id+id; 缺行 -> ErrNoRows -> handler 404。
	DeleteQuotaPolicy(ctx context.Context, arg DeleteQuotaPolicyParams) (int64, error)
	// 单行读, tenant_id 与 id 双定位; 缺行 -> sqlc 返回 ErrNoRows -> handler 404。
	GetQuotaPolicyByID(ctx context.Context, arg GetQuotaPolicyByIDParams) (QuotaPolicy, error)
	// HUAKAI 配额策略管理面 (BILL-122 /admin/v1/quota-policies) sqlc 查询。
	// 与 reserve-path 读 (quota.sql) 分离: 这些查询给运营后台 CRUD 用, 故意不过滤
	// enabled/valid_until/mode, 让运营看到禁用+过期+影子策略全集; 也单独成包让
	// 生成文件按职责拆分, 不撑大 reserve-path 的 quota.sql.go。
	// 约束: 所有读写定位都显式带 tenant_id, 防跨租户误读/误改。
	// 建一条配额策略并回写全列; live unique / valid_range / >=0 CHECK 由库守。
	InsertQuotaPolicy(ctx context.Context, arg InsertQuotaPolicyParams) (QuotaPolicy, error)
	// 运营后台列表: 可选 scope_kind/scope_id/metric/enabled 过滤 + 分页。
	// 故意不过滤 valid_from/valid_until/mode, 运营须看到过期+影子+禁用全集。
	ListQuotaPoliciesForAdmin(ctx context.Context, arg ListQuotaPoliciesForAdminParams) ([]QuotaPolicy, error)
	// 整行覆盖一条策略 (含 enabled/mode 开关), 仍按 tenant_id+id 定位防越租户。
	UpdateQuotaPolicy(ctx context.Context, arg UpdateQuotaPolicyParams) (QuotaPolicy, error)
}

var _ Querier = (*Queries)(nil)
