// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quota_admin.sql

package quotaadmin

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteQuotaPolicy = `-- name: DeleteQuotaPolicy :one
DELETE FROM quota_policies
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
RETURNING id
`

type DeleteQuotaPolicyParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ID       int64 `db:"id" json:"id"`
}

// 硬删 (quota_policies 无 deleted_at); 若有 quota_windows 引用, FK ON DELETE
// RESTRICT 触发 23503 -> handler 归一 409 quota_policy_in_use。双定位
// tenant_id+id; 缺行 -> ErrNoRows -> handler 404。
func (q *Queries) DeleteQuotaPolicy(ctx context.Context, arg DeleteQuotaPolicyParams) (int64, error) {
	row := q.db.QueryRow(ctx, deleteQuotaPolicy, arg.TenantID, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getQuotaPolicyByID = `-- name: GetQuotaPolicyByID :one
SELECT quota_policies.tenant_id, quota_policies.id, quota_policies.scope_kind, quota_policies.scope_id, quota_policies.metric, quota_policies.window_kind, quota_policies.window_seconds, quota_policies.limit_value, quota_policies.burst_value, quota_policies.mode, quota_policies.priority, quota_policies.enabled, quota_policies.valid_from, quota_policies.valid_until, quota_policies.created_by_actor, quota_policies.last_modified_by_actor, quota_policies.created_at, quota_policies.updated_at, quota_policies.model_selector
FROM quota_policies
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
`

type GetQuotaPolicyByIDParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ID       int64 `db:"id" json:"id"`
}

// 单行读, tenant_id 与 id 双定位; 缺行 -> sqlc 返回 ErrNoRows -> handler 404。
func (q *Queries) GetQuotaPolicyByID(ctx context.Context, arg GetQuotaPolicyByIDParams) (QuotaPolicy, error) {
	row := q.db.QueryRow(ctx, getQuotaPolicyByID, arg.TenantID, arg.ID)
	var i QuotaPolicy
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Metric,
		&i.WindowKind,
		&i.WindowSeconds,
		&i.LimitValue,
		&i.BurstValue,
		&i.Mode,
		&i.Priority,
		&i.Enabled,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedByActor,
		&i.LastModifiedByActor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelSelector,
	)
	return i, err
}

const insertQuotaPolicy = `-- name: InsertQuotaPolicy :one

INSERT INTO quota_policies (
    tenant_id, scope_kind, scope_id, model_selector, metric, window_kind, window_seconds,
    limit_value, burst_value, mode, priority, enabled,
    valid_from, valid_until, created_by_actor, last_modified_by_actor
) VALUES (
    $1::bigint,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::integer,
    $8::numeric(20,8),
    $9::numeric(20,8),
    $10::text,
    $11::integer,
    $12::boolean,
    $13::timestamptz,
    $14::timestamptz,
    $15::text,
    $16::text
)
RETURNING tenant_id, id, scope_kind, scope_id, metric, window_kind, window_seconds, limit_value, burst_value, mode, priority, enabled, valid_from, valid_until, created_by_actor, last_modified_by_actor, created_at, updated_at, model_selector
`

type InsertQuotaPolicyParams struct {
	TenantID            int64              `db:"tenant_id" json:"tenant_id"`
	ScopeKind           string             `db:"scope_kind" json:"scope_kind"`
	ScopeID             string             `db:"scope_id" json:"scope_id"`
	ModelSelector       string             `db:"model_selector" json:"model_selector"`
	Metric              string             `db:"metric" json:"metric"`
	WindowKind          string             `db:"window_kind" json:"window_kind"`
	WindowSeconds       int32              `db:"window_seconds" json:"window_seconds"`
	LimitValue          pgtype.Numeric     `db:"limit_value" json:"limit_value"`
	BurstValue          pgtype.Numeric     `db:"burst_value" json:"burst_value"`
	Mode                string             `db:"mode" json:"mode"`
	Priority            int32              `db:"priority" json:"priority"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	ValidFrom           pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidUntil          pgtype.Timestamptz `db:"valid_until" json:"valid_until"`
	CreatedByActor      *string            `db:"created_by_actor" json:"created_by_actor"`
	LastModifiedByActor *string            `db:"last_modified_by_actor" json:"last_modified_by_actor"`
}

// HUAKAI 配额策略管理面 (BILL-122 /admin/v1/quota-policies) sqlc 查询。
// 与 reserve-path 读 (quota.sql) 分离: 这些查询给运营后台 CRUD 用, 故意不过滤
// enabled/valid_until/mode, 让运营看到禁用+过期+影子策略全集; 也单独成包让
// 生成文件按职责拆分, 不撑大 reserve-path 的 quota.sql.go。
// 约束: 所有读写定位都显式带 tenant_id, 防跨租户误读/误改。
// 建一条配额策略并回写全列; live unique / valid_range / >=0 CHECK 由库守。
func (q *Queries) InsertQuotaPolicy(ctx context.Context, arg InsertQuotaPolicyParams) (QuotaPolicy, error) {
	row := q.db.QueryRow(ctx, insertQuotaPolicy,
		arg.TenantID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.ModelSelector,
		arg.Metric,
		arg.WindowKind,
		arg.WindowSeconds,
		arg.LimitValue,
		arg.BurstValue,
		arg.Mode,
		arg.Priority,
		arg.Enabled,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.CreatedByActor,
		arg.LastModifiedByActor,
	)
	var i QuotaPolicy
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Metric,
		&i.WindowKind,
		&i.WindowSeconds,
		&i.LimitValue,
		&i.BurstValue,
		&i.Mode,
		&i.Priority,
		&i.Enabled,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedByActor,
		&i.LastModifiedByActor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelSelector,
	)
	return i, err
}

const listQuotaPoliciesForAdmin = `-- name: ListQuotaPoliciesForAdmin :many
SELECT quota_policies.tenant_id, quota_policies.id, quota_policies.scope_kind, quota_policies.scope_id, quota_policies.metric, quota_policies.window_kind, quota_policies.window_seconds, quota_policies.limit_value, quota_policies.burst_value, quota_policies.mode, quota_policies.priority, quota_policies.enabled, quota_policies.valid_from, quota_policies.valid_until, quota_policies.created_by_actor, quota_policies.last_modified_by_actor, quota_policies.created_at, quota_policies.updated_at, quota_policies.model_selector
FROM quota_policies
WHERE tenant_id = $1::bigint
  AND ($2::text IS NULL OR scope_kind = $2::text)
  AND ($3::text IS NULL OR scope_id = $3::text)
  AND ($4::text IS NULL OR model_selector = $4::text)
  AND ($5::text IS NULL OR metric = $5::text)
  AND ($6::boolean IS NULL OR enabled = $6::boolean)
ORDER BY
    CASE WHEN model_selector = '*' THEN 0 ELSE 1 END,
    priority ASC,
    id ASC
LIMIT $8::integer
OFFSET $7::integer
`

type ListQuotaPoliciesForAdminParams struct {
	TenantID      int64   `db:"tenant_id" json:"tenant_id"`
	ScopeKind     *string `db:"scope_kind" json:"scope_kind"`
	ScopeID       *string `db:"scope_id" json:"scope_id"`
	ModelSelector *string `db:"model_selector" json:"model_selector"`
	Metric        *string `db:"metric" json:"metric"`
	Enabled       *bool   `db:"enabled" json:"enabled"`
	PageOffset    int32   `db:"page_offset" json:"page_offset"`
	PageLimit     int32   `db:"page_limit" json:"page_limit"`
}

// 运营后台列表: 可选 scope_kind/scope_id/model_selector/metric/enabled 过滤 + 分页。
// 故意不过滤 valid_from/valid_until/mode, 运营须看到过期+影子+禁用全集。
func (q *Queries) ListQuotaPoliciesForAdmin(ctx context.Context, arg ListQuotaPoliciesForAdminParams) ([]QuotaPolicy, error) {
	rows, err := q.db.Query(ctx, listQuotaPoliciesForAdmin,
		arg.TenantID,
		arg.ScopeKind,
		arg.ScopeID,
		arg.ModelSelector,
		arg.Metric,
		arg.Enabled,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuotaPolicy
	for rows.Next() {
		var i QuotaPolicy
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.ScopeKind,
			&i.ScopeID,
			&i.Metric,
			&i.WindowKind,
			&i.WindowSeconds,
			&i.LimitValue,
			&i.BurstValue,
			&i.Mode,
			&i.Priority,
			&i.Enabled,
			&i.ValidFrom,
			&i.ValidUntil,
			&i.CreatedByActor,
			&i.LastModifiedByActor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ModelSelector,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuotaPolicy = `-- name: UpdateQuotaPolicy :one
UPDATE quota_policies
SET scope_kind = $1::text,
    scope_id = $2::text,
    model_selector = $3::text,
    metric = $4::text,
    window_kind = $5::text,
    window_seconds = $6::integer,
    limit_value = $7::numeric(20,8),
    burst_value = $8::numeric(20,8),
    mode = $9::text,
    priority = $10::integer,
    enabled = $11::boolean,
    valid_from = $12::timestamptz,
    valid_until = $13::timestamptz,
    last_modified_by_actor = $14::text,
    updated_at = NOW()
WHERE tenant_id = $15::bigint
  AND id = $16::bigint
RETURNING tenant_id, id, scope_kind, scope_id, metric, window_kind, window_seconds, limit_value, burst_value, mode, priority, enabled, valid_from, valid_until, created_by_actor, last_modified_by_actor, created_at, updated_at, model_selector
`

type UpdateQuotaPolicyParams struct {
	ScopeKind           string             `db:"scope_kind" json:"scope_kind"`
	ScopeID             string             `db:"scope_id" json:"scope_id"`
	ModelSelector       string             `db:"model_selector" json:"model_selector"`
	Metric              string             `db:"metric" json:"metric"`
	WindowKind          string             `db:"window_kind" json:"window_kind"`
	WindowSeconds       int32              `db:"window_seconds" json:"window_seconds"`
	LimitValue          pgtype.Numeric     `db:"limit_value" json:"limit_value"`
	BurstValue          pgtype.Numeric     `db:"burst_value" json:"burst_value"`
	Mode                string             `db:"mode" json:"mode"`
	Priority            int32              `db:"priority" json:"priority"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	ValidFrom           pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidUntil          pgtype.Timestamptz `db:"valid_until" json:"valid_until"`
	LastModifiedByActor *string            `db:"last_modified_by_actor" json:"last_modified_by_actor"`
	TenantID            int64              `db:"tenant_id" json:"tenant_id"`
	ID                  int64              `db:"id" json:"id"`
}

// 整行覆盖一条策略 (含 enabled/mode 开关), 仍按 tenant_id+id 定位防越租户。
func (q *Queries) UpdateQuotaPolicy(ctx context.Context, arg UpdateQuotaPolicyParams) (QuotaPolicy, error) {
	row := q.db.QueryRow(ctx, updateQuotaPolicy,
		arg.ScopeKind,
		arg.ScopeID,
		arg.ModelSelector,
		arg.Metric,
		arg.WindowKind,
		arg.WindowSeconds,
		arg.LimitValue,
		arg.BurstValue,
		arg.Mode,
		arg.Priority,
		arg.Enabled,
		arg.ValidFrom,
		arg.ValidUntil,
		arg.LastModifiedByActor,
		arg.TenantID,
		arg.ID,
	)
	var i QuotaPolicy
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Metric,
		&i.WindowKind,
		&i.WindowSeconds,
		&i.LimitValue,
		&i.BurstValue,
		&i.Mode,
		&i.Priority,
		&i.Enabled,
		&i.ValidFrom,
		&i.ValidUntil,
		&i.CreatedByActor,
		&i.LastModifiedByActor,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ModelSelector,
	)
	return i, err
}
