package moderation

// 本文件为 Hermes mutating 工具 moderation_keyword_enable/disable 手写的两个查询(照
// SoftDeleteModerationKeyword 的生成码范式手写,未经 sqlc generate —— 项目规则:重新生成
// 会带入无关漂移)。刻意放在生成文件 moderation.sql.go **之外**的独立文件里:既不污染那份
// `// Code generated by sqlc. DO NOT EDIT.` 文件,也不让生成文件的体量超 codebudget 软预算。
//
// 列与类型对齐 ListEnabledModerationKeywords 的 SELECT(id/tenant_id/keyword/reason_code/
// enabled bigint/bigint/text/text/boolean,created_at/updated_at timestamptz)。仅加到具体类型
// *Queries(不动 Querier 接口,避免接口 ripple)。对应源 SQL 也已同步进 sql/queries/moderation.sql。

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getModerationKeyword = `-- name: GetModerationKeyword :one
SELECT id, tenant_id, keyword, reason_code, enabled, created_at, updated_at
FROM moderation_keywords
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND deleted_at IS NULL
`

type GetModerationKeywordParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ID       int64 `db:"id" json:"id"`
}

type GetModerationKeywordRow struct {
	ID         int64              `db:"id" json:"id"`
	TenantID   int64              `db:"tenant_id" json:"tenant_id"`
	Keyword    string             `db:"keyword" json:"keyword"`
	ReasonCode string             `db:"reason_code" json:"reason_code"`
	Enabled    bool               `db:"enabled" json:"enabled"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// GetModerationKeyword 按 tenant_id + id 读取单条未软删(deleted_at IS NULL)的审核关键词,
// 供 Hermes 工具的 Resolve 复检租户归属 + 渲染预览。跨租户或已软删均返回 pgx.ErrNoRows。
func (q *Queries) GetModerationKeyword(ctx context.Context, arg GetModerationKeywordParams) (GetModerationKeywordRow, error) {
	row := q.db.QueryRow(ctx, getModerationKeyword, arg.TenantID, arg.ID)
	var i GetModerationKeywordRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Keyword,
		&i.ReasonCode,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setModerationKeywordEnabled = `-- name: SetModerationKeywordEnabled :execrows
UPDATE moderation_keywords
SET enabled = $3::boolean,
    updated_at = now()
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND deleted_at IS NULL
`

type SetModerationKeywordEnabledParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ID       int64 `db:"id" json:"id"`
	Enabled  bool  `db:"enabled" json:"enabled"`
}

// SetModerationKeywordEnabled 在传入的查询器(可由 tx 构造)上定向翻转单条未软删关键词的
// enabled 列(只改 enabled + updated_at)。租户 scope 绑死在 WHERE tenant_id;跨租户或已软删
// 命中 0 行(返回的 RowsAffected=0)。返回受影响行数。
func (q *Queries) SetModerationKeywordEnabled(ctx context.Context, arg SetModerationKeywordEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setModerationKeywordEnabled, arg.TenantID, arg.ID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
