// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: moderation_violation_write.sql

package moderation

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countModerationBlocksInWindow = `-- name: CountModerationBlocksInWindow :one
SELECT count(*)::bigint
FROM moderation_violation_events
WHERE tenant_id = $1::bigint
  AND api_key_id = $2::bigint
  AND occurred_at >= now() - make_interval(secs => $3::integer)
`

type CountModerationBlocksInWindowParams struct {
	TenantID      int64 `db:"tenant_id" json:"tenant_id"`
	APIKeyID      int64 `db:"api_key_id" json:"api_key_id"`
	WindowSeconds int32 `db:"window_seconds" json:"window_seconds"`
}

func (q *Queries) CountModerationBlocksInWindow(ctx context.Context, arg CountModerationBlocksInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countModerationBlocksInWindow, arg.TenantID, arg.APIKeyID, arg.WindowSeconds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const disableModerationAPIKey = `-- name: DisableModerationAPIKey :one
UPDATE api_keys
SET status = 'disabled',
    updated_at = now()
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND purpose = 'user'
  AND status = 'active'
  AND deleted_at IS NULL
RETURNING status_generation, updated_at
`

type DisableModerationAPIKeyParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	APIKeyID int64 `db:"api_key_id" json:"api_key_id"`
}

type DisableModerationAPIKeyRow struct {
	StatusGeneration int64              `db:"status_generation" json:"status_generation"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) DisableModerationAPIKey(ctx context.Context, arg DisableModerationAPIKeyParams) (DisableModerationAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, disableModerationAPIKey, arg.TenantID, arg.APIKeyID)
	var i DisableModerationAPIKeyRow
	err := row.Scan(&i.StatusGeneration, &i.UpdatedAt)
	return i, err
}

const finalizeModerationViolationEvent = `-- name: FinalizeModerationViolationEvent :one
UPDATE moderation_violation_events
SET violation_count = $1::bigint,
    threshold_reached = $2::boolean,
    disposition_source = $3::text,
    disposition_result = $4::text
WHERE tenant_id = $5::bigint
  AND id = $6::bigint
RETURNING id
`

type FinalizeModerationViolationEventParams struct {
	ViolationCount    int64  `db:"violation_count" json:"violation_count"`
	ThresholdReached  bool   `db:"threshold_reached" json:"threshold_reached"`
	DispositionSource string `db:"disposition_source" json:"disposition_source"`
	DispositionResult string `db:"disposition_result" json:"disposition_result"`
	TenantID          int64  `db:"tenant_id" json:"tenant_id"`
	ViolationEventID  int64  `db:"violation_event_id" json:"violation_event_id"`
}

func (q *Queries) FinalizeModerationViolationEvent(ctx context.Context, arg FinalizeModerationViolationEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, finalizeModerationViolationEvent,
		arg.ViolationCount,
		arg.ThresholdReached,
		arg.DispositionSource,
		arg.DispositionResult,
		arg.TenantID,
		arg.ViolationEventID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getModerationViolationByRequest = `-- name: GetModerationViolationByRequest :one
SELECT id, tenant_id, api_key_id, user_id, request_id,
       decision, reason_code, matched_keyword_id, matched_hash_id,
       ban_threshold_snapshot, ban_window_seconds_snapshot,
       violation_count, threshold_reached, auto_disable_enabled,
       disposition_source, disposition_result, occurred_at
FROM moderation_violation_events
WHERE tenant_id = $1::bigint
  AND api_key_id = $2::bigint
  AND request_id = $3::text
`

type GetModerationViolationByRequestParams struct {
	TenantID  int64  `db:"tenant_id" json:"tenant_id"`
	APIKeyID  int64  `db:"api_key_id" json:"api_key_id"`
	RequestID string `db:"request_id" json:"request_id"`
}

type GetModerationViolationByRequestRow struct {
	ID                       int64              `db:"id" json:"id"`
	TenantID                 int64              `db:"tenant_id" json:"tenant_id"`
	APIKeyID                 int64              `db:"api_key_id" json:"api_key_id"`
	UserID                   int64              `db:"user_id" json:"user_id"`
	RequestID                string             `db:"request_id" json:"request_id"`
	Decision                 string             `db:"decision" json:"decision"`
	ReasonCode               string             `db:"reason_code" json:"reason_code"`
	MatchedKeywordID         *int64             `db:"matched_keyword_id" json:"matched_keyword_id"`
	MatchedHashID            *int64             `db:"matched_hash_id" json:"matched_hash_id"`
	BanThresholdSnapshot     int32              `db:"ban_threshold_snapshot" json:"ban_threshold_snapshot"`
	BanWindowSecondsSnapshot int32              `db:"ban_window_seconds_snapshot" json:"ban_window_seconds_snapshot"`
	ViolationCount           int64              `db:"violation_count" json:"violation_count"`
	ThresholdReached         bool               `db:"threshold_reached" json:"threshold_reached"`
	AutoDisableEnabled       bool               `db:"auto_disable_enabled" json:"auto_disable_enabled"`
	DispositionSource        string             `db:"disposition_source" json:"disposition_source"`
	DispositionResult        string             `db:"disposition_result" json:"disposition_result"`
	OccurredAt               pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

func (q *Queries) GetModerationViolationByRequest(ctx context.Context, arg GetModerationViolationByRequestParams) (GetModerationViolationByRequestRow, error) {
	row := q.db.QueryRow(ctx, getModerationViolationByRequest, arg.TenantID, arg.APIKeyID, arg.RequestID)
	var i GetModerationViolationByRequestRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.APIKeyID,
		&i.UserID,
		&i.RequestID,
		&i.Decision,
		&i.ReasonCode,
		&i.MatchedKeywordID,
		&i.MatchedHashID,
		&i.BanThresholdSnapshot,
		&i.BanWindowSecondsSnapshot,
		&i.ViolationCount,
		&i.ThresholdReached,
		&i.AutoDisableEnabled,
		&i.DispositionSource,
		&i.DispositionResult,
		&i.OccurredAt,
	)
	return i, err
}

const insertModerationViolationEvent = `-- name: InsertModerationViolationEvent :one
INSERT INTO moderation_violation_events (
    tenant_id, api_key_id, user_id, request_id,
    decision, reason_code, matched_keyword_id, matched_hash_id,
    ban_threshold_snapshot, ban_window_seconds_snapshot,
    violation_count, threshold_reached, auto_disable_enabled,
    disposition_source, disposition_result
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::text,
    $5::text,
    $6::text,
    $7::bigint,
    $8::bigint,
    $9::integer,
    $10::integer,
    0,
    false,
    $11::boolean,
    'none',
    'unchanged'
)
ON CONFLICT (tenant_id, api_key_id, request_id) DO NOTHING
RETURNING id
`

type InsertModerationViolationEventParams struct {
	TenantID                 int64  `db:"tenant_id" json:"tenant_id"`
	APIKeyID                 int64  `db:"api_key_id" json:"api_key_id"`
	UserID                   int64  `db:"user_id" json:"user_id"`
	RequestID                string `db:"request_id" json:"request_id"`
	Decision                 string `db:"decision" json:"decision"`
	ReasonCode               string `db:"reason_code" json:"reason_code"`
	MatchedKeywordID         *int64 `db:"matched_keyword_id" json:"matched_keyword_id"`
	MatchedHashID            *int64 `db:"matched_hash_id" json:"matched_hash_id"`
	BanThresholdSnapshot     int32  `db:"ban_threshold_snapshot" json:"ban_threshold_snapshot"`
	BanWindowSecondsSnapshot int32  `db:"ban_window_seconds_snapshot" json:"ban_window_seconds_snapshot"`
	AutoDisableEnabled       bool   `db:"auto_disable_enabled" json:"auto_disable_enabled"`
}

func (q *Queries) InsertModerationViolationEvent(ctx context.Context, arg InsertModerationViolationEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertModerationViolationEvent,
		arg.TenantID,
		arg.APIKeyID,
		arg.UserID,
		arg.RequestID,
		arg.Decision,
		arg.ReasonCode,
		arg.MatchedKeywordID,
		arg.MatchedHashID,
		arg.BanThresholdSnapshot,
		arg.BanWindowSecondsSnapshot,
		arg.AutoDisableEnabled,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const lockModerationAPIKey = `-- name: LockModerationAPIKey :one

SELECT id, tenant_id, user_id, status, status_generation
FROM api_keys
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND purpose = 'user'
  AND deleted_at IS NULL
FOR UPDATE
`

type LockModerationAPIKeyParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	APIKeyID int64 `db:"api_key_id" json:"api_key_id"`
}

type LockModerationAPIKeyRow struct {
	ID               int64  `db:"id" json:"id"`
	TenantID         int64  `db:"tenant_id" json:"tenant_id"`
	UserID           int64  `db:"user_id" json:"user_id"`
	Status           string `db:"status" json:"status"`
	StatusGeneration int64  `db:"status_generation" json:"status_generation"`
}

// 内容审核永久违规事实与自动处置写入。
// 永久表不保存正文、摘录或载荷摘要。
func (q *Queries) LockModerationAPIKey(ctx context.Context, arg LockModerationAPIKeyParams) (LockModerationAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, lockModerationAPIKey, arg.TenantID, arg.APIKeyID)
	var i LockModerationAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.StatusGeneration,
	)
	return i, err
}

const upsertModerationKeyState = `-- name: UpsertModerationKeyState :exec
INSERT INTO moderation_key_states (
    tenant_id, api_key_id, state, source, trigger_event_id,
    reason_code, actor_id, actor_role, disable_generation, updated_at
) VALUES (
    $1::bigint,
    $2::bigint,
    'disabled',
    $3::text,
    $4::bigint,
    $5::text,
    $6::text,
    $7::text,
    $8::bigint,
    now()
)
ON CONFLICT (tenant_id, api_key_id) DO UPDATE
SET state = 'disabled',
    source = EXCLUDED.source,
    trigger_event_id = EXCLUDED.trigger_event_id,
    reason_code = EXCLUDED.reason_code,
    actor_id = EXCLUDED.actor_id,
    actor_role = EXCLUDED.actor_role,
    disable_generation = EXCLUDED.disable_generation,
    updated_at = now()
`

type UpsertModerationKeyStateParams struct {
	TenantID          int64  `db:"tenant_id" json:"tenant_id"`
	APIKeyID          int64  `db:"api_key_id" json:"api_key_id"`
	Source            string `db:"source" json:"source"`
	TriggerEventID    int64  `db:"trigger_event_id" json:"trigger_event_id"`
	ReasonCode        string `db:"reason_code" json:"reason_code"`
	ActorID           string `db:"actor_id" json:"actor_id"`
	ActorRole         string `db:"actor_role" json:"actor_role"`
	DisableGeneration int64  `db:"disable_generation" json:"disable_generation"`
}

func (q *Queries) UpsertModerationKeyState(ctx context.Context, arg UpsertModerationKeyStateParams) error {
	_, err := q.db.Exec(ctx, upsertModerationKeyState,
		arg.TenantID,
		arg.APIKeyID,
		arg.Source,
		arg.TriggerEventID,
		arg.ReasonCode,
		arg.ActorID,
		arg.ActorRole,
		arg.DisableGeneration,
	)
	return err
}
