// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: moderation_config.sql

package moderation

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getModerationConfig = `-- name: GetModerationConfig :one

SELECT tenant_id, enabled, fail_closed, sample_rate_pct, ban_threshold,
       ban_window_seconds, auto_disable_key_on_ban,
       violation_fee_usd, updated_by, updated_at
FROM moderation_config
WHERE tenant_id = $1::bigint
`

type GetModerationConfigRow struct {
	TenantID            int64              `db:"tenant_id" json:"tenant_id"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	FailClosed          bool               `db:"fail_closed" json:"fail_closed"`
	SampleRatePct       int32              `db:"sample_rate_pct" json:"sample_rate_pct"`
	BanThreshold        int32              `db:"ban_threshold" json:"ban_threshold"`
	BanWindowSeconds    int32              `db:"ban_window_seconds" json:"ban_window_seconds"`
	AutoDisableKeyOnBan bool               `db:"auto_disable_key_on_ban" json:"auto_disable_key_on_ban"`
	ViolationFeeUsd     decimal.Decimal    `db:"violation_fee_usd" json:"violation_fee_usd"`
	UpdatedBy           *string            `db:"updated_by" json:"updated_by"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// 内容审核租户配置查询。
func (q *Queries) GetModerationConfig(ctx context.Context, tenantID int64) (GetModerationConfigRow, error) {
	row := q.db.QueryRow(ctx, getModerationConfig, tenantID)
	var i GetModerationConfigRow
	err := row.Scan(
		&i.TenantID,
		&i.Enabled,
		&i.FailClosed,
		&i.SampleRatePct,
		&i.BanThreshold,
		&i.BanWindowSeconds,
		&i.AutoDisableKeyOnBan,
		&i.ViolationFeeUsd,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertModerationConfig = `-- name: UpsertModerationConfig :one
INSERT INTO moderation_config (
    tenant_id, enabled, fail_closed, sample_rate_pct,
    ban_threshold, ban_window_seconds, auto_disable_key_on_ban,
    violation_fee_usd, updated_by
) VALUES (
    $1::bigint,
    $2::boolean,
    $3::boolean,
    $4::integer,
    $5::integer,
    $6::integer,
    $7::boolean,
    $8::numeric,
    $9::text
)
ON CONFLICT (tenant_id) DO UPDATE
SET enabled = EXCLUDED.enabled,
    fail_closed = EXCLUDED.fail_closed,
    sample_rate_pct = EXCLUDED.sample_rate_pct,
    ban_threshold = EXCLUDED.ban_threshold,
    ban_window_seconds = EXCLUDED.ban_window_seconds,
    auto_disable_key_on_ban = EXCLUDED.auto_disable_key_on_ban,
    violation_fee_usd = EXCLUDED.violation_fee_usd,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING tenant_id, enabled, fail_closed, sample_rate_pct, ban_threshold,
          ban_window_seconds, auto_disable_key_on_ban,
          violation_fee_usd, updated_by, updated_at
`

type UpsertModerationConfigParams struct {
	TenantID            int64          `db:"tenant_id" json:"tenant_id"`
	Enabled             bool           `db:"enabled" json:"enabled"`
	FailClosed          bool           `db:"fail_closed" json:"fail_closed"`
	SampleRatePct       int32          `db:"sample_rate_pct" json:"sample_rate_pct"`
	BanThreshold        int32          `db:"ban_threshold" json:"ban_threshold"`
	BanWindowSeconds    int32          `db:"ban_window_seconds" json:"ban_window_seconds"`
	AutoDisableKeyOnBan bool           `db:"auto_disable_key_on_ban" json:"auto_disable_key_on_ban"`
	ViolationFeeUsd     pgtype.Numeric `db:"violation_fee_usd" json:"violation_fee_usd"`
	UpdatedBy           *string        `db:"updated_by" json:"updated_by"`
}

type UpsertModerationConfigRow struct {
	TenantID            int64              `db:"tenant_id" json:"tenant_id"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	FailClosed          bool               `db:"fail_closed" json:"fail_closed"`
	SampleRatePct       int32              `db:"sample_rate_pct" json:"sample_rate_pct"`
	BanThreshold        int32              `db:"ban_threshold" json:"ban_threshold"`
	BanWindowSeconds    int32              `db:"ban_window_seconds" json:"ban_window_seconds"`
	AutoDisableKeyOnBan bool               `db:"auto_disable_key_on_ban" json:"auto_disable_key_on_ban"`
	ViolationFeeUsd     decimal.Decimal    `db:"violation_fee_usd" json:"violation_fee_usd"`
	UpdatedBy           *string            `db:"updated_by" json:"updated_by"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertModerationConfig(ctx context.Context, arg UpsertModerationConfigParams) (UpsertModerationConfigRow, error) {
	row := q.db.QueryRow(ctx, upsertModerationConfig,
		arg.TenantID,
		arg.Enabled,
		arg.FailClosed,
		arg.SampleRatePct,
		arg.BanThreshold,
		arg.BanWindowSeconds,
		arg.AutoDisableKeyOnBan,
		arg.ViolationFeeUsd,
		arg.UpdatedBy,
	)
	var i UpsertModerationConfigRow
	err := row.Scan(
		&i.TenantID,
		&i.Enabled,
		&i.FailClosed,
		&i.SampleRatePct,
		&i.BanThreshold,
		&i.BanWindowSeconds,
		&i.AutoDisableKeyOnBan,
		&i.ViolationFeeUsd,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
