// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: moderation_key_operations.sql

package moderation

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireModerationKeyOperationLock = `-- name: AcquireModerationKeyOperationLock :exec

SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// 人工禁用与解封的永久幂等事实。
func (q *Queries) AcquireModerationKeyOperationLock(ctx context.Context, lockKey string) error {
	_, err := q.db.Exec(ctx, acquireModerationKeyOperationLock, lockKey)
	return err
}

const getModerationKeyOperation = `-- name: GetModerationKeyOperation :one
SELECT id, tenant_id, api_key_id, idempotency_key, request_fingerprint,
       action, violation_event_id, actor_id, actor_role,
       result_status, result_log_id, result_generation,
       result_updated_at, created_at
FROM moderation_key_operations
WHERE tenant_id = $1::bigint
  AND idempotency_key = $2::text
`

type GetModerationKeyOperationParams struct {
	TenantID       int64  `db:"tenant_id" json:"tenant_id"`
	IdempotencyKey string `db:"idempotency_key" json:"idempotency_key"`
}

func (q *Queries) GetModerationKeyOperation(ctx context.Context, arg GetModerationKeyOperationParams) (ModerationKeyOperation, error) {
	row := q.db.QueryRow(ctx, getModerationKeyOperation, arg.TenantID, arg.IdempotencyKey)
	var i ModerationKeyOperation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.APIKeyID,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.Action,
		&i.ViolationEventID,
		&i.ActorID,
		&i.ActorRole,
		&i.ResultStatus,
		&i.ResultLogID,
		&i.ResultGeneration,
		&i.ResultUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertModerationKeyOperation = `-- name: InsertModerationKeyOperation :one
INSERT INTO moderation_key_operations (
    tenant_id, api_key_id, idempotency_key, request_fingerprint,
    action, violation_event_id, actor_id, actor_role,
    result_status, result_log_id, result_generation, result_updated_at
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::text,
    $4::text,
    $5::text,
    $6::bigint,
    $7::text,
    $8::text,
    $9::text,
    $10::bigint,
    $11::bigint,
    $12::timestamptz
)
RETURNING id
`

type InsertModerationKeyOperationParams struct {
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	APIKeyID           int64              `db:"api_key_id" json:"api_key_id"`
	IdempotencyKey     string             `db:"idempotency_key" json:"idempotency_key"`
	RequestFingerprint string             `db:"request_fingerprint" json:"request_fingerprint"`
	Action             string             `db:"action" json:"action"`
	ViolationEventID   *int64             `db:"violation_event_id" json:"violation_event_id"`
	ActorID            string             `db:"actor_id" json:"actor_id"`
	ActorRole          string             `db:"actor_role" json:"actor_role"`
	ResultStatus       string             `db:"result_status" json:"result_status"`
	ResultLogID        int64              `db:"result_log_id" json:"result_log_id"`
	ResultGeneration   int64              `db:"result_generation" json:"result_generation"`
	ResultUpdatedAt    pgtype.Timestamptz `db:"result_updated_at" json:"result_updated_at"`
}

func (q *Queries) InsertModerationKeyOperation(ctx context.Context, arg InsertModerationKeyOperationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertModerationKeyOperation,
		arg.TenantID,
		arg.APIKeyID,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.Action,
		arg.ViolationEventID,
		arg.ActorID,
		arg.ActorRole,
		arg.ResultStatus,
		arg.ResultLogID,
		arg.ResultGeneration,
		arg.ResultUpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
