// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package moderation

import (
	"context"
)

type Querier interface {
	CountModerationBlocksInWindow(ctx context.Context, arg CountModerationBlocksInWindowParams) (int64, error)
	CreateModerationKeyword(ctx context.Context, arg CreateModerationKeywordParams) (CreateModerationKeywordRow, error)
	DisableModerationAPIKey(ctx context.Context, arg DisableModerationAPIKeyParams) (int64, error)
	FindEnabledModerationHash(ctx context.Context, arg FindEnabledModerationHashParams) (FindEnabledModerationHashRow, error)
	GetModerationConfig(ctx context.Context, tenantID int64) (ModerationConfig, error)
	InsertModerationLog(ctx context.Context, arg InsertModerationLogParams) (int64, error)
	// Content moderation sqlc queries.
	// moderation_log writes metadata and payload_hash only; raw request
	// bodies, plaintext credentials, and key hashes never appear in this file.
	ListEnabledModerationKeywords(ctx context.Context, tenantID int64) ([]ListEnabledModerationKeywordsRow, error)
	ListModerationKeywords(ctx context.Context, arg ListModerationKeywordsParams) ([]ListModerationKeywordsRow, error)
	SoftDeleteModerationKeyword(ctx context.Context, arg SoftDeleteModerationKeywordParams) (int64, error)
	UpsertModerationConfig(ctx context.Context, arg UpsertModerationConfigParams) (ModerationConfig, error)
}

var _ Querier = (*Queries)(nil)
