// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package moderation

import (
	"context"
)

type Querier interface {
	BulkCreateModerationHashes(ctx context.Context, arg BulkCreateModerationHashesParams) ([]BulkCreateModerationHashesRow, error)
	BulkCreateModerationKeywords(ctx context.Context, arg BulkCreateModerationKeywordsParams) ([]BulkCreateModerationKeywordsRow, error)
	CountModerationBlocksInWindow(ctx context.Context, arg CountModerationBlocksInWindowParams) (int64, error)
	CreateModerationHash(ctx context.Context, arg CreateModerationHashParams) (CreateModerationHashRow, error)
	CreateModerationKeyword(ctx context.Context, arg CreateModerationKeywordParams) (CreateModerationKeywordRow, error)
	DisableModerationAPIKey(ctx context.Context, arg DisableModerationAPIKeyParams) (int64, error)
	EnableModerationAPIKey(ctx context.Context, arg EnableModerationAPIKeyParams) (EnableModerationAPIKeyRow, error)
	FindEnabledModerationHash(ctx context.Context, arg FindEnabledModerationHashParams) (FindEnabledModerationHashRow, error)
	GetModerationConfig(ctx context.Context, tenantID int64) (ModerationConfig, error)
	InsertModerationLog(ctx context.Context, arg InsertModerationLogParams) (int64, error)
	InsertModerationViolationEvent(ctx context.Context, arg InsertModerationViolationEventParams) (int64, error)
	ListBannedKeys(ctx context.Context, arg ListBannedKeysParams) ([]ListBannedKeysRow, error)
	// Content moderation sqlc queries.
	// moderation_log writes metadata and payload_hash only; raw request
	// bodies, plaintext credentials, and key hashes never appear in this file.
	ListEnabledModerationKeywords(ctx context.Context, tenantID int64) ([]ListEnabledModerationKeywordsRow, error)
	ListModerationHashes(ctx context.Context, arg ListModerationHashesParams) ([]ListModerationHashesRow, error)
	ListModerationKeywords(ctx context.Context, arg ListModerationKeywordsParams) ([]ListModerationKeywordsRow, error)
	ListModerationLog(ctx context.Context, arg ListModerationLogParams) ([]ModerationLog, error)
	SoftDeleteModerationHash(ctx context.Context, arg SoftDeleteModerationHashParams) (int64, error)
	SoftDeleteModerationKeyword(ctx context.Context, arg SoftDeleteModerationKeywordParams) (int64, error)
	UpsertModerationConfig(ctx context.Context, arg UpsertModerationConfigParams) (ModerationConfig, error)
}

var _ Querier = (*Queries)(nil)
