// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: userkey_controls.sql

package userkeycontrols

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAPIKeyGroup = `-- name: GetAPIKeyGroup :one
SELECT
    ak.id AS api_key_id,
    g.id AS key_group_id,
    g.name AS group_name,
    g.description AS group_description,
    g.enabled AS group_enabled
FROM api_keys ak
LEFT JOIN api_key_groups g
  ON g.tenant_id = ak.tenant_id
 AND g.id = ak.key_group_id
 AND g.deleted_at IS NULL
WHERE ak.id = $1::bigint
  AND ak.tenant_id = $2::bigint
  AND ak.user_id = $3::bigint
  AND ak.deleted_at IS NULL
`

type GetAPIKeyGroupParams struct {
	APIKeyID int64 `db:"api_key_id" json:"api_key_id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

type GetAPIKeyGroupRow struct {
	APIKeyID         int64   `db:"api_key_id" json:"api_key_id"`
	KeyGroupID       *int64  `db:"key_group_id" json:"key_group_id"`
	GroupName        *string `db:"group_name" json:"group_name"`
	GroupDescription *string `db:"group_description" json:"group_description"`
	GroupEnabled     *bool   `db:"group_enabled" json:"group_enabled"`
}

func (q *Queries) GetAPIKeyGroup(ctx context.Context, arg GetAPIKeyGroupParams) (GetAPIKeyGroupRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyGroup, arg.APIKeyID, arg.TenantID, arg.UserID)
	var i GetAPIKeyGroupRow
	err := row.Scan(
		&i.APIKeyID,
		&i.KeyGroupID,
		&i.GroupName,
		&i.GroupDescription,
		&i.GroupEnabled,
	)
	return i, err
}

const getAPIKeyQuotaPolicy = `-- name: GetAPIKeyQuotaPolicy :one
SELECT
    ak.id AS api_key_id,
    qp.tenant_id,
    qp.id,
    qp.scope_kind,
    qp.scope_id,
    qp.metric,
    qp.window_kind,
    qp.window_seconds,
    qp.limit_value,
    qp.mode,
    qp.priority,
    qp.enabled,
    qp.valid_from,
    qp.valid_until
FROM api_keys ak
JOIN quota_policies qp
  ON qp.tenant_id = ak.tenant_id
 AND qp.id = ak.quota_policy_id
WHERE ak.id = $1::bigint
  AND ak.tenant_id = $2::bigint
  AND ak.user_id = $3::bigint
  AND ak.deleted_at IS NULL
  AND qp.scope_kind = 'api_key'
  AND qp.scope_id = ak.id::text
  AND qp.metric = 'cost_usd'
  AND qp.enabled = true
  AND qp.valid_until IS NULL
`

type GetAPIKeyQuotaPolicyParams struct {
	APIKeyID int64 `db:"api_key_id" json:"api_key_id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

type GetAPIKeyQuotaPolicyRow struct {
	APIKeyID      int64              `db:"api_key_id" json:"api_key_id"`
	TenantID      int64              `db:"tenant_id" json:"tenant_id"`
	ID            int64              `db:"id" json:"id"`
	ScopeKind     string             `db:"scope_kind" json:"scope_kind"`
	ScopeID       string             `db:"scope_id" json:"scope_id"`
	Metric        string             `db:"metric" json:"metric"`
	WindowKind    string             `db:"window_kind" json:"window_kind"`
	WindowSeconds int32              `db:"window_seconds" json:"window_seconds"`
	LimitValue    pgtype.Numeric     `db:"limit_value" json:"limit_value"`
	Mode          string             `db:"mode" json:"mode"`
	Priority      int32              `db:"priority" json:"priority"`
	Enabled       bool               `db:"enabled" json:"enabled"`
	ValidFrom     pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidUntil    pgtype.Timestamptz `db:"valid_until" json:"valid_until"`
}

func (q *Queries) GetAPIKeyQuotaPolicy(ctx context.Context, arg GetAPIKeyQuotaPolicyParams) (GetAPIKeyQuotaPolicyRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyQuotaPolicy, arg.APIKeyID, arg.TenantID, arg.UserID)
	var i GetAPIKeyQuotaPolicyRow
	err := row.Scan(
		&i.APIKeyID,
		&i.TenantID,
		&i.ID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Metric,
		&i.WindowKind,
		&i.WindowSeconds,
		&i.LimitValue,
		&i.Mode,
		&i.Priority,
		&i.Enabled,
		&i.ValidFrom,
		&i.ValidUntil,
	)
	return i, err
}

const setAPIKeyGroupID = `-- name: SetAPIKeyGroupID :execrows
UPDATE api_keys ak
SET key_group_id = $1::bigint,
    updated_at = NOW()
WHERE ak.id = $2::bigint
  AND ak.tenant_id = $3::bigint
  AND ak.user_id = $4::bigint
  AND ak.deleted_at IS NULL
`

type SetAPIKeyGroupIDParams struct {
	KeyGroupID *int64 `db:"key_group_id" json:"key_group_id"`
	APIKeyID   int64  `db:"api_key_id" json:"api_key_id"`
	TenantID   int64  `db:"tenant_id" json:"tenant_id"`
	UserID     int64  `db:"user_id" json:"user_id"`
}

func (q *Queries) SetAPIKeyGroupID(ctx context.Context, arg SetAPIKeyGroupIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAPIKeyGroupID,
		arg.KeyGroupID,
		arg.APIKeyID,
		arg.TenantID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAPIKeyQuotaPolicyID = `-- name: SetAPIKeyQuotaPolicyID :execrows
UPDATE api_keys ak
SET quota_policy_id = $1::bigint,
    updated_at = NOW()
WHERE ak.id = $2::bigint
  AND ak.tenant_id = $3::bigint
  AND ak.user_id = $4::bigint
  AND ak.deleted_at IS NULL
`

type SetAPIKeyQuotaPolicyIDParams struct {
	QuotaPolicyID int64 `db:"quota_policy_id" json:"quota_policy_id"`
	APIKeyID      int64 `db:"api_key_id" json:"api_key_id"`
	TenantID      int64 `db:"tenant_id" json:"tenant_id"`
	UserID        int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) SetAPIKeyQuotaPolicyID(ctx context.Context, arg SetAPIKeyQuotaPolicyIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAPIKeyQuotaPolicyID,
		arg.QuotaPolicyID,
		arg.APIKeyID,
		arg.TenantID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAPIKeyQuotaPolicy = `-- name: UpsertAPIKeyQuotaPolicy :one

INSERT INTO quota_policies (
    tenant_id,
    scope_kind,
    scope_id,
    metric,
    window_kind,
    window_seconds,
    limit_value,
    mode,
    priority,
    enabled,
    valid_from,
    valid_until,
    created_by_actor,
    last_modified_by_actor
)
SELECT
    $1::bigint,
    'api_key',
    $2::text,
    'cost_usd',
    $3::text,
    $4::integer,
    $5::numeric(20,8),
    $6::text,
    200,
    true,
    $7::timestamptz,
    NULL,
    $8::text,
    $8::text
WHERE EXISTS (
    SELECT 1
    FROM api_keys ak
    JOIN tenants t
      ON t.id = ak.tenant_id
     AND t.deleted_at IS NULL
     AND t.status = 'active'
    JOIN users u
      ON u.id = ak.user_id
     AND u.tenant_id = ak.tenant_id
     AND u.deleted_at IS NULL
     AND u.status = 'active'
    WHERE ak.id = $9::bigint
      AND ak.tenant_id = $1::bigint
      AND ak.user_id = $10::bigint
      AND ak.deleted_at IS NULL
)
ON CONFLICT (
    tenant_id,
    scope_kind,
    scope_id,
    metric,
    window_kind,
    window_seconds,
    priority
)
WHERE enabled = true AND valid_until IS NULL
DO UPDATE SET
    limit_value = EXCLUDED.limit_value,
    mode = EXCLUDED.mode,
    valid_from = EXCLUDED.valid_from,
    last_modified_by_actor = EXCLUDED.last_modified_by_actor,
    updated_at = NOW()
RETURNING
    $9::bigint AS api_key_id,
    tenant_id,
    id,
    scope_kind,
    scope_id,
    metric,
    window_kind,
    window_seconds,
    limit_value,
    mode,
    priority,
    enabled,
    valid_from,
    valid_until
`

type UpsertAPIKeyQuotaPolicyParams struct {
	TenantID      int64              `db:"tenant_id" json:"tenant_id"`
	ScopeID       string             `db:"scope_id" json:"scope_id"`
	WindowKind    string             `db:"window_kind" json:"window_kind"`
	WindowSeconds int32              `db:"window_seconds" json:"window_seconds"`
	LimitValue    pgtype.Numeric     `db:"limit_value" json:"limit_value"`
	Mode          string             `db:"mode" json:"mode"`
	ValidFrom     pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	Actor         string             `db:"actor" json:"actor"`
	APIKeyID      int64              `db:"api_key_id" json:"api_key_id"`
	UserID        int64              `db:"user_id" json:"user_id"`
}

type UpsertAPIKeyQuotaPolicyRow struct {
	APIKeyID      int64              `db:"api_key_id" json:"api_key_id"`
	TenantID      int64              `db:"tenant_id" json:"tenant_id"`
	ID            int64              `db:"id" json:"id"`
	ScopeKind     string             `db:"scope_kind" json:"scope_kind"`
	ScopeID       string             `db:"scope_id" json:"scope_id"`
	Metric        string             `db:"metric" json:"metric"`
	WindowKind    string             `db:"window_kind" json:"window_kind"`
	WindowSeconds int32              `db:"window_seconds" json:"window_seconds"`
	LimitValue    pgtype.Numeric     `db:"limit_value" json:"limit_value"`
	Mode          string             `db:"mode" json:"mode"`
	Priority      int32              `db:"priority" json:"priority"`
	Enabled       bool               `db:"enabled" json:"enabled"`
	ValidFrom     pgtype.Timestamptz `db:"valid_from" json:"valid_from"`
	ValidUntil    pgtype.Timestamptz `db:"valid_until" json:"valid_until"`
}

// User-owned API key control queries.
// CMB-5: this file must not select bearer credential material.
// The live uniqueness surface is a partial unique index, so the executable
// clause names the same indexed columns and predicate directly.
func (q *Queries) UpsertAPIKeyQuotaPolicy(ctx context.Context, arg UpsertAPIKeyQuotaPolicyParams) (UpsertAPIKeyQuotaPolicyRow, error) {
	row := q.db.QueryRow(ctx, upsertAPIKeyQuotaPolicy,
		arg.TenantID,
		arg.ScopeID,
		arg.WindowKind,
		arg.WindowSeconds,
		arg.LimitValue,
		arg.Mode,
		arg.ValidFrom,
		arg.Actor,
		arg.APIKeyID,
		arg.UserID,
	)
	var i UpsertAPIKeyQuotaPolicyRow
	err := row.Scan(
		&i.APIKeyID,
		&i.TenantID,
		&i.ID,
		&i.ScopeKind,
		&i.ScopeID,
		&i.Metric,
		&i.WindowKind,
		&i.WindowSeconds,
		&i.LimitValue,
		&i.Mode,
		&i.Priority,
		&i.Enabled,
		&i.ValidFrom,
		&i.ValidUntil,
	)
	return i, err
}

const validateGroupBelongsToTenant = `-- name: ValidateGroupBelongsToTenant :one
SELECT
    id,
    name,
    description,
    enabled
FROM api_key_groups
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND deleted_at IS NULL
  AND enabled = true
`

type ValidateGroupBelongsToTenantParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	GroupID  int64 `db:"group_id" json:"group_id"`
}

type ValidateGroupBelongsToTenantRow struct {
	ID          int64  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	Enabled     bool   `db:"enabled" json:"enabled"`
}

func (q *Queries) ValidateGroupBelongsToTenant(ctx context.Context, arg ValidateGroupBelongsToTenantParams) (ValidateGroupBelongsToTenantRow, error) {
	row := q.db.QueryRow(ctx, validateGroupBelongsToTenant, arg.TenantID, arg.GroupID)
	var i ValidateGroupBelongsToTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Enabled,
	)
	return i, err
}
