// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package requesttracedb

import (
	"context"
)

type Querier interface {
	// 按网关请求标识拼装调用链路时间线的只读查询(FE-GAP-002 第五切)。
	// 权威关联键是 billing_ledger_claims.logical_request_id(网关签发);用量、账本事件、健康/路由/限流/刷新
	// 审计事件与信任链收据按该标识 join。每条查询都带租户谓词(tenant_id <= 0 表示部署者跨租户查询),
	// 任一表无对应行只让对应段为空,由投影层打降级标记,不让整个查询失败。
	// 请求头信息:一逻辑请求一行(失败切换复用同一行并递增 attempt_seq)。HUAKAI 有两把请求标识:
	// 账本 claim 的 logical_request_id(客户端幂等键或网关生成),以及响应头 / 收据 / 审计使用的网关
	// HTTP 请求标识(写在 billing_events.audit_request_id)。这里同时按两把键找到 claim,并回传该 claim
	// 关联的全部 HTTP 标识,供后续按审计与收据表 join。同一标识若存在多行(不同指纹的幂等冲突),取最新
	// reserved_at 的一行。user_id <= 0 表示不按用户收敛(管理面);> 0 表示最终用户只看自己的请求。
	GetRequestTraceClaim(ctx context.Context, arg GetRequestTraceClaimParams) (GetRequestTraceClaimRow, error)
	// 面向用户的签名费用收据(与 /v1/receipts 同源):按网关 HTTP 请求标识与租户取最新一份,只回传摘要。
	GetRequestTraceCostReceipt(ctx context.Context, arg GetRequestTraceCostReceiptParams) (GetRequestTraceCostReceiptRow, error)
	// 信任链收据摘要:账本条目标识、签名公钥指纹、模型链;hop_chain 含上游跳点,由投影层按角色决定是否回传。
	// 信任链按网关 HTTP 请求标识落账。租户未知(tenant_id 为空)的历史条目只在 allow_null_tenant 为真
	//(部署者档位,且调用方已用 claim 锁定租户)时匹配,租户管理员与最终用户只读明确归属本租户的条目。
	GetRequestTraceReceipt(ctx context.Context, arg GetRequestTraceReceiptParams) (GetRequestTraceReceiptRow, error)
	// 与该请求相关的账号级审计事件:健康状态转换、路由审计、限流/过载、凭据刷新。这些表写的是网关 HTTP
	// 请求标识,调用方传入该 claim 关联的全部标识(逻辑标识 + HTTP 标识)。统一成
	// (来源, 事件类型, 原因, 账号代号, 时刻) 的时间线子记录;payload 不回传(可能含上游原文)。
	ListRequestTraceAuditEvents(ctx context.Context, arg ListRequestTraceAuditEventsParams) ([]ListRequestTraceAuditEventsRow, error)
	// 账本事件(永久保留):每次尝试的提交 / 中止与对账追加,构成用量明细过期后仍可用的时间线骨架。
	ListRequestTraceBillingEvents(ctx context.Context, arg ListRequestTraceBillingEventsParams) ([]ListRequestTraceBillingEventsRow, error)
	// 已结算的上游尝试:每个 (claim, attempt_seq) 一行,含账号代号、渠道、厂商、结束分类、用量与费用分项、
	// 时间戳与选号解释。已拿到账号后中止的尝试也会落一行(结束分类 unknown_termination、选号解释为空);
	// 只有拿到账号之前就中止的尝试不在此表(由账本事件补位,账号未知)。
	ListRequestTraceUsageRecords(ctx context.Context, arg ListRequestTraceUsageRecordsParams) ([]ListRequestTraceUsageRecordsRow, error)
}

var _ Querier = (*Queries)(nil)
