// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package audit

import (
	"context"
)

type Querier interface {
	CountAuditLedgerEntries(ctx context.Context) (int64, error)
	CreateCostDispute(ctx context.Context, arg CreateCostDisputeParams) (CostDispute, error)
	GetAuditLedgerEntryByRequestID(ctx context.Context, requestID string) (GetAuditLedgerEntryByRequestIDRow, error)
	GetLatestAuditLedgerMerkleRoot(ctx context.Context) ([]byte, error)
	InsertAuditLedgerEntry(ctx context.Context, arg InsertAuditLedgerEntryParams) error
	ListUserCostDisputes(ctx context.Context, arg ListUserCostDisputesParams) ([]CostDispute, error)
	ResolveCostDispute(ctx context.Context, arg ResolveCostDisputeParams) (CostDispute, error)
}

var _ Querier = (*Queries)(nil)
