// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quota_reservations.sql

package quota

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getQuotaReservationByClaimForUpdate = `-- name: GetQuotaReservationByClaimForUpdate :one

SELECT
    tenant_id,
    id,
    claim_id,
    request_fingerprint,
    requested_model,
    scope_snapshot,
    policy_snapshot,
    predicted_cost,
    reserved_units,
    settled_cost,
    settled_units,
    overage_units,
    status,
    lease_expires_at,
    settled_at,
    released_at,
    release_reason
FROM quota_reservations
WHERE tenant_id = $1::bigint
  AND claim_id = $2::bigint
FOR UPDATE
`

type GetQuotaReservationByClaimForUpdateParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ClaimID  int64 `db:"claim_id" json:"claim_id"`
}

type GetQuotaReservationByClaimForUpdateRow struct {
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	ID                 int64              `db:"id" json:"id"`
	ClaimID            int64              `db:"claim_id" json:"claim_id"`
	RequestFingerprint string             `db:"request_fingerprint" json:"request_fingerprint"`
	RequestedModel     string             `db:"requested_model" json:"requested_model"`
	ScopeSnapshot      []byte             `db:"scope_snapshot" json:"scope_snapshot"`
	PolicySnapshot     []byte             `db:"policy_snapshot" json:"policy_snapshot"`
	PredictedCost      pgtype.Numeric     `db:"predicted_cost" json:"predicted_cost"`
	ReservedUnits      pgtype.Numeric     `db:"reserved_units" json:"reserved_units"`
	SettledCost        pgtype.Numeric     `db:"settled_cost" json:"settled_cost"`
	SettledUnits       pgtype.Numeric     `db:"settled_units" json:"settled_units"`
	OverageUnits       pgtype.Numeric     `db:"overage_units" json:"overage_units"`
	Status             string             `db:"status" json:"status"`
	LeaseExpiresAt     pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	SettledAt          pgtype.Timestamptz `db:"settled_at" json:"settled_at"`
	ReleasedAt         pgtype.Timestamptz `db:"released_at" json:"released_at"`
	ReleaseReason      *string            `db:"release_reason" json:"release_reason"`
}

// HUAKAI claim 级配额预留账本。所有读写都显式携带 tenant_id。
func (q *Queries) GetQuotaReservationByClaimForUpdate(ctx context.Context, arg GetQuotaReservationByClaimForUpdateParams) (GetQuotaReservationByClaimForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getQuotaReservationByClaimForUpdate, arg.TenantID, arg.ClaimID)
	var i GetQuotaReservationByClaimForUpdateRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ClaimID,
		&i.RequestFingerprint,
		&i.RequestedModel,
		&i.ScopeSnapshot,
		&i.PolicySnapshot,
		&i.PredictedCost,
		&i.ReservedUnits,
		&i.SettledCost,
		&i.SettledUnits,
		&i.OverageUnits,
		&i.Status,
		&i.LeaseExpiresAt,
		&i.SettledAt,
		&i.ReleasedAt,
		&i.ReleaseReason,
	)
	return i, err
}

const insertQuotaReservation = `-- name: InsertQuotaReservation :one
INSERT INTO quota_reservations (
    tenant_id,
    claim_id,
    request_fingerprint,
    requested_model,
    scope_snapshot,
    policy_snapshot,
    predicted_cost,
    reserved_units,
    lease_expires_at
)
SELECT
    $1::bigint,
    $2::bigint,
    $3::text,
    $4::text,
    $5::jsonb,
    $6::jsonb,
    $7::numeric(20,8),
    $8::numeric(20,8),
    $9::timestamptz
WHERE EXISTS (
    SELECT 1
    FROM billing_ledger_claims blc
    WHERE blc.tenant_id = $1::bigint
      AND blc.id = $2::bigint
)
RETURNING
    tenant_id,
    id,
    claim_id,
    request_fingerprint,
    requested_model,
    scope_snapshot,
    policy_snapshot,
    predicted_cost,
    reserved_units,
    status,
    lease_expires_at,
    created_at,
    updated_at
`

type InsertQuotaReservationParams struct {
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	ClaimID            int64              `db:"claim_id" json:"claim_id"`
	RequestFingerprint string             `db:"request_fingerprint" json:"request_fingerprint"`
	RequestedModel     string             `db:"requested_model" json:"requested_model"`
	ScopeSnapshot      []byte             `db:"scope_snapshot" json:"scope_snapshot"`
	PolicySnapshot     []byte             `db:"policy_snapshot" json:"policy_snapshot"`
	PredictedCost      pgtype.Numeric     `db:"predicted_cost" json:"predicted_cost"`
	ReservedUnits      pgtype.Numeric     `db:"reserved_units" json:"reserved_units"`
	LeaseExpiresAt     pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
}

type InsertQuotaReservationRow struct {
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	ID                 int64              `db:"id" json:"id"`
	ClaimID            int64              `db:"claim_id" json:"claim_id"`
	RequestFingerprint string             `db:"request_fingerprint" json:"request_fingerprint"`
	RequestedModel     string             `db:"requested_model" json:"requested_model"`
	ScopeSnapshot      []byte             `db:"scope_snapshot" json:"scope_snapshot"`
	PolicySnapshot     []byte             `db:"policy_snapshot" json:"policy_snapshot"`
	PredictedCost      pgtype.Numeric     `db:"predicted_cost" json:"predicted_cost"`
	ReservedUnits      pgtype.Numeric     `db:"reserved_units" json:"reserved_units"`
	Status             string             `db:"status" json:"status"`
	LeaseExpiresAt     pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) InsertQuotaReservation(ctx context.Context, arg InsertQuotaReservationParams) (InsertQuotaReservationRow, error) {
	row := q.db.QueryRow(ctx, insertQuotaReservation,
		arg.TenantID,
		arg.ClaimID,
		arg.RequestFingerprint,
		arg.RequestedModel,
		arg.ScopeSnapshot,
		arg.PolicySnapshot,
		arg.PredictedCost,
		arg.ReservedUnits,
		arg.LeaseExpiresAt,
	)
	var i InsertQuotaReservationRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ClaimID,
		&i.RequestFingerprint,
		&i.RequestedModel,
		&i.ScopeSnapshot,
		&i.PolicySnapshot,
		&i.PredictedCost,
		&i.ReservedUnits,
		&i.Status,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markQuotaReservationReconciliationNeeded = `-- name: MarkQuotaReservationReconciliationNeeded :execrows
UPDATE quota_reservations
SET status = 'reconciliation_needed',
    updated_at = NOW()
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND claim_id = $3::bigint
  AND status = 'reserved'
`

type MarkQuotaReservationReconciliationNeededParams struct {
	TenantID      int64 `db:"tenant_id" json:"tenant_id"`
	ReservationID int64 `db:"reservation_id" json:"reservation_id"`
	ClaimID       int64 `db:"claim_id" json:"claim_id"`
}

func (q *Queries) MarkQuotaReservationReconciliationNeeded(ctx context.Context, arg MarkQuotaReservationReconciliationNeededParams) (int64, error) {
	result, err := q.db.Exec(ctx, markQuotaReservationReconciliationNeeded, arg.TenantID, arg.ReservationID, arg.ClaimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const prepareQuotaReleaseRecovery = `-- name: PrepareQuotaReleaseRecovery :one
UPDATE quota_reservations
SET status = 'reconciliation_needed',
    lease_expires_at = LEAST(lease_expires_at, NOW()),
    updated_at = NOW()
WHERE tenant_id = $1::bigint
  AND claim_id = $2::bigint
  AND ($3::bigint = 0 OR id = $3::bigint)
  AND status IN ('reserved', 'reconciliation_needed')
  AND EXISTS (
      SELECT 1
      FROM billing_ledger_claims blc
      WHERE blc.tenant_id = $1::bigint
        AND blc.id = $2::bigint
        AND blc.status = 'aborted'
  )
RETURNING id
`

type PrepareQuotaReleaseRecoveryParams struct {
	TenantID      int64 `db:"tenant_id" json:"tenant_id"`
	ClaimID       int64 `db:"claim_id" json:"claim_id"`
	ReservationID int64 `db:"reservation_id" json:"reservation_id"`
}

// 仅为仍处于 aborted 终态的 claim 建立释放恢复资格。
func (q *Queries) PrepareQuotaReleaseRecovery(ctx context.Context, arg PrepareQuotaReleaseRecoveryParams) (int64, error) {
	row := q.db.QueryRow(ctx, prepareQuotaReleaseRecovery, arg.TenantID, arg.ClaimID, arg.ReservationID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const reactivateQuotaReservation = `-- name: ReactivateQuotaReservation :one
UPDATE quota_reservations
SET status = 'reserved',
    request_fingerprint = $1::text,
    requested_model = $2::text,
    scope_snapshot = $3::jsonb,
    policy_snapshot = $4::jsonb,
    predicted_cost = $5::numeric(20,8),
    reserved_units = $6::numeric(20,8),
    lease_expires_at = $7::timestamptz,
    settled_at = NULL,
    released_at = NULL,
    release_reason = NULL,
    updated_at = NOW()
WHERE tenant_id = $8::bigint
  AND id = $9::bigint
  AND claim_id = $10::bigint
  AND status IN ('released', 'expired')
RETURNING
    tenant_id,
    id,
    claim_id,
    request_fingerprint,
    requested_model,
    scope_snapshot,
    policy_snapshot,
    predicted_cost,
    reserved_units,
    status,
    lease_expires_at,
    created_at,
    updated_at
`

type ReactivateQuotaReservationParams struct {
	RequestFingerprint string             `db:"request_fingerprint" json:"request_fingerprint"`
	RequestedModel     string             `db:"requested_model" json:"requested_model"`
	ScopeSnapshot      []byte             `db:"scope_snapshot" json:"scope_snapshot"`
	PolicySnapshot     []byte             `db:"policy_snapshot" json:"policy_snapshot"`
	PredictedCost      pgtype.Numeric     `db:"predicted_cost" json:"predicted_cost"`
	ReservedUnits      pgtype.Numeric     `db:"reserved_units" json:"reserved_units"`
	LeaseExpiresAt     pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	ReservationID      int64              `db:"reservation_id" json:"reservation_id"`
	ClaimID            int64              `db:"claim_id" json:"claim_id"`
}

type ReactivateQuotaReservationRow struct {
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	ID                 int64              `db:"id" json:"id"`
	ClaimID            int64              `db:"claim_id" json:"claim_id"`
	RequestFingerprint string             `db:"request_fingerprint" json:"request_fingerprint"`
	RequestedModel     string             `db:"requested_model" json:"requested_model"`
	ScopeSnapshot      []byte             `db:"scope_snapshot" json:"scope_snapshot"`
	PolicySnapshot     []byte             `db:"policy_snapshot" json:"policy_snapshot"`
	PredictedCost      pgtype.Numeric     `db:"predicted_cost" json:"predicted_cost"`
	ReservedUnits      pgtype.Numeric     `db:"reserved_units" json:"reserved_units"`
	Status             string             `db:"status" json:"status"`
	LeaseExpiresAt     pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// released/expired claim 重试通过重新评估后复用原预留行。
func (q *Queries) ReactivateQuotaReservation(ctx context.Context, arg ReactivateQuotaReservationParams) (ReactivateQuotaReservationRow, error) {
	row := q.db.QueryRow(ctx, reactivateQuotaReservation,
		arg.RequestFingerprint,
		arg.RequestedModel,
		arg.ScopeSnapshot,
		arg.PolicySnapshot,
		arg.PredictedCost,
		arg.ReservedUnits,
		arg.LeaseExpiresAt,
		arg.TenantID,
		arg.ReservationID,
		arg.ClaimID,
	)
	var i ReactivateQuotaReservationRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ClaimID,
		&i.RequestFingerprint,
		&i.RequestedModel,
		&i.ScopeSnapshot,
		&i.PolicySnapshot,
		&i.PredictedCost,
		&i.ReservedUnits,
		&i.Status,
		&i.LeaseExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseQuotaReservation = `-- name: ReleaseQuotaReservation :execrows
UPDATE quota_reservations
SET status = 'released',
    released_at = NOW(),
    release_reason = $1::text,
    updated_at = NOW()
WHERE tenant_id = $2::bigint
  AND id = $3::bigint
  AND claim_id = $4::bigint
  AND status IN ('reserved', 'reconciliation_needed')
`

type ReleaseQuotaReservationParams struct {
	ReleaseReason string `db:"release_reason" json:"release_reason"`
	TenantID      int64  `db:"tenant_id" json:"tenant_id"`
	ReservationID int64  `db:"reservation_id" json:"reservation_id"`
	ClaimID       int64  `db:"claim_id" json:"claim_id"`
}

func (q *Queries) ReleaseQuotaReservation(ctx context.Context, arg ReleaseQuotaReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseQuotaReservation,
		arg.ReleaseReason,
		arg.TenantID,
		arg.ReservationID,
		arg.ClaimID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const settleQuotaReservation = `-- name: SettleQuotaReservation :execrows
UPDATE quota_reservations
SET status = 'settled',
    settled_cost = $1::numeric(20,8),
    settled_units = $2::numeric(20,8),
    overage_units = $3::numeric(20,8),
    settled_at = NOW(),
    updated_at = NOW()
WHERE tenant_id = $4::bigint
  AND id = $5::bigint
  AND claim_id = $6::bigint
  AND status IN ('reserved', 'reconciliation_needed')
`

type SettleQuotaReservationParams struct {
	SettledCost   pgtype.Numeric `db:"settled_cost" json:"settled_cost"`
	SettledUnits  pgtype.Numeric `db:"settled_units" json:"settled_units"`
	OverageUnits  pgtype.Numeric `db:"overage_units" json:"overage_units"`
	TenantID      int64          `db:"tenant_id" json:"tenant_id"`
	ReservationID int64          `db:"reservation_id" json:"reservation_id"`
	ClaimID       int64          `db:"claim_id" json:"claim_id"`
}

func (q *Queries) SettleQuotaReservation(ctx context.Context, arg SettleQuotaReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleQuotaReservation,
		arg.SettledCost,
		arg.SettledUnits,
		arg.OverageUnits,
		arg.TenantID,
		arg.ReservationID,
		arg.ClaimID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
