-- 0061_recharge_orders.up.sql
--
-- MONEY-3: additive recharge order table. This slice only creates local
-- pending orders; provider dispatch, callbacks, and balance credit capture
-- are intentionally out of scope.

BEGIN;

CREATE TABLE IF NOT EXISTS recharge_orders (
    id                  bigserial PRIMARY KEY,
    tenant_id           bigint        NOT NULL REFERENCES tenants(id),
    user_id             bigint        NOT NULL,
    external_trade_no   text          NOT NULL,
    recharge_ref        text          NOT NULL,
    status              text          NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING','PAID','CREDITING','COMPLETED','FAILED','EXPIRED','CANCELLED')),
    requested_amount    numeric(20,8) NOT NULL CHECK (requested_amount > 0),
    credited_amount     numeric(20,8) NOT NULL CHECK (credited_amount >= 0),
    currency_code       char(3)       NOT NULL DEFAULT 'USD',
    provider            text          NOT NULL DEFAULT 'manual',
    metadata            jsonb         NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    updated_at          timestamptz   NOT NULL DEFAULT now(),
    expires_at          timestamptz,
    paid_at             timestamptz,
    completed_at        timestamptz,
    FOREIGN KEY (tenant_id, user_id) REFERENCES users (tenant_id, id),
    CHECK (credited_amount <= requested_amount)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_recharge_orders_tenant_external_trade
    ON recharge_orders (tenant_id, external_trade_no);
CREATE UNIQUE INDEX IF NOT EXISTS uq_recharge_orders_tenant_ref
    ON recharge_orders (tenant_id, recharge_ref);
CREATE UNIQUE INDEX IF NOT EXISTS uq_recharge_orders_tenant_id
    ON recharge_orders (tenant_id, id);
CREATE INDEX IF NOT EXISTS idx_recharge_orders_user_pending
    ON recharge_orders (tenant_id, user_id, created_at DESC)
    WHERE status = 'PENDING';
CREATE INDEX IF NOT EXISTS idx_recharge_orders_user_day_active
    ON recharge_orders (tenant_id, user_id, created_at DESC)
    WHERE status IN ('PENDING','PAID','CREDITING','COMPLETED');
CREATE INDEX IF NOT EXISTS idx_recharge_orders_status_created
    ON recharge_orders (tenant_id, status, created_at DESC);

COMMENT ON TABLE recharge_orders IS
    'MONEY-3 local recharge order lifecycle. This slice creates PENDING rows only; provider callbacks and balance credits land in later gated slices.';
COMMENT ON COLUMN recharge_orders.external_trade_no IS
    'Tenant-scoped external trade identifier generated by HUAKAI or supplied by a manual provider bridge.';
COMMENT ON COLUMN recharge_orders.recharge_ref IS
    'Deterministic HUAKAI recharge reference for later balance credit capture and audit correlation.';
COMMENT ON COLUMN recharge_orders.credited_amount IS
    'USD numeric(20,8) amount to credit after successful provider confirmation. PENDING orders store the requested amount.';

COMMIT;
