-- 0131: seed verified official prices for domestic + Qwen/DeepSeek models into the
-- default pricing version (tenant 0, '1.0'). Owner-directed (官方价默认); each value
-- is USD per 1M tokens. Unlisted models still FAIL CLOSED (0068 invariant). Prices
-- PM-verified vs official pages / litellm; high-risk/stale entries (Baichuan4,
-- hunyuan-pro, StepFun) intentionally omitted pending operator confirmation.
BEGIN;
UPDATE billing_pricing_versions
SET pricing_data = jsonb_set(
        pricing_data,
        '{models}',
        COALESCE(pricing_data->'models', '{}'::jsonb) || $models${"Baichuan3-Turbo": {"input_micro_usd": 1.68, "output_micro_usd": 1.68}, "Baichuan3-Turbo-128k": {"input_micro_usd": 3.36, "output_micro_usd": 3.36}, "Baichuan4-Air": {"input_micro_usd": 0.14, "output_micro_usd": 0.14}, "Baichuan4-Turbo": {"input_micro_usd": 2.1, "output_micro_usd": 2.1}, "deepseek-chat": {"input_micro_usd": 0.28, "output_micro_usd": 0.42}, "deepseek-coder": {"input_micro_usd": 0.14, "output_micro_usd": 0.28}, "deepseek-reasoner": {"input_micro_usd": 0.28, "output_micro_usd": 0.42}, "doubao-1.5-pro-32k": {"input_micro_usd": 0.112, "output_micro_usd": 0.28}, "doubao-lite-32k": {"input_micro_usd": 0.042, "output_micro_usd": 0.084}, "doubao-pro-32k": {"input_micro_usd": 0.112, "output_micro_usd": 0.28}, "doubao-pro-4k": {"input_micro_usd": 0.112, "output_micro_usd": 0.28}, "doubao-seed-1.6": {"input_micro_usd": 0.117, "output_micro_usd": 1.168}, "ernie-3.5-8k": {"input_micro_usd": 0.112, "output_micro_usd": 0.28}, "ernie-4.0-8k": {"input_micro_usd": 0.559, "output_micro_usd": 2.238}, "ernie-4.0-turbo-8k": {"input_micro_usd": 0.42, "output_micro_usd": 1.259}, "ernie-5.0": {"input_micro_usd": 0.839, "output_micro_usd": 3.357}, "ernie-lite-8k": {"input_micro_usd": 0.0, "output_micro_usd": 0.0}, "ernie-speed-8k": {"input_micro_usd": 0.0, "output_micro_usd": 0.0}, "glm-4-air": {"input_micro_usd": 0.07, "output_micro_usd": 0.07}, "glm-4-flash": {"input_micro_usd": 0.0, "output_micro_usd": 0.0}, "glm-4-plus": {"input_micro_usd": 0.7, "output_micro_usd": 0.7}, "glm-4.5": {"input_micro_usd": 0.6, "output_micro_usd": 2.2}, "glm-4.6": {"input_micro_usd": 0.6, "output_micro_usd": 2.2}, "glm-4.6v": {"input_micro_usd": 0.3, "output_micro_usd": 0.9}, "hunyuan-lite": {"input_micro_usd": 0.0, "output_micro_usd": 0.0}, "hunyuan-standard": {"input_micro_usd": 0.63, "output_micro_usd": 0.7}, "hunyuan-turbos": {"input_micro_usd": 0.11, "output_micro_usd": 0.28}, "qwen-coder": {"input_micro_usd": 0.3, "output_micro_usd": 1.5}, "qwen-max": {"input_micro_usd": 1.6, "output_micro_usd": 6.4}, "qwen-plus": {"input_micro_usd": 0.4, "output_micro_usd": 1.2}, "qwen-turbo": {"input_micro_usd": 0.05, "output_micro_usd": 0.2}, "qwen3-next-80b-a3b-instruct": {"input_micro_usd": 0.15, "output_micro_usd": 1.2}, "qwen3-vl-32b-instruct": {"input_micro_usd": 0.16, "output_micro_usd": 0.64}, "yi-large": {"input_micro_usd": 2.8, "output_micro_usd": 2.8}, "yi-large-turbo": {"input_micro_usd": 1.68, "output_micro_usd": 1.68}, "yi-lightning": {"input_micro_usd": 0.138, "output_micro_usd": 0.138}, "yi-medium": {"input_micro_usd": 0.35, "output_micro_usd": 0.35}, "yi-vision": {"input_micro_usd": 0.84, "output_micro_usd": 0.84}}$models$::jsonb
    )
WHERE tenant_id = 0 AND version = '1.0';
COMMIT;
