// Package modulecatalog is the STATIC (Option A) overlay of the module-knowledge
// spine. It holds checked-in, generated knowledge about each HUAKAI module —
// what section it belongs to, its feature id, parity/stage status, and the Go
// packages that implement it — derived from the project feature tree
// (docs/process/feature-tree/feature-tree.json).
//
// This is the "what the module IS" half. The live moduleregistry is the "what
// the module is DOING right now" half. The two are merged at the admin endpoint.
//
// The catalog JSON is GENERATED by backend/cmd/modulecatalog-gen and committed
// into this package as module-catalog.json, then embedded via go:embed. We embed
// (rather than read a path at boot) so the binary has zero filesystem dependency
// on docs/ at runtime — the gateway can run from any working directory — and so
// the staleness guard test can diff the committed artifact against a fresh
// regeneration without touching the embedded copy.
package modulecatalog

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
)

// CatalogModule is one module's static knowledge entry.
type CatalogModule struct {
	// Pkg is the Go package short name (e.g. "billing"), unique within Modules.
	Pkg string `json:"pkg"`
	// Section is the feature-tree section the module belongs to (e.g. "§5 计费").
	Section string `json:"section"`
	// FeatureID is the feature-tree leaf identifier (e.g. "F-BILL-001").
	FeatureID string `json:"feature_id"`
	// Title is the feature-tree leaf name (human-readable).
	Title string `json:"title"`
	// Status is the implementation stage from the feature tree (e.g. "tested",
	// "wired", "planned").
	Status string `json:"status"`
	// Parity is the short parity-vs-reference note from the feature tree.
	Parity string `json:"parity,omitempty"`
	// Pkgs is the full set of packages the owning feature leaf lists (a leaf can
	// span several packages); Pkg is one member of this set.
	Pkgs []string `json:"pkgs,omitempty"`
}

// Catalog is the top-level generated artifact.
type Catalog struct {
	// Source records the feature-tree generation marker so drift is auditable.
	Source string `json:"source"`
	// Generated is the feature-tree "generated" date copied through.
	Generated string `json:"generated"`
	// Modules is sorted by Pkg for deterministic output.
	Modules []CatalogModule `json:"modules"`
}

// Lookup returns the catalog entry for a package short name.
func (c Catalog) Lookup(pkg string) (CatalogModule, bool) {
	for _, m := range c.Modules {
		if m.Pkg == pkg {
			return m, true
		}
	}
	return CatalogModule{}, false
}

// MarshalDeterministic encodes the catalog with stable key/field order and a
// trailing newline so the generator output and the staleness-guard regeneration
// byte-match. Modules are sorted by Pkg before encoding.
func (c Catalog) MarshalDeterministic() ([]byte, error) {
	sort.Slice(c.Modules, func(i, j int) bool { return c.Modules[i].Pkg < c.Modules[j].Pkg })
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false) // keep §/CJK readable in the committed artifact
	if err := enc.Encode(c); err != nil {
		return nil, fmt.Errorf("modulecatalog: marshal: %w", err)
	}
	return buf.Bytes(), nil
}
