// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package usageoverview

import (
	"context"
)

type Querier interface {
	// 租户作用域经营总览 totals。tenant_id 强制，禁止省略成全平台。
	// 列口径与平台总览一致：请求数、实扣费用、输入/输出/提示缓存写读/图像 Token
	// 与费用分项、活跃用户/密钥、成功数。不把网关响应缓存命中折进提示缓存 Token。
	AggregateTenantUsageOverviewTotals(ctx context.Context, arg AggregateTenantUsageOverviewTotalsParams) (AggregateTenantUsageOverviewTotalsRow, error)
	// 同一租户、同一结算窗口的 UTC 日桶请求数与实扣费用。
	AggregateTenantUsageOverviewTrendByDay(ctx context.Context, arg AggregateTenantUsageOverviewTrendByDayParams) ([]AggregateTenantUsageOverviewTrendByDayRow, error)
}

var _ Querier = (*Queries)(nil)
