// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package platformsettings

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Platform-wide runtime-mutable admin settings. scope=global for v1. No credential material is stored here.
type PlatformSetting struct {
	ID           int64              `db:"id" json:"id"`
	Scope        string             `db:"scope" json:"scope"`
	SettingKey   string             `db:"setting_key" json:"setting_key"`
	SettingValue string             `db:"setting_value" json:"setting_value"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedBy    string             `db:"updated_by" json:"updated_by"`
}
