// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package platformsettings

import (
	"context"
)

type Querier interface {
	// Serialize the read-modify-write audit path for the same scope/key even
	// before the first row exists.
	AcquirePlatformSettingLock(ctx context.Context, arg AcquirePlatformSettingLockParams) error
	// Platform-wide runtime settings. Table added by migration 0077.
	GetPlatformSetting(ctx context.Context, arg GetPlatformSettingParams) (PlatformSetting, error)
	GetPlatformSettingForUpdate(ctx context.Context, arg GetPlatformSettingForUpdateParams) (PlatformSetting, error)
	ListPlatformSettingsByScope(ctx context.Context, scope string) ([]PlatformSetting, error)
	UpsertPlatformSetting(ctx context.Context, arg UpsertPlatformSettingParams) (PlatformSetting, error)
}

var _ Querier = (*Queries)(nil)
