// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_proxy_quality.sql

package admin

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveProxiesByTenant = `-- name: ListActiveProxiesByTenant :many
SELECT
    id, tenant_id, name, protocol, host, port,
    auth_username, auth_secret,
    status, last_check_at, created_at, updated_at
FROM proxies
WHERE tenant_id = $1
  AND deleted_at IS NULL
  AND status = 'active'
ORDER BY id
`

type ListActiveProxiesByTenantRow struct {
	ID           int64              `db:"id" json:"id"`
	TenantID     int64              `db:"tenant_id" json:"tenant_id"`
	Name         string             `db:"name" json:"name"`
	Protocol     string             `db:"protocol" json:"protocol"`
	Host         string             `db:"host" json:"host"`
	Port         int32              `db:"port" json:"port"`
	AuthUsername *string            `db:"auth_username" json:"auth_username"`
	AuthSecret   *string            `db:"auth_secret" json:"auth_secret"`
	Status       string             `db:"status" json:"status"`
	LastCheckAt  pgtype.Timestamptz `db:"last_check_at" json:"last_check_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// 周期探活候选：未删除且仍为 active 的线路。与 CRUD 分文件以免生成码超预算。
func (q *Queries) ListActiveProxiesByTenant(ctx context.Context, tenantID int64) ([]ListActiveProxiesByTenantRow, error) {
	rows, err := q.db.Query(ctx, listActiveProxiesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveProxiesByTenantRow
	for rows.Next() {
		var i ListActiveProxiesByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Protocol,
			&i.Host,
			&i.Port,
			&i.AuthUsername,
			&i.AuthSecret,
			&i.Status,
			&i.LastCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProxyQuality = `-- name: RecordProxyQuality :one
UPDATE proxies
SET
    last_check_at = NOW(),
    quality_probed_at = NOW(),
    quality_ok = $1,
    quality_latency_ms = $2,
    quality_error_class = $3,
    quality_grade = $4,
    quality_source = $5,
    quality_success_at = CASE
        WHEN $1::boolean THEN NOW()
        ELSE quality_success_at
    END,
    quality_success_latency_ms = CASE
        WHEN $1::boolean THEN $2
        ELSE quality_success_latency_ms
    END,
    updated_at = NOW()
WHERE tenant_id = $6
  AND id = $7
  AND deleted_at IS NULL
RETURNING
    id, tenant_id, name, protocol, host, port,
    auth_username, auth_secret, group_id,
    status, last_check_at,
    quality_probed_at, quality_ok, quality_latency_ms, quality_error_class,
    quality_grade, quality_source, quality_success_at, quality_success_latency_ms,
    created_at, updated_at
`

type RecordProxyQualityParams struct {
	QualityOk         *bool   `db:"quality_ok" json:"quality_ok"`
	QualityLatencyMs  *int64  `db:"quality_latency_ms" json:"quality_latency_ms"`
	QualityErrorClass string  `db:"quality_error_class" json:"quality_error_class"`
	QualityGrade      *string `db:"quality_grade" json:"quality_grade"`
	QualitySource     *string `db:"quality_source" json:"quality_source"`
	TenantID          int64   `db:"tenant_id" json:"tenant_id"`
	ID                int64   `db:"id" json:"id"`
}

type RecordProxyQualityRow struct {
	ID                      int64              `db:"id" json:"id"`
	TenantID                int64              `db:"tenant_id" json:"tenant_id"`
	Name                    string             `db:"name" json:"name"`
	Protocol                string             `db:"protocol" json:"protocol"`
	Host                    string             `db:"host" json:"host"`
	Port                    int32              `db:"port" json:"port"`
	AuthUsername            *string            `db:"auth_username" json:"auth_username"`
	AuthSecret              *string            `db:"auth_secret" json:"auth_secret"`
	GroupID                 *string            `db:"group_id" json:"group_id"`
	Status                  string             `db:"status" json:"status"`
	LastCheckAt             pgtype.Timestamptz `db:"last_check_at" json:"last_check_at"`
	QualityProbedAt         pgtype.Timestamptz `db:"quality_probed_at" json:"quality_probed_at"`
	QualityOk               *bool              `db:"quality_ok" json:"quality_ok"`
	QualityLatencyMs        *int64             `db:"quality_latency_ms" json:"quality_latency_ms"`
	QualityErrorClass       string             `db:"quality_error_class" json:"quality_error_class"`
	QualityGrade            *string            `db:"quality_grade" json:"quality_grade"`
	QualitySource           *string            `db:"quality_source" json:"quality_source"`
	QualitySuccessAt        pgtype.Timestamptz `db:"quality_success_at" json:"quality_success_at"`
	QualitySuccessLatencyMs *int64             `db:"quality_success_latency_ms" json:"quality_success_latency_ms"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) RecordProxyQuality(ctx context.Context, arg RecordProxyQualityParams) (RecordProxyQualityRow, error) {
	row := q.db.QueryRow(ctx, recordProxyQuality,
		arg.QualityOk,
		arg.QualityLatencyMs,
		arg.QualityErrorClass,
		arg.QualityGrade,
		arg.QualitySource,
		arg.TenantID,
		arg.ID,
	)
	var i RecordProxyQualityRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Protocol,
		&i.Host,
		&i.Port,
		&i.AuthUsername,
		&i.AuthSecret,
		&i.GroupID,
		&i.Status,
		&i.LastCheckAt,
		&i.QualityProbedAt,
		&i.QualityOk,
		&i.QualityLatencyMs,
		&i.QualityErrorClass,
		&i.QualityGrade,
		&i.QualitySource,
		&i.QualitySuccessAt,
		&i.QualitySuccessLatencyMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
