// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_audit.sql

package admin

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireAdminBootstrapLock = `-- name: AcquireAdminBootstrapLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('admin_bootstrap'::text, 0))
`

// Codex N+4b2 pass-7 P2: serialize MaybeBootstrap across concurrently
// starting gateway instances. Without this lock, two pods that both see
// empty admin_tokens can each insert a fresh bootstrap row. The lock is
// a constant key so all instances contend on the same one. Released
// automatically on TX commit/rollback.
func (q *Queries) AcquireAdminBootstrapLock(ctx context.Context) error {
	_, err := q.db.Exec(ctx, acquireAdminBootstrapLock)
	return err
}

const acquireAdminIssuanceLock = `-- name: AcquireAdminIssuanceLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Codex N+4b2 pass-4 P1 fix: serialize per-actor issuance under a
// transaction-scoped advisory lock so concurrent POST /admin/v1/api-keys
// from the same admin token cannot race past the 30/hour cap. The lock
// is keyed on hash(actor_id) and released automatically on TX
// commit/rollback. Must be called BEFORE CountIssuanceInWindow inside
// the same TX, otherwise the count→insert window remains racy.
func (q *Queries) AcquireAdminIssuanceLock(ctx context.Context, actorID string) error {
	_, err := q.db.Exec(ctx, acquireAdminIssuanceLock, actorID)
	return err
}

const countIssuanceInWindow = `-- name: CountIssuanceInWindow :one
SELECT count(*)::bigint
FROM admin_audit_events
WHERE actor_id = $1::text
  AND action = 'issue_api_key'
  AND target_id IS NOT NULL
  AND occurred_at > now() - make_interval(secs => $2::integer)
`

type CountIssuanceInWindowParams struct {
	ActorID       string `db:"actor_id" json:"actor_id"`
	WindowSeconds int32  `db:"window_seconds" json:"window_seconds"`
}

// D4 rate-limit window: how many SUCCESSFUL 'issue_api_key' actions has
// this actor performed in the last `window_seconds`? Default cap = 30/hour
// per token, enforced by the issuer service.
//
// Codex N+4b2 pass-10 P2: filter on target_id IS NOT NULL so denied
// attempts (which write a deny audit row with target_id=0/NULL) are
// excluded from the cap. Otherwise an actor that hits the cap keeps
// refreshing the window with deny rows on every retry and never recovers.
func (q *Queries) CountIssuanceInWindow(ctx context.Context, arg CountIssuanceInWindowParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIssuanceInWindow, arg.ActorID, arg.WindowSeconds)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertAdminAuditEvent = `-- name: InsertAdminAuditEvent :one

INSERT INTO admin_audit_events (
    tenant_id, actor_id, actor_role, action,
    target_type, target_id, request_id, reason, payload
) VALUES (
    $1::bigint,
    $2::text,
    $3::text,
    $4::text,
    $5::text,
    $6::bigint,
    $7::text,
    $8::text,
    $9::jsonb
)
RETURNING id, occurred_at
`

type InsertAdminAuditEventParams struct {
	TenantID   *int64  `db:"tenant_id" json:"tenant_id"`
	ActorID    string  `db:"actor_id" json:"actor_id"`
	ActorRole  string  `db:"actor_role" json:"actor_role"`
	Action     string  `db:"action" json:"action"`
	TargetType string  `db:"target_type" json:"target_type"`
	TargetID   *int64  `db:"target_id" json:"target_id"`
	RequestID  *string `db:"request_id" json:"request_id"`
	Reason     *string `db:"reason" json:"reason"`
	Payload    []byte  `db:"payload" json:"payload"`
}

type InsertAdminAuditEventRow struct {
	ID         int64              `db:"id" json:"id"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

// Slice 2 (N+4b2) admin_audit_events queries.
// Per CMB-5 + CMB-7: these queries are append-only writes. NEVER store
// plaintext bearer or key_hash inside the payload jsonb.
// Append a single admin action audit row. Called inside the same TX as
// the corresponding api_keys / admin_tokens write so the audit trail is
// atomic with the action.
func (q *Queries) InsertAdminAuditEvent(ctx context.Context, arg InsertAdminAuditEventParams) (InsertAdminAuditEventRow, error) {
	row := q.db.QueryRow(ctx, insertAdminAuditEvent,
		arg.TenantID,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.Reason,
		arg.Payload,
	)
	var i InsertAdminAuditEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}
