// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: admin_provider_account_bulk.sql

package admin

import (
	"context"
)

const getChannelForBulkMove = `-- name: GetChannelForBulkMove :one
SELECT id, pool_group_id, name, enabled
FROM channels
WHERE id = $1::bigint
  AND tenant_id = $2::bigint
  AND deleted_at IS NULL
`

type GetChannelForBulkMoveParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

type GetChannelForBulkMoveRow struct {
	ID          int64  `db:"id" json:"id"`
	PoolGroupID int64  `db:"pool_group_id" json:"pool_group_id"`
	Name        string `db:"name" json:"name"`
	Enabled     bool   `db:"enabled" json:"enabled"`
}

// 批量改渠道的目标渠道校验:必须属于同一租户且未删除;返回所属池组与启用态供审计与风险提示。
func (q *Queries) GetChannelForBulkMove(ctx context.Context, arg GetChannelForBulkMoveParams) (GetChannelForBulkMoveRow, error) {
	row := q.db.QueryRow(ctx, getChannelForBulkMove, arg.ID, arg.TenantID)
	var i GetChannelForBulkMoveRow
	err := row.Scan(
		&i.ID,
		&i.PoolGroupID,
		&i.Name,
		&i.Enabled,
	)
	return i, err
}

const lockProviderAccountForBulk = `-- name: LockProviderAccountForBulk :one
SELECT id, enabled, priority, static_weight, channel_id, provider_id, account_type, name
FROM provider_accounts
WHERE id = $1::bigint
  AND tenant_id = $2::bigint
  AND deleted_at IS NULL
FOR UPDATE
`

type LockProviderAccountForBulkParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

type LockProviderAccountForBulkRow struct {
	ID           int64  `db:"id" json:"id"`
	Enabled      bool   `db:"enabled" json:"enabled"`
	Priority     int32  `db:"priority" json:"priority"`
	StaticWeight int32  `db:"static_weight" json:"static_weight"`
	ChannelID    int64  `db:"channel_id" json:"channel_id"`
	ProviderID   int64  `db:"provider_id" json:"provider_id"`
	AccountType  string `db:"account_type" json:"account_type"`
	Name         string `db:"name" json:"name"`
}

// 批量运维逐项事务:按 (id, tenant) 锁定未删除账号并读取将改字段的当前值,用于"已达期望态 → skipped"
// 判定与审计 before/after;他租户或已删除 → no rows(调用方统一映射为 not_found,不区分)。
func (q *Queries) LockProviderAccountForBulk(ctx context.Context, arg LockProviderAccountForBulkParams) (LockProviderAccountForBulkRow, error) {
	row := q.db.QueryRow(ctx, lockProviderAccountForBulk, arg.ID, arg.TenantID)
	var i LockProviderAccountForBulkRow
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Priority,
		&i.StaticWeight,
		&i.ChannelID,
		&i.ProviderID,
		&i.AccountType,
		&i.Name,
	)
	return i, err
}

const updateProviderAccountChannel = `-- name: UpdateProviderAccountChannel :execrows
UPDATE provider_accounts
SET channel_id = $1::bigint,
    updated_at = now(),
    last_modified_by_actor = $2::text
WHERE id = $3::bigint
  AND tenant_id = $4::bigint
  AND deleted_at IS NULL
`

type UpdateProviderAccountChannelParams struct {
	ChannelID int64   `db:"channel_id" json:"channel_id"`
	ActorID   *string `db:"actor_id" json:"actor_id"`
	ID        int64   `db:"id" json:"id"`
	TenantID  int64   `db:"tenant_id" json:"tenant_id"`
}

// 批量改渠道:只改 channel_id;调用方已在同一事务内锁定账号、校验目标渠道并完成混合风险判定。
func (q *Queries) UpdateProviderAccountChannel(ctx context.Context, arg UpdateProviderAccountChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProviderAccountChannel,
		arg.ChannelID,
		arg.ActorID,
		arg.ID,
		arg.TenantID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
