// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package admin

import (
	"context"
)

type Querier interface {
	// Serialize MaybeBootstrap across concurrently
	// starting gateway instances. Without this lock, two pods that both see
	// empty admin_tokens can each insert a fresh bootstrap row. The lock is
	// a constant key so all instances contend on the same one. Released
	// automatically on TX commit/rollback.
	AcquireAdminBootstrapLock(ctx context.Context) error
	// Serialize per-actor issuance under a
	// transaction-scoped advisory lock so concurrent POST /admin/v1/api-keys
	// from the same admin token cannot race past the 30/hour cap. The lock
	// is keyed on hash(actor_id) and released automatically on TX
	// commit/rollback. Must be called BEFORE CountIssuanceInWindow inside
	// the same TX, otherwise the count→insert window remains racy.
	AcquireAdminIssuanceLock(ctx context.Context, actorID string) error
	// 在生成 bearer 与 bcrypt 前确认目标是有效终端用户。
	AdminCheckIssuanceTarget(ctx context.Context, arg AdminCheckIssuanceTargetParams) (AdminCheckIssuanceTargetRow, error)
	// Codex N+4b2 pass-8 P2: list endpoint must verify the tenant exists
	// before writing the audit row, otherwise the admin_audit_events.tenant_id
	// FK turns "tenant_id=<bogus>" into a 503 audit-write failure instead
	// of a clean 404. Active OR disabled is fine — we just need a valid FK
	// target.
	AdminCheckTenantExists(ctx context.Context, tenantID int64) (bool, error)
	// 撤销流程使用的租户级 purpose=user Key 查询。不得依赖持有人当前状态，
	// 否则最需要退役的历史凭据反而会从管理面消失。
	AdminGetAPIKeyByID(ctx context.Context, arg AdminGetAPIKeyByIDParams) (AdminGetAPIKeyByIDRow, error)
	AdminGetTwoFAAdoptionStatsForTenant(ctx context.Context, tenantID int64) (AdminGetTwoFAAdoptionStatsForTenantRow, error)
	AdminGetUserForTenant(ctx context.Context, arg AdminGetUserForTenantParams) (AdminGetUserForTenantRow, error)
	// 管理侧 api_keys 查询由 internal/admin 调用，与 internal/auth 面向客户的
	// LookupAPIKeysByPrefix 热路径相互独立。管理面不得复用只按前缀查找的热路径，
	// 两者属于不同安全边界。
	// 写入时锁定并确认租户和终端用户仍有效；目标在外部预检后失活或角色已不是
	// user 时返回 NoRows。FOR SHARE 会与生命周期/用户状态的非键更新互斥，避免
	// 停用提交后又从旧快照落下一把新 Key。
	AdminInsertAPIKey(ctx context.Context, arg AdminInsertAPIKeyParams) (AdminInsertAPIKeyRow, error)
	// 列出该租户全部 purpose=user Key 元数据，绝不返回 key_hash。这里不能按
	// users 当前角色或 deleted_at 过滤：持有人升为管理员或被软删后，历史凭据
	// 仍必须留在运维视野中并可被永久撤销。
	AdminListAPIKeysForTenant(ctx context.Context, arg AdminListAPIKeysForTenantParams) ([]AdminListAPIKeysForTenantRow, error)
	AdminListUserBalanceHistoryForTenant(ctx context.Context, arg AdminListUserBalanceHistoryForTenantParams) ([]AdminListUserBalanceHistoryForTenantRow, error)
	// 管理端终端用户只读查询。每条查询都必须同时限定 tenant 与 role='user'，
	// 且绝不返回密码、Key hash 或其他凭据材料。
	AdminListUsersForTenant(ctx context.Context, arg AdminListUsersForTenantParams) ([]AdminListUsersForTenantRow, error)
	// 将终端用户 Key 的任意非 revoked 状态收敛为 revoked。返回 0 行表示已撤销，
	// 持有人的当前角色和删除状态不得阻断永久撤销。
	AdminRevokeAPIKey(ctx context.Context, arg AdminRevokeAPIKeyParams) (int64, error)
	CountActiveProviderAccountsForProvider(ctx context.Context, arg CountActiveProviderAccountsForProviderParams) (int64, error)
	// Used by bootstrap: env-var bootstrap MUST only insert when NO
	// admin token row has ever been minted (regardless of current status).
	// An active-only count would let a stale env
	// var re-bootstrap after the operator disabled/revoked all tokens, which
	// breaks the "one-shot" guarantee. Counting all non-deleted rows closes
	// that hole; if you want to wipe and re-bootstrap, hard-delete the row.
	CountAdminTokensIncludingInactive(ctx context.Context) (int64, error)
	// D4 rate-limit window: how many SUCCESSFUL 'issue_api_key' actions has
	// this actor performed in the last `window_seconds`? Default cap = 30/hour
	// per token, enforced by the issuer service.
	//
	// Filter on target_id IS NOT NULL so denied
	// attempts (which write a deny audit row with target_id=0/NULL) are
	// excluded from the cap. Otherwise an actor that hits the cap keeps
	// refreshing the window with deny rows on every retry and never recovers.
	//
	// 双格式分桶(role 制单登录 S3 修):P2b-1 把 actor_id 从裸 TokenID("5")统一成
	// AuditActor() 串("admin_token:5"),部署边界老行匹配不到会重置限流窗。谓词兼容
	// 两种键(legacy_actor_id=老格式;无老格式的来源传同一串,OR 无副作用),窗口跨
	// 格式迁移连续,且不需要新列/回填(数值列方案会再造一次同类边界重置)。
	CountIssuanceInWindow(ctx context.Context, arg CountIssuanceInWindowParams) (int64, error)
	// 渠道目录写操作。三个请求改写字段均在 channels 上维护。
	// pool_group 必须属于同租户(EXISTS 守卫防跨租户链接);name 唯一冲突由
	// uq_channels_tenant_pool_name 抛 23505。
	CreateChannel(ctx context.Context, arg CreateChannelParams) (CreateChannelRow, error)
	CreateChannelTestTemplate(ctx context.Context, arg CreateChannelTestTemplateParams) (ChannelTestTemplate, error)
	// auth_secret 应由调用方加密后传入 (HUAKAI credentialstore.KeyProvider)。
	// sqlc 层是字节流, 不强制加密格式 — 业务层负责。
	CreateProxy(ctx context.Context, arg CreateProxyParams) (CreateProxyRow, error)
	CreateTLSFingerprintProfile(ctx context.Context, arg CreateTLSFingerprintProfileParams) (CreateTLSFingerprintProfileRow, error)
	DeleteChannelTestTemplate(ctx context.Context, arg DeleteChannelTestTemplateParams) (ChannelTestTemplate, error)
	DeleteProxyIfUnused(ctx context.Context, arg DeleteProxyIfUnusedParams) (DeleteProxyIfUnusedRow, error)
	// After the operator issues a real (non-bootstrap) admin token, the
	// bootstrap rows should be auto-disabled so the env-var token is no
	// longer accepted by the resolver. Idempotent.
	DisableBootstrapAdminTokens(ctx context.Context) (int64, error)
	GetAdminChannel(ctx context.Context, arg GetAdminChannelParams) (GetAdminChannelRow, error)
	GetAdminProviderAccountHealth(ctx context.Context, arg GetAdminProviderAccountHealthParams) (GetAdminProviderAccountHealthRow, error)
	// Fetch a single admin token's metadata (no key_hash) for revoke
	// pre-checks and idempotency decisions. Soft-deleted rows are excluded.
	GetAdminTokenByID(ctx context.Context, id int64) (GetAdminTokenByIDRow, error)
	GetChannelTestTemplate(ctx context.Context, arg GetChannelTestTemplateParams) (ChannelTestTemplate, error)
	// P0 provider/channel admin catalog queries.
	// Read-only directory data for admin UI. These SELECT lists intentionally
	// exclude tenant_id and every credential-bearing provider_accounts column.
	// 账号创建事务内读取并锁定 provider 协议。必须用 FOR SHARE 而非 FOR KEY SHARE:
	// upstream_protocol 是非键列,管理端改它取 FOR NO KEY UPDATE 锁;FOR KEY SHARE 与之
	// 不冲突,会放过"创建读旧协议→管理端改新协议→创建插入不兼容账号"的 TOCTOU。
	// FOR SHARE 与 FOR NO KEY UPDATE 冲突,把协议钉到创建事务提交,同时允许并发创建共存。
	GetProviderProtocolForAccountCreate(ctx context.Context, arg GetProviderProtocolForAccountCreateParams) (string, error)
	GetProxy(ctx context.Context, arg GetProxyParams) (GetProxyRow, error)
	GetProxyDeleteImpact(ctx context.Context, arg GetProxyDeleteImpactParams) (GetProxyDeleteImpactRow, error)
	// 单 profile 查询 (按 tenant + id 双过滤); admin UI 编辑 + resolver 走这条。
	GetTLSFingerprintProfile(ctx context.Context, arg GetTLSFingerprintProfileParams) (GetTLSFingerprintProfileRow, error)
	// Admin audit event queries.
	// These queries are append-only writes. NEVER store
	// plaintext bearer or key_hash inside the payload jsonb.
	// Append a single admin action audit row. Called inside the same TX as
	// the corresponding api_keys / admin_tokens write so the audit trail is
	// atomic with the action.
	InsertAdminAuditEvent(ctx context.Context, arg InsertAdminAuditEventParams) (InsertAdminAuditEventRow, error)
	// Creates an admin_tokens row. Caller passes a pre-bcrypt-hashed key_hash
	// and the prefix derived from the plaintext (first 16 chars).
	InsertAdminToken(ctx context.Context, arg InsertAdminTokenParams) (int64, error)
	InsertProvider(ctx context.Context, arg InsertProviderParams) (InsertProviderRow, error)
	InsertProviderAccountRaw(ctx context.Context, arg InsertProviderAccountRawParams) (int64, error)
	// Phase 3 health check worker 用 (选 active 但 last_check_at 老的 ping)。
	ListActiveProxiesByTenant(ctx context.Context, tenantID int64) ([]ListActiveProxiesByTenantRow, error)
	// Drift worker 用; 只取 status='active' 且未软删。
	ListActiveTLSFingerprintProfilesByTenant(ctx context.Context, tenantID int64) ([]ListActiveTLSFingerprintProfilesByTenantRow, error)
	ListAdminChannelsByTenant(ctx context.Context, arg ListAdminChannelsByTenantParams) ([]ListAdminChannelsByTenantRow, error)
	ListAdminProvidersByTenant(ctx context.Context, arg ListAdminProvidersByTenantParams) ([]ListAdminProvidersByTenantRow, error)
	// Metadata-only listing of admin tokens for the operator console. NEVER
	// selects key_hash — only key_prefix (insufficient on its own to
	// authenticate) plus lifecycle columns. Soft-deleted rows are excluded.
	// platform_admin scope sees every row; the handler-side RBAC decides who
	// may call this read.
	ListAdminTokens(ctx context.Context, arg ListAdminTokensParams) ([]ListAdminTokensRow, error)
	ListChannelTestTemplatesByTenant(ctx context.Context, arg ListChannelTestTemplatesByTenantParams) ([]ChannelTestTemplate, error)
	// HUAKAI F-FP-POOL Phase 1.3 sqlc queries — 出口代理池 CRUD。
	//
	// 多租户约束 (DR-001/TS-006): 所有 query 以 tenant_id 为第一参数过滤,
	// 跨租户访问被 WHERE 拒绝在 SQL 层。
	ListProxiesByTenant(ctx context.Context, tenantID int64) ([]ListProxiesByTenantRow, error)
	// HUAKAI F-FP-POOL Phase 1.3 sqlc queries — TLS 指纹模板池 CRUD。
	//
	// 多租户约束 (DR-001/TS-006): 所有 query 必须以 tenant_id 为第一参数过滤,
	// 跨租户访问被 WHERE 子句拒绝在 SQL 层。
	// admin 后台列表; 返回该 tenant 下所有未软删行 (含 disabled / drift_detected)。
	ListTLSFingerprintProfilesByTenant(ctx context.Context, tenantID int64) ([]ListTLSFingerprintProfilesByTenantRow, error)
	// Admin token queries.
	// This file is consumed only by internal/admin and never by
	// internal/auth (the inbound customer resolver). Queries
	// never SELECT key_hash for any purpose other than bcrypt comparison
	// inside the resolver, and never join into log/trace fields.
	// Returns active candidates whose key_prefix matches. Mirrors the
	// customer API key lookup shape (LIMIT 5 caps bcrypt fanout DOS).
	// Status is enforced here; deleted_at filters parent rows.
	//
	// tenant_operator tokens MUST be rejected
	// when their scoped tenant is disabled or soft-deleted. We LEFT JOIN
	// tenants so platform_admin tokens (scope_tenant_id IS NULL) still
	// resolve, but tenant_operator tokens whose tenant is disabled/deleted
	// get filtered at the SQL layer — no app-side check required.
	LookupAdminTokenByPrefix(ctx context.Context, keyPrefix string) ([]LookupAdminTokenByPrefixRow, error)
	RecordProviderAccountProbe(ctx context.Context, arg RecordProviderAccountProbeParams) (int64, error)
	// Soft-revoke an admin token. Tenant-bound revocation isn't enforced here
	// because admin_tokens has no tenant ownership for platform_admin rows;
	// the handler-side RBAC check decides whether the caller can revoke.
	RevokeAdminToken(ctx context.Context, arg RevokeAdminTokenParams) (int64, error)
	// Phase 3 health check worker 标 dead/active, admin 手动 disable 走这。
	SetProxyStatus(ctx context.Context, arg SetProxyStatusParams) (int64, error)
	// status 转换专用; drift worker 标 'drift_detected', admin disable/enable 走这。
	// 不动 updated_at (status 不算内容变); active 时刷 last_validated_at.
	SetTLSFingerprintProfileStatus(ctx context.Context, arg SetTLSFingerprintProfileStatusParams) error
	SoftDeleteChannel(ctx context.Context, arg SoftDeleteChannelParams) (SoftDeleteChannelRow, error)
	SoftDeleteProvider(ctx context.Context, arg SoftDeleteProviderParams) (SoftDeleteProviderRow, error)
	SoftDeleteProviderAccount(ctx context.Context, arg SoftDeleteProviderAccountParams) error
	SoftDeleteProxy(ctx context.Context, arg SoftDeleteProxyParams) error
	// 软删 (设 deleted_at); provider_accounts.tls_fingerprint_profile_id 引用仍存在
	// (FK 不级联), 但 resolver 走 GetByID 因 deleted_at IS NULL 过滤掉, 降级到 builtin.
	SoftDeleteTLSFingerprintProfile(ctx context.Context, arg SoftDeleteTLSFingerprintProfileParams) error
	// 账号池健康聚合(B9 运维巡检):按 (health_state, enabled) 计数,跨整个租户池(非分页)。
	// 只读、不含钱字段;供管理端一眼看清问题账号分布。软删账号排除。
	SummarizeProviderAccountHealth(ctx context.Context, tenantID int64) ([]SummarizeProviderAccountHealthRow, error)
	// 由异步请求完成事件调用,单调记录被动请求观测时间。
	TouchProviderAccountRequestObservedAt(ctx context.Context, arg TouchProviderAccountRequestObservedAtParams) error
	UpdateAdminProviderAccountRaw(ctx context.Context, arg UpdateAdminProviderAccountRawParams) (UpdateAdminProviderAccountRawRow, error)
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (UpdateChannelRow, error)
	UpdateChannelTestTemplate(ctx context.Context, arg UpdateChannelTestTemplateParams) (ChannelTestTemplate, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (UpdateProviderRow, error)
	UpdateProviderAccountEnabled(ctx context.Context, arg UpdateProviderAccountEnabledParams) error
	// 绑定/解绑 provider account 的 TLS 指纹 profile。profile_id 为 NULL → 解绑回内置默认;
	// 非 NULL → 绑定(DB 触发器 0038 校验 profile 属同租户,跨租户绑定被拒)。
	UpdateProviderAccountFingerprintProfile(ctx context.Context, arg UpdateProviderAccountFingerprintProfileParams) error
	UpdateProxy(ctx context.Context, arg UpdateProxyParams) (UpdateProxyRow, error)
	// 全字段更新; admin UI 修改时调用。updated_at 自动刷; status 走专用 SetStatus 端点。
	UpdateTLSFingerprintProfile(ctx context.Context, arg UpdateTLSFingerprintProfileParams) (UpdateTLSFingerprintProfileRow, error)
}

var _ Querier = (*Queries)(nil)
