// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_storm.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrCreateAccountStormBudget = `-- name: GetOrCreateAccountStormBudget :one
WITH inserted AS (
    INSERT INTO oauth_storm_budget (
        scope_type,
        tenant_id,
        provider_account_id,
        cap_concurrent_refreshes,
        cap_refreshes_per_minute
    ) VALUES (
        'account',
        $1,
        $2,
        1,
        60
    )
    ON CONFLICT (tenant_id, provider_account_id)
    WHERE scope_type = 'account'
    DO NOTHING
    RETURNING id, tenant_id, scope_type, provider_account_id, provider_code, oauth_endpoint_fingerprint, cap_concurrent_refreshes, cap_refreshes_per_minute, current_in_flight, refreshes_in_window, window_start, circuit_open_until, last_updated_at
)
SELECT id, tenant_id, scope_type, provider_account_id, provider_code, oauth_endpoint_fingerprint, cap_concurrent_refreshes, cap_refreshes_per_minute, current_in_flight, refreshes_in_window, window_start, circuit_open_until, last_updated_at
FROM inserted
UNION ALL
SELECT id, tenant_id, scope_type, provider_account_id, provider_code, oauth_endpoint_fingerprint, cap_concurrent_refreshes, cap_refreshes_per_minute, current_in_flight, refreshes_in_window, window_start, circuit_open_until, last_updated_at
FROM oauth_storm_budget
WHERE scope_type = 'account'
  AND tenant_id = $1
  AND provider_account_id = $2
LIMIT 1
`

type GetOrCreateAccountStormBudgetParams struct {
	TenantID          int64  `db:"tenant_id" json:"tenant_id"`
	ProviderAccountID *int64 `db:"provider_account_id" json:"provider_account_id"`
}

type GetOrCreateAccountStormBudgetRow struct {
	ID                       int64              `db:"id" json:"id"`
	TenantID                 int64              `db:"tenant_id" json:"tenant_id"`
	ScopeType                string             `db:"scope_type" json:"scope_type"`
	ProviderAccountID        *int64             `db:"provider_account_id" json:"provider_account_id"`
	ProviderCode             *string            `db:"provider_code" json:"provider_code"`
	OauthEndpointFingerprint *string            `db:"oauth_endpoint_fingerprint" json:"oauth_endpoint_fingerprint"`
	CapConcurrentRefreshes   int32              `db:"cap_concurrent_refreshes" json:"cap_concurrent_refreshes"`
	CapRefreshesPerMinute    int32              `db:"cap_refreshes_per_minute" json:"cap_refreshes_per_minute"`
	CurrentInFlight          int32              `db:"current_in_flight" json:"current_in_flight"`
	RefreshesInWindow        int32              `db:"refreshes_in_window" json:"refreshes_in_window"`
	WindowStart              pgtype.Timestamptz `db:"window_start" json:"window_start"`
	CircuitOpenUntil         pgtype.Timestamptz `db:"circuit_open_until" json:"circuit_open_until"`
	LastUpdatedAt            pgtype.Timestamptz `db:"last_updated_at" json:"last_updated_at"`
}

func (q *Queries) GetOrCreateAccountStormBudget(ctx context.Context, arg GetOrCreateAccountStormBudgetParams) (GetOrCreateAccountStormBudgetRow, error) {
	row := q.db.QueryRow(ctx, getOrCreateAccountStormBudget, arg.TenantID, arg.ProviderAccountID)
	var i GetOrCreateAccountStormBudgetRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ProviderAccountID,
		&i.ProviderCode,
		&i.OauthEndpointFingerprint,
		&i.CapConcurrentRefreshes,
		&i.CapRefreshesPerMinute,
		&i.CurrentInFlight,
		&i.RefreshesInWindow,
		&i.WindowStart,
		&i.CircuitOpenUntil,
		&i.LastUpdatedAt,
	)
	return i, err
}

const releaseAccountStormSlot = `-- name: ReleaseAccountStormSlot :exec
UPDATE oauth_storm_budget
SET
    current_in_flight = GREATEST(current_in_flight - 1, 0),
    last_updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ReleaseAccountStormSlot(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, releaseAccountStormSlot, id)
	return err
}

const tryAcquireAccountStormSlot = `-- name: TryAcquireAccountStormSlot :one
WITH acquired AS (
    UPDATE oauth_storm_budget
    SET
        current_in_flight = current_in_flight + 1,
        last_updated_at = NOW()
    WHERE id = $1
      AND current_in_flight < cap_concurrent_refreshes
    RETURNING current_in_flight
)
SELECT current_in_flight
FROM acquired
UNION ALL
SELECT 0::integer AS current_in_flight
WHERE NOT EXISTS (SELECT 1 FROM acquired)
LIMIT 1
`

func (q *Queries) TryAcquireAccountStormSlot(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, tryAcquireAccountStormSlot, id)
	var current_in_flight int32
	err := row.Scan(&current_in_flight)
	return current_in_flight, err
}
