// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: billing_settle.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const getClaimForSettle = `-- name: GetClaimForSettle :one

SELECT
    id,
    tenant_id,
    api_key_id,
    user_id,
    provider_account_id,
    acquisition_token,
    attempt_seq,
    predicted_cost,
    currency_code,
    billing_policy_version,
    requested_model,
    request_fingerprint,
    status
FROM billing_ledger_claims
WHERE id = $1 AND tenant_id = $2 AND acquisition_token = $3 AND status = 'reserving'
FOR UPDATE
`

type GetClaimForSettleParams struct {
	ID               int64     `db:"id" json:"id"`
	TenantID         int64     `db:"tenant_id" json:"tenant_id"`
	AcquisitionToken uuid.UUID `db:"acquisition_token" json:"acquisition_token"`
}

type GetClaimForSettleRow struct {
	ID                   int64           `db:"id" json:"id"`
	TenantID             int64           `db:"tenant_id" json:"tenant_id"`
	APIKeyID             int64           `db:"api_key_id" json:"api_key_id"`
	UserID               int64           `db:"user_id" json:"user_id"`
	ProviderAccountID    *int64          `db:"provider_account_id" json:"provider_account_id"`
	AcquisitionToken     uuid.UUID       `db:"acquisition_token" json:"acquisition_token"`
	AttemptSeq           int32           `db:"attempt_seq" json:"attempt_seq"`
	PredictedCost        decimal.Decimal `db:"predicted_cost" json:"predicted_cost"`
	CurrencyCode         string          `db:"currency_code" json:"currency_code"`
	BillingPolicyVersion string          `db:"billing_policy_version" json:"billing_policy_version"`
	RequestedModel       string          `db:"requested_model" json:"requested_model"`
	RequestFingerprint   string          `db:"request_fingerprint" json:"request_fingerprint"`
	Status               string          `db:"status" json:"status"`
}

// F-OBS-001 Tx2 Settler queries.
// Backed by billing_ledger_claims + usage_records + billing_events tables
// in docs/schema/observability-billing.sql + scheduler_outbox in
// docs/schema/pool-routing.sql.
// Tx2 entry: lock the claim row + verify still-settle-able state.
// Spec §Tx2 step 9: re-fetch claim row; verify status='reserving' AND
// acquisition_token matches.
func (q *Queries) GetClaimForSettle(ctx context.Context, arg GetClaimForSettleParams) (GetClaimForSettleRow, error) {
	row := q.db.QueryRow(ctx, getClaimForSettle, arg.ID, arg.TenantID, arg.AcquisitionToken)
	var i GetClaimForSettleRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.APIKeyID,
		&i.UserID,
		&i.ProviderAccountID,
		&i.AcquisitionToken,
		&i.AttemptSeq,
		&i.PredictedCost,
		&i.CurrencyCode,
		&i.BillingPolicyVersion,
		&i.RequestedModel,
		&i.RequestFingerprint,
		&i.Status,
	)
	return i, err
}

const insertBillingEvent = `-- name: InsertBillingEvent :one
INSERT INTO billing_events (
    tenant_id, claim_id, event_type,
    actual_cost, actual_cost_signed,
    end_class, usage_source,
    stream_state, delivered_token_count, stream_terminated_reason,
    fingerprint, audit_request_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, occurred_at
`

type InsertBillingEventParams struct {
	TenantID               int64           `db:"tenant_id" json:"tenant_id"`
	ClaimID                *int64          `db:"claim_id" json:"claim_id"`
	EventType              string          `db:"event_type" json:"event_type"`
	ActualCost             decimal.Decimal `db:"actual_cost" json:"actual_cost"`
	ActualCostSigned       decimal.Decimal `db:"actual_cost_signed" json:"actual_cost_signed"`
	EndClass               *string         `db:"end_class" json:"end_class"`
	UsageSource            *string         `db:"usage_source" json:"usage_source"`
	StreamState            int16           `db:"stream_state" json:"stream_state"`
	DeliveredTokenCount    int64           `db:"delivered_token_count" json:"delivered_token_count"`
	StreamTerminatedReason *string         `db:"stream_terminated_reason" json:"stream_terminated_reason"`
	Fingerprint            string          `db:"fingerprint" json:"fingerprint"`
	AuditRequestID         *string         `db:"audit_request_id" json:"audit_request_id"`
}

type InsertBillingEventRow struct {
	ID         int64              `db:"id" json:"id"`
	OccurredAt pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

// Spec §Tx2 step 13: audit-grade event row in same Tx; survives Usage Record
// async failure (per F-OBS-001 H8). event_type per CHECK constraint.
func (q *Queries) InsertBillingEvent(ctx context.Context, arg InsertBillingEventParams) (InsertBillingEventRow, error) {
	row := q.db.QueryRow(ctx, insertBillingEvent,
		arg.TenantID,
		arg.ClaimID,
		arg.EventType,
		arg.ActualCost,
		arg.ActualCostSigned,
		arg.EndClass,
		arg.UsageSource,
		arg.StreamState,
		arg.DeliveredTokenCount,
		arg.StreamTerminatedReason,
		arg.Fingerprint,
		arg.AuditRequestID,
	)
	var i InsertBillingEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}

const insertSchedulerOutboxRow = `-- name: InsertSchedulerOutboxRow :one
INSERT INTO scheduler_outbox (
    tenant_id, event_type, pool_group_id, provider_account_id, payload
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, created_at
`

type InsertSchedulerOutboxRowParams struct {
	TenantID          int64  `db:"tenant_id" json:"tenant_id"`
	EventType         string `db:"event_type" json:"event_type"`
	PoolGroupID       *int64 `db:"pool_group_id" json:"pool_group_id"`
	ProviderAccountID *int64 `db:"provider_account_id" json:"provider_account_id"`
	Payload           []byte `db:"payload" json:"payload"`
}

type InsertSchedulerOutboxRowRow struct {
	ID        int64              `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Spec §Tx2 step 11: cross-threshold notification, in same Tx.
// For Phase B.5 v0.1, the threshold detection itself is stubbed (operator
// policy returns false unless explicitly forced in test); when the policy
// returns true, this query enqueues the row.
func (q *Queries) InsertSchedulerOutboxRow(ctx context.Context, arg InsertSchedulerOutboxRowParams) (InsertSchedulerOutboxRowRow, error) {
	row := q.db.QueryRow(ctx, insertSchedulerOutboxRow,
		arg.TenantID,
		arg.EventType,
		arg.PoolGroupID,
		arg.ProviderAccountID,
		arg.Payload,
	)
	var i InsertSchedulerOutboxRowRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const insertUsageRecord = `-- name: InsertUsageRecord :one
INSERT INTO usage_records (
    tenant_id, claim_id, api_key_id, user_id, provider_account_id,
    acquisition_token, attempt_seq,
    tokens_input, tokens_output,
    cache_creation_tokens, cache_read_tokens,
    cache_creation_5m_tokens, cache_creation_1h_tokens, image_output_tokens,
    actual_cost, input_cost, output_cost,
    cache_creation_cost, cache_read_cost, image_output_cost,
    end_class, usage_source, confidence_score, pending_reconciliation,
    stream_state, delivered_token_count, stream_terminated_reason,
    drain_outcome, routing_reason, protocol_loss,
    requested_at, upstream_request_at, first_byte_at, first_event_at, last_event_at,
    requested_model, upstream_model, stream, snapshot_version
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    $8, $9,
    $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20,
    $21, $22, $23, $24,
    $25, $26, $27,
    $28, $29, $30,
    $31, $32, $33, $34, $35,
    $36, $37, $38, $39
)
RETURNING id
`

type InsertUsageRecordParams struct {
	TenantID               int64              `db:"tenant_id" json:"tenant_id"`
	ClaimID                int64              `db:"claim_id" json:"claim_id"`
	APIKeyID               int64              `db:"api_key_id" json:"api_key_id"`
	UserID                 int64              `db:"user_id" json:"user_id"`
	ProviderAccountID      int64              `db:"provider_account_id" json:"provider_account_id"`
	AcquisitionToken       pgtype.UUID        `db:"acquisition_token" json:"acquisition_token"`
	AttemptSeq             int32              `db:"attempt_seq" json:"attempt_seq"`
	TokensInput            int32              `db:"tokens_input" json:"tokens_input"`
	TokensOutput           int32              `db:"tokens_output" json:"tokens_output"`
	CacheCreationTokens    int32              `db:"cache_creation_tokens" json:"cache_creation_tokens"`
	CacheReadTokens        int32              `db:"cache_read_tokens" json:"cache_read_tokens"`
	CacheCreation5mTokens  int32              `db:"cache_creation_5m_tokens" json:"cache_creation_5m_tokens"`
	CacheCreation1hTokens  int32              `db:"cache_creation_1h_tokens" json:"cache_creation_1h_tokens"`
	ImageOutputTokens      int32              `db:"image_output_tokens" json:"image_output_tokens"`
	ActualCost             decimal.Decimal    `db:"actual_cost" json:"actual_cost"`
	InputCost              decimal.Decimal    `db:"input_cost" json:"input_cost"`
	OutputCost             decimal.Decimal    `db:"output_cost" json:"output_cost"`
	CacheCreationCost      decimal.Decimal    `db:"cache_creation_cost" json:"cache_creation_cost"`
	CacheReadCost          decimal.Decimal    `db:"cache_read_cost" json:"cache_read_cost"`
	ImageOutputCost        decimal.Decimal    `db:"image_output_cost" json:"image_output_cost"`
	EndClass               string             `db:"end_class" json:"end_class"`
	UsageSource            string             `db:"usage_source" json:"usage_source"`
	ConfidenceScore        pgtype.Numeric     `db:"confidence_score" json:"confidence_score"`
	PendingReconciliation  bool               `db:"pending_reconciliation" json:"pending_reconciliation"`
	StreamState            int16              `db:"stream_state" json:"stream_state"`
	DeliveredTokenCount    int64              `db:"delivered_token_count" json:"delivered_token_count"`
	StreamTerminatedReason *string            `db:"stream_terminated_reason" json:"stream_terminated_reason"`
	DrainOutcome           *string            `db:"drain_outcome" json:"drain_outcome"`
	RoutingReason          []byte             `db:"routing_reason" json:"routing_reason"`
	ProtocolLoss           []byte             `db:"protocol_loss" json:"protocol_loss"`
	RequestedAt            pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	UpstreamRequestAt      pgtype.Timestamptz `db:"upstream_request_at" json:"upstream_request_at"`
	FirstByteAt            pgtype.Timestamptz `db:"first_byte_at" json:"first_byte_at"`
	FirstEventAt           pgtype.Timestamptz `db:"first_event_at" json:"first_event_at"`
	LastEventAt            pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	RequestedModel         string             `db:"requested_model" json:"requested_model"`
	UpstreamModel          *string            `db:"upstream_model" json:"upstream_model"`
	Stream                 bool               `db:"stream" json:"stream"`
	SnapshotVersion        *string            `db:"snapshot_version" json:"snapshot_version"`
}

// Spec §Tx2 step 12: write Usage Record into the same Tx as everything else.
// Slice 2 (N+5b 2026-05-01): added snapshot_version (column from migration
// 0008). Format documented there as "registry:<tid>:<v>;router:<rv>".
func (q *Queries) InsertUsageRecord(ctx context.Context, arg InsertUsageRecordParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUsageRecord,
		arg.TenantID,
		arg.ClaimID,
		arg.APIKeyID,
		arg.UserID,
		arg.ProviderAccountID,
		arg.AcquisitionToken,
		arg.AttemptSeq,
		arg.TokensInput,
		arg.TokensOutput,
		arg.CacheCreationTokens,
		arg.CacheReadTokens,
		arg.CacheCreation5mTokens,
		arg.CacheCreation1hTokens,
		arg.ImageOutputTokens,
		arg.ActualCost,
		arg.InputCost,
		arg.OutputCost,
		arg.CacheCreationCost,
		arg.CacheReadCost,
		arg.ImageOutputCost,
		arg.EndClass,
		arg.UsageSource,
		arg.ConfidenceScore,
		arg.PendingReconciliation,
		arg.StreamState,
		arg.DeliveredTokenCount,
		arg.StreamTerminatedReason,
		arg.DrainOutcome,
		arg.RoutingReason,
		arg.ProtocolLoss,
		arg.RequestedAt,
		arg.UpstreamRequestAt,
		arg.FirstByteAt,
		arg.FirstEventAt,
		arg.LastEventAt,
		arg.RequestedModel,
		arg.UpstreamModel,
		arg.Stream,
		arg.SnapshotVersion,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const releaseSlotAndDecrementInFlight = `-- name: ReleaseSlotAndDecrementInFlight :execrows
WITH released AS (
    UPDATE pool_slot_acquisitions
    SET status = 'released_success',
        released_at = NOW(),
        release_reason = $2
    WHERE acquisition_token = $1 AND status = 'acquired'
    RETURNING provider_account_id
)
UPDATE provider_accounts pa
SET in_flight_count = pa.in_flight_count - 1
FROM released r
WHERE r.provider_account_id = pa.id AND pa.in_flight_count > 0
`

type ReleaseSlotAndDecrementInFlightParams struct {
	AcquisitionToken uuid.UUID `db:"acquisition_token" json:"acquisition_token"`
	ReleaseReason    *string   `db:"release_reason" json:"release_reason"`
}

// Spec §Tx2 step 14: TRULY IDEMPOTENT in_flight decrement (codex P1 review fix).
// Atomic CTE: flip pool_slot_acquisitions.status acquired -> released_success
// AND ONLY THEN decrement provider_accounts.in_flight_count. If the token is
// replayed (e.g. retry storm), the inner UPDATE returns 0 rows because status
// is no longer 'acquired'; the outer UPDATE no-ops; in_flight_count stays correct.
// $2 = release_reason text ('settled_committed' / 'settled_aborted' / etc.)
func (q *Queries) ReleaseSlotAndDecrementInFlight(ctx context.Context, arg ReleaseSlotAndDecrementInFlightParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseSlotAndDecrementInFlight, arg.AcquisitionToken, arg.ReleaseReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateClaimAbortedWithReason = `-- name: UpdateClaimAbortedWithReason :execrows
UPDATE billing_ledger_claims
SET status = 'aborted', aborted_reason = $3, settled_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND status = 'reserving'
`

type UpdateClaimAbortedWithReasonParams struct {
	ID            int64   `db:"id" json:"id"`
	TenantID      int64   `db:"tenant_id" json:"tenant_id"`
	AbortedReason *string `db:"aborted_reason" json:"aborted_reason"`
}

// Abort path: claim status reserving → aborted; usage_record/billing_event
// still written (with zero cost) for audit completeness.
// Tenant-scoped to prevent cross-tenant abort via stale claim id.
func (q *Queries) UpdateClaimAbortedWithReason(ctx context.Context, arg UpdateClaimAbortedWithReasonParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateClaimAbortedWithReason, arg.ID, arg.TenantID, arg.AbortedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateClaimCommitted = `-- name: UpdateClaimCommitted :execrows
UPDATE billing_ledger_claims
SET status = 'committed', actual_cost = $2, settled_at = NOW()
WHERE id = $1 AND status = 'reserving'
`

type UpdateClaimCommittedParams struct {
	ID         int64               `db:"id" json:"id"`
	ActualCost decimal.NullDecimal `db:"actual_cost" json:"actual_cost"`
}

// Spec §Tx2 step 15: claim status reserving → committed.
func (q *Queries) UpdateClaimCommitted(ctx context.Context, arg UpdateClaimCommittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateClaimCommitted, arg.ID, arg.ActualCost)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
