// Package db is a Phase 3/4-bridge stub.
//
// In production, this package is GENERATED by sqlc from sql/queries/*.sql
// (see sqlc.yaml; run `make generate` once sqlc binary is installed).
//
// This file is a hand-written placeholder so the rest of the codebase
// compiles before Phase 4 sqlc setup completes. Phase 4 implementer-lane
// REPLACES this file with sqlc output (or removes this file and lets
// `make generate` produce internal/db/queries.sql.go etc).
//
// Per .gitignore: internal/db/ is normally untracked because it's generated.
// We track THIS one stub file with the marker `db_stub.go` rule below to
// keep the codebase compiling on a fresh clone before sqlc runs.
package db

import (
	"context"
	"time"
)

// Queries is the sqlc-generated query handle. In the real (generated) version
// it carries a *pgx.Conn or pgxpool. Phase 4 replaces this stub.
type Queries struct{}

// New returns a fresh Queries handle. Replaced by sqlc-generated code.
func New(_ any) *Queries {
	return &Queries{}
}

// ----------------------------------------------------------------------------
// auth_storm.sql query stubs
// ----------------------------------------------------------------------------

// GetOrCreateAccountStormBudgetParams mirrors the sqlc-generated params.
type GetOrCreateAccountStormBudgetParams struct {
	TenantID          int64
	ProviderAccountID int64
}

// OAuthStormBudget is the row shape for the oauth_storm_budget table.
type OAuthStormBudget struct {
	ID                       int64
	TenantID                 int64
	ScopeType                string
	ProviderAccountID        *int64
	ProviderCode             *string
	OAuthEndpointFingerprint *string
	CapConcurrentRefreshes   int32
	CapRefreshesPerMinute    int32
	CurrentInFlight          int32
	RefreshesInWindow        int32
	WindowStart              time.Time
	CircuitOpenUntil         *time.Time
	LastUpdatedAt            time.Time
}

// GetOrCreateAccountStormBudget is a stub. Phase 4 sqlc-generated.
func (q *Queries) GetOrCreateAccountStormBudget(_ context.Context, _ GetOrCreateAccountStormBudgetParams) (OAuthStormBudget, error) {
	return OAuthStormBudget{}, nil
}

// TryAcquireAccountStormSlot is a stub. Phase 4 sqlc-generated.
func (q *Queries) TryAcquireAccountStormSlot(_ context.Context, _ int64) (int32, error) {
	return 0, nil
}

// ReleaseAccountStormSlot is a stub. Phase 4 sqlc-generated.
func (q *Queries) ReleaseAccountStormSlot(_ context.Context, _ int64) error {
	return nil
}

// ----------------------------------------------------------------------------
// Phase 4 implementer-lane: DELETE THIS FILE AND RUN `make generate`
// ----------------------------------------------------------------------------
