// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// L0 minimum (2026-04-30 N+4a) inbound bearer storage. key_hash is bcrypt; key_prefix indexed for tenant-scoped lookup. CMB-5: no plaintext bearer EVER persisted; CMB-7: last_used_at NOT updated synchronously in N+4.
type ApiKey struct {
	ID       int64  `db:"id" json:"id"`
	TenantID int64  `db:"tenant_id" json:"tenant_id"`
	UserID   int64  `db:"user_id" json:"user_id"`
	Name     string `db:"name" json:"name"`
	// bcrypt hash of the full plaintext bearer (cost=10). NEVER append to logs; CMB-5.
	KeyHash string `db:"key_hash" json:"key_hash"`
	// First 16 chars of plaintext bearer (incl. "hk_live_" or "hk_test_" namespace prefix). Indexed for hot-path; insufficient on its own to authenticate.
	KeyPrefix     string             `db:"key_prefix" json:"key_prefix"`
	Status        string             `db:"status" json:"status"`
	ExpiresAt     pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt    pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	RevokedAt     pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokedReason *string            `db:"revoked_reason" json:"revoked_reason"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// F-OBS-001 H8: audit-grade event row in Tx2; survives Usage Record async failure. Append-only.
type BillingEvent struct {
	ID               int64              `db:"id" json:"id"`
	TenantID         int64              `db:"tenant_id" json:"tenant_id"`
	ClaimID          int64              `db:"claim_id" json:"claim_id"`
	EventType        string             `db:"event_type" json:"event_type"`
	ActualCost       decimal.Decimal    `db:"actual_cost" json:"actual_cost"`
	ActualCostSigned decimal.Decimal    `db:"actual_cost_signed" json:"actual_cost_signed"`
	EndClass         *string            `db:"end_class" json:"end_class"`
	UsageSource      *string            `db:"usage_source" json:"usage_source"`
	Fingerprint      string             `db:"fingerprint" json:"fingerprint"`
	OccurredAt       pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

// F-OBS-001 + docs/19 §Invariant 4: append-only paired adjustments. Original claim never mutated; corrections via signed delta rows.
type BillingLedgerAdjustment struct {
	ID                    int64              `db:"id" json:"id"`
	TenantID              int64              `db:"tenant_id" json:"tenant_id"`
	OriginalClaimID       int64              `db:"original_claim_id" json:"original_claim_id"`
	AdjustmentType        string             `db:"adjustment_type" json:"adjustment_type"`
	CostDelta             pgtype.Numeric     `db:"cost_delta" json:"cost_delta"`
	Reason                string             `db:"reason" json:"reason"`
	ActorID               *string            `db:"actor_id" json:"actor_id"`
	ReconciliationEventID *int64             `db:"reconciliation_event_id" json:"reconciliation_event_id"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Retired claim fingerprints (replay protection). Sub2API S3 archive pattern.
type BillingLedgerArchive struct {
	ID                 int64              `db:"id" json:"id"`
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	IdempotencyKey     string             `db:"idempotency_key" json:"idempotency_key"`
	RequestFingerprint string             `db:"request_fingerprint" json:"request_fingerprint"`
	APIKeyID           int64              `db:"api_key_id" json:"api_key_id"`
	ArchivedAt         pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
}

// F-OBS-001 Tx1/Tx2 claim row. Money-grade source of truth. Once status=committed, immutable except for downstream paired adjustments.
type BillingLedgerClaim struct {
	ID                   int64  `db:"id" json:"id"`
	TenantID             int64  `db:"tenant_id" json:"tenant_id"`
	IdempotencyKey       string `db:"idempotency_key" json:"idempotency_key"`
	RequestFingerprint   string `db:"request_fingerprint" json:"request_fingerprint"`
	APIKeyID             int64  `db:"api_key_id" json:"api_key_id"`
	UserID               int64  `db:"user_id" json:"user_id"`
	LogicalRequestID     string `db:"logical_request_id" json:"logical_request_id"`
	EndpointFamily       string `db:"endpoint_family" json:"endpoint_family"`
	RequestedModel       string `db:"requested_model" json:"requested_model"`
	PoolingGroupID       *int64 `db:"pooling_group_id" json:"pooling_group_id"`
	BillingPolicyVersion string `db:"billing_policy_version" json:"billing_policy_version"`
	RequestClass         string `db:"request_class" json:"request_class"`
	// Pattern B placeholder per F-POOL-001 §6. NULL during reserving; populated by Pool acquire writeback in same Tx1 commit.
	ProviderAccountID *int64              `db:"provider_account_id" json:"provider_account_id"`
	AcquisitionToken  uuid.UUID           `db:"acquisition_token" json:"acquisition_token"`
	AttemptSeq        int32               `db:"attempt_seq" json:"attempt_seq"`
	PredictedCost     decimal.Decimal     `db:"predicted_cost" json:"predicted_cost"`
	ActualCost        decimal.NullDecimal `db:"actual_cost" json:"actual_cost"`
	CurrencyCode      string              `db:"currency_code" json:"currency_code"`
	Status            string              `db:"status" json:"status"`
	AbortedReason     *string             `db:"aborted_reason" json:"aborted_reason"`
	ReservedAt        pgtype.Timestamptz  `db:"reserved_at" json:"reserved_at"`
	SettledAt         pgtype.Timestamptz  `db:"settled_at" json:"settled_at"`
	LeaseExpiresAt    pgtype.Timestamptz  `db:"lease_expires_at" json:"lease_expires_at"`
}

// F-BILL-001 framing: versioned pricing context. Reprice operates on stored version, not live config.
type BillingPricingVersion struct {
	ID             int64              `db:"id" json:"id"`
	TenantID       int64              `db:"tenant_id" json:"tenant_id"`
	Version        string             `db:"version" json:"version"`
	PricingData    []byte             `db:"pricing_data" json:"pricing_data"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `db:"effective_to" json:"effective_to"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedByActor *string            `db:"created_by_actor" json:"created_by_actor"`
}

// F-POOL-001: Channel filter inside Pool Group. Failover status codes configurable per Channel (HUAKAI improvement over Sub2API hardcoded list).
type Channel struct {
	ID                  int64              `db:"id" json:"id"`
	TenantID            int64              `db:"tenant_id" json:"tenant_id"`
	PoolGroupID         int64              `db:"pool_group_id" json:"pool_group_id"`
	Name                string             `db:"name" json:"name"`
	FailoverStatusCodes []int32            `db:"failover_status_codes" json:"failover_status_codes"`
	Enabled             bool               `db:"enabled" json:"enabled"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// F-AUTH-005 H6: per-Pool Claude Code mimicry. Constraint: enabled requires legal_review_id (no enabling without legal review document attached).
type MimicryPolicy struct {
	ID                     int64              `db:"id" json:"id"`
	TenantID               int64              `db:"tenant_id" json:"tenant_id"`
	PoolGroupID            int64              `db:"pool_group_id" json:"pool_group_id"`
	Enabled                bool               `db:"enabled" json:"enabled"`
	LegalReviewID          *string            `db:"legal_review_id" json:"legal_review_id"`
	LegalReviewReceivedAt  pgtype.Timestamptz `db:"legal_review_received_at" json:"legal_review_received_at"`
	PolicyVersion          string             `db:"policy_version" json:"policy_version"`
	ApplySystemRewrite     bool               `db:"apply_system_rewrite" json:"apply_system_rewrite"`
	ApplyCacheControlStrip bool               `db:"apply_cache_control_strip" json:"apply_cache_control_strip"`
	ApplyBreakpoints       bool               `db:"apply_breakpoints" json:"apply_breakpoints"`
	ApplyToolObfuscation   bool               `db:"apply_tool_obfuscation" json:"apply_tool_obfuscation"`
	ApplyMetadataUserID    bool               `db:"apply_metadata_user_id" json:"apply_metadata_user_id"`
	EnabledByActor         *string            `db:"enabled_by_actor" json:"enabled_by_actor"`
	EnabledAt              pgtype.Timestamptz `db:"enabled_at" json:"enabled_at"`
}

// Slice 2: canonical model identities. provider-agnostic. tenant_id NULL iff scope=global (D20). pricing_class is a free-form tag; decimal pricing lives in billing (CMB-2 carve-out).
type Model struct {
	ID                      int64              `db:"id" json:"id"`
	TenantID                *int64             `db:"tenant_id" json:"tenant_id"`
	Scope                   string             `db:"scope" json:"scope"`
	CanonicalID             string             `db:"canonical_id" json:"canonical_id"`
	ProtocolFamily          string             `db:"protocol_family" json:"protocol_family"`
	DefaultProviderModelID  string             `db:"default_provider_model_id" json:"default_provider_model_id"`
	DefaultContextWindow    int32              `db:"default_context_window" json:"default_context_window"`
	DefaultRequestTimeoutMs int32              `db:"default_request_timeout_ms" json:"default_request_timeout_ms"`
	PricingClass            string             `db:"pricing_class" json:"pricing_class"`
	ModelOwner              string             `db:"model_owner" json:"model_owner"`
	ModelCreatedAt          pgtype.Timestamptz `db:"model_created_at" json:"model_created_at"`
	Status                  string             `db:"status" json:"status"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Slice 2: (tenant, public_alias) -> model. Lookup is on normalized lower-case alias; display alias preserves operator-set casing for audit. Tenant-disabled rows always block global fallback (explicit deny).
type ModelAlias struct {
	ID                    int64              `db:"id" json:"id"`
	TenantID              *int64             `db:"tenant_id" json:"tenant_id"`
	Scope                 string             `db:"scope" json:"scope"`
	ModelID               int64              `db:"model_id" json:"model_id"`
	PublicAliasNormalized string             `db:"public_alias_normalized" json:"public_alias_normalized"`
	PublicAliasDisplay    string             `db:"public_alias_display" json:"public_alias_display"`
	Status                string             `db:"status" json:"status"`
	DisabledReason        *string            `db:"disabled_reason" json:"disabled_reason"`
	Source                string             `db:"source" json:"source"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Slice 2: ordered tenant-scoped model -> pool_group binding. Reference citations: LiteLLM proxy types (rpm/tpm/max_parallel) + Portkey strategy.mode (selection_mode) + one-api ModelMapping (override) + envoy AIGatewayRouteRuleBackendRef (weight/priority) + LiteLLM typed-fallback (fallback_class). All verified via WebFetch 2026-04-30. Codex N+5a P1: scope column removed — global bindings would cross-tenant-leak pool ids.
type ModelPoolBinding struct {
	ID                      int64              `db:"id" json:"id"`
	TenantID                int64              `db:"tenant_id" json:"tenant_id"`
	ModelID                 int64              `db:"model_id" json:"model_id"`
	PoolGroupID             int64              `db:"pool_group_id" json:"pool_group_id"`
	Priority                int32              `db:"priority" json:"priority"`
	Weight                  int32              `db:"weight" json:"weight"`
	SelectionMode           string             `db:"selection_mode" json:"selection_mode"`
	ProviderModelIDOverride *string            `db:"provider_model_id_override" json:"provider_model_id_override"`
	RpmLimit                *int32             `db:"rpm_limit" json:"rpm_limit"`
	TpmLimit                *int32             `db:"tpm_limit" json:"tpm_limit"`
	MaxParallelRequests     *int32             `db:"max_parallel_requests" json:"max_parallel_requests"`
	FallbackClass           string             `db:"fallback_class" json:"fallback_class"`
	Enabled                 bool               `db:"enabled" json:"enabled"`
	DisabledReason          *string            `db:"disabled_reason" json:"disabled_reason"`
	EffectiveFrom           pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveUntil          pgtype.Timestamptz `db:"effective_until" json:"effective_until"`
	Reason                  string             `db:"reason" json:"reason"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt               pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Slice 2: per-model capability rows. capability_params jsonb supports parameterized capabilities (e.g. reasoning_effort {"levels":["high","medium","low"]} per E-NAI-004).
type ModelRegistryCapability struct {
	ID               int64              `db:"id" json:"id"`
	TenantID         *int64             `db:"tenant_id" json:"tenant_id"`
	Scope            string             `db:"scope" json:"scope"`
	ModelID          int64              `db:"model_id" json:"model_id"`
	Capability       string             `db:"capability" json:"capability"`
	CapabilityValue  *string            `db:"capability_value" json:"capability_value"`
	CapabilityParams []byte             `db:"capability_params" json:"capability_params"`
	Enabled          bool               `db:"enabled" json:"enabled"`
	Source           string             `db:"source" json:"source"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// Slice 2: per-tenant monotonic registry version. Admin writers MUST UPDATE version+1 in the same TX as any model/alias/binding/capability change. ResolveModel reads version into RoutePlan.SnapshotVersion (registry:<tid>:<v>) for audit replay.
type ModelRegistrySnapshot struct {
	TenantID       int64              `db:"tenant_id" json:"tenant_id"`
	Version        int64              `db:"version" json:"version"`
	Reason         *string            `db:"reason" json:"reason"`
	UpdatedByActor *string            `db:"updated_by_actor" json:"updated_by_actor"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Slice 2: opt-in global-catalog inheritance. inherit_global_catalog=true allows ResolveModel to fall through to scope=global rows on tenant miss. Tenant-scoped DISABLED rows always block (explicit deny per integration test #5).
type ModelRegistryTenantPolicy struct {
	TenantID             int64              `db:"tenant_id" json:"tenant_id"`
	InheritGlobalCatalog bool               `db:"inherit_global_catalog" json:"inherit_global_catalog"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	UpdatedByActor       *string            `db:"updated_by_actor" json:"updated_by_actor"`
}

// F-POOL-001 Layer 1: Model Routing config. Empty array = no override; selection skips Layer 1 and goes to Layer 1.5b.
type ModelRoutingOverride struct {
	ID                 int64              `db:"id" json:"id"`
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	PoolGroupID        int64              `db:"pool_group_id" json:"pool_group_id"`
	Model              string             `db:"model" json:"model"`
	ProviderAccountIds []int64            `db:"provider_account_ids" json:"provider_account_ids"`
	Enabled            bool               `db:"enabled" json:"enabled"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// F-AUTH-005: append-only audit trail. Token-leakage-safe (sanitized errors only). Mimicry events recorded with components + policy version.
type OauthRefreshAuditEvent struct {
	ID                       int64              `db:"id" json:"id"`
	TenantID                 int64              `db:"tenant_id" json:"tenant_id"`
	ProviderAccountID        int64              `db:"provider_account_id" json:"provider_account_id"`
	Outcome                  string             `db:"outcome" json:"outcome"`
	StormScope               *string            `db:"storm_scope" json:"storm_scope"`
	OldTokenFingerprint      *string            `db:"old_token_fingerprint" json:"old_token_fingerprint"`
	NewTokenFingerprint      *string            `db:"new_token_fingerprint" json:"new_token_fingerprint"`
	MimicryComponentsApplied []string           `db:"mimicry_components_applied" json:"mimicry_components_applied"`
	MimicryPolicyVersion     *string            `db:"mimicry_policy_version" json:"mimicry_policy_version"`
	RequestID                *string            `db:"request_id" json:"request_id"`
	ClientProtocol           *string            `db:"client_protocol" json:"client_protocol"`
	Model                    *string            `db:"model" json:"model"`
	ErrorClass               *string            `db:"error_class" json:"error_class"`
	ErrorMessageRedacted     *string            `db:"error_message_redacted" json:"error_message_redacted"`
	OccurredAt               pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

// F-AUTH-005 H4: three-scope storm controller state. Per-account, per-(provider, endpoint), and per-tenant global budgets.
type OauthStormBudget struct {
	ID                       int64              `db:"id" json:"id"`
	TenantID                 int64              `db:"tenant_id" json:"tenant_id"`
	ScopeType                string             `db:"scope_type" json:"scope_type"`
	ProviderAccountID        *int64             `db:"provider_account_id" json:"provider_account_id"`
	ProviderCode             *string            `db:"provider_code" json:"provider_code"`
	OauthEndpointFingerprint *string            `db:"oauth_endpoint_fingerprint" json:"oauth_endpoint_fingerprint"`
	CapConcurrentRefreshes   int32              `db:"cap_concurrent_refreshes" json:"cap_concurrent_refreshes"`
	CapRefreshesPerMinute    int32              `db:"cap_refreshes_per_minute" json:"cap_refreshes_per_minute"`
	CurrentInFlight          int32              `db:"current_in_flight" json:"current_in_flight"`
	RefreshesInWindow        int32              `db:"refreshes_in_window" json:"refreshes_in_window"`
	WindowStart              pgtype.Timestamptz `db:"window_start" json:"window_start"`
	CircuitOpenUntil         pgtype.Timestamptz `db:"circuit_open_until" json:"circuit_open_until"`
	LastUpdatedAt            pgtype.Timestamptz `db:"last_updated_at" json:"last_updated_at"`
}

// F-POOL-001 §1: logical capacity grouping; routing policy + Q1..Q4 owner decisions live here.
type PoolGroup struct {
	ID                          int64              `db:"id" json:"id"`
	TenantID                    int64              `db:"tenant_id" json:"tenant_id"`
	Name                        string             `db:"name" json:"name"`
	RoutingPolicyVersion        string             `db:"routing_policy_version" json:"routing_policy_version"`
	TopKDefault                 int32              `db:"top_k_default" json:"top_k_default"`
	CapabilityDefault           string             `db:"capability_default" json:"capability_default"`
	AllowTenantOperatorForce    bool               `db:"allow_tenant_operator_force" json:"allow_tenant_operator_force"`
	AllowLastResort             bool               `db:"allow_last_resort" json:"allow_last_resort"`
	StickyWaitMaxWaiting        int32              `db:"sticky_wait_max_waiting" json:"sticky_wait_max_waiting"`
	FallbackWaitMaxWaiting      int32              `db:"fallback_wait_max_waiting" json:"fallback_wait_max_waiting"`
	StickyWaitTimeoutMs         int32              `db:"sticky_wait_timeout_ms" json:"sticky_wait_timeout_ms"`
	FallbackWaitTimeoutMs       int32              `db:"fallback_wait_timeout_ms" json:"fallback_wait_timeout_ms"`
	ForcedRouteRateLimitPerHour int32              `db:"forced_route_rate_limit_per_hour" json:"forced_route_rate_limit_per_hour"`
	Enabled                     bool               `db:"enabled" json:"enabled"`
	CreatedAt                   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// F-POOL-001 §Audit: structured audit trail. Forced-route + last-resort + safe-equivalent uses captured here.
type PoolRoutingAuditEvent struct {
	ID                int64              `db:"id" json:"id"`
	TenantID          int64              `db:"tenant_id" json:"tenant_id"`
	EventType         string             `db:"event_type" json:"event_type"`
	PoolGroupID       *int64             `db:"pool_group_id" json:"pool_group_id"`
	ProviderAccountID *int64             `db:"provider_account_id" json:"provider_account_id"`
	RequestID         *string            `db:"request_id" json:"request_id"`
	ActorID           *string            `db:"actor_id" json:"actor_id"`
	ActorRole         *string            `db:"actor_role" json:"actor_role"`
	Reason            *string            `db:"reason" json:"reason"`
	Payload           []byte             `db:"payload" json:"payload"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// F-POOL-001 I2: idempotent slot release via UUID token. Orphan sweep finds status=acquired AND lease_expires_at < now().
type PoolSlotAcquisition struct {
	ID                int64              `db:"id" json:"id"`
	TenantID          int64              `db:"tenant_id" json:"tenant_id"`
	ProviderAccountID int64              `db:"provider_account_id" json:"provider_account_id"`
	AcquisitionToken  uuid.UUID          `db:"acquisition_token" json:"acquisition_token"`
	ClaimID           *int64             `db:"claim_id" json:"claim_id"`
	AttemptSeq        int32              `db:"attempt_seq" json:"attempt_seq"`
	HeartbeatAt       pgtype.Timestamptz `db:"heartbeat_at" json:"heartbeat_at"`
	LeaseExpiresAt    pgtype.Timestamptz `db:"lease_expires_at" json:"lease_expires_at"`
	Status            string             `db:"status" json:"status"`
	ReleasedAt        pgtype.Timestamptz `db:"released_at" json:"released_at"`
	ReleaseReason     *string            `db:"release_reason" json:"release_reason"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// F-PROTO-002 §4: per-(client × upstream × feature) capability verdict. Operator UI source. Tooling generates "supported features" docs.
type ProtocolCapabilityMatrix struct {
	ID                  int64              `db:"id" json:"id"`
	TenantID            int64              `db:"tenant_id" json:"tenant_id"`
	ClientProtocol      string             `db:"client_protocol" json:"client_protocol"`
	UpstreamProtocol    string             `db:"upstream_protocol" json:"upstream_protocol"`
	FeatureName         string             `db:"feature_name" json:"feature_name"`
	Verdict             string             `db:"verdict" json:"verdict"`
	LossNote            *string            `db:"loss_note" json:"loss_note"`
	VerifyingTestID     *string            `db:"verifying_test_id" json:"verifying_test_id"`
	MatrixPolicyVersion string             `db:"matrix_policy_version" json:"matrix_policy_version"`
	LastVerifiedAt      pgtype.Timestamptz `db:"last_verified_at" json:"last_verified_at"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// F-PROTO-002: versioned policy. Usage Records reference the version active at translation time for replay correctness.
type ProtocolPolicyVersion struct {
	ID             int64              `db:"id" json:"id"`
	TenantID       int64              `db:"tenant_id" json:"tenant_id"`
	Version        string             `db:"version" json:"version"`
	PolicyData     []byte             `db:"policy_data" json:"policy_data"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `db:"effective_to" json:"effective_to"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedByActor *string            `db:"created_by_actor" json:"created_by_actor"`
}

// Upstream LLM provider catalog. Code drives upstream-protocol adapter choice (F-PROTO-001).
type Provider struct {
	ID               int64              `db:"id" json:"id"`
	TenantID         int64              `db:"tenant_id" json:"tenant_id"`
	Code             string             `db:"code" json:"code"`
	DisplayName      string             `db:"display_name" json:"display_name"`
	UpstreamProtocol string             `db:"upstream_protocol" json:"upstream_protocol"`
	Enabled          bool               `db:"enabled" json:"enabled"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// F-POOL-001: upstream credential + capacity unit. Selected by 5-layer algorithm. Credentials JSONB redacted at rest.
type ProviderAccount struct {
	ID               int64              `db:"id" json:"id"`
	TenantID         int64              `db:"tenant_id" json:"tenant_id"`
	ProviderID       int64              `db:"provider_id" json:"provider_id"`
	ChannelID        int64              `db:"channel_id" json:"channel_id"`
	Name             string             `db:"name" json:"name"`
	AccountType      string             `db:"account_type" json:"account_type"`
	Enabled          bool               `db:"enabled" json:"enabled"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	HealthState      string             `db:"health_state" json:"health_state"`
	HealthStateUntil pgtype.Timestamptz `db:"health_state_until" json:"health_state_until"`
	CredentialState  string             `db:"credential_state" json:"credential_state"`
	Credentials      []byte             `db:"credentials" json:"credentials"`
	CapConcurrency   int32              `db:"cap_concurrency" json:"cap_concurrency"`
	// Atomic counter for slot acquisition; row-locked via SELECT FOR UPDATE during F-POOL-001 §Phase C.
	InFlightCount          int32              `db:"in_flight_count" json:"in_flight_count"`
	CapQueueSticky         int32              `db:"cap_queue_sticky" json:"cap_queue_sticky"`
	CapQueueFallback       int32              `db:"cap_queue_fallback" json:"cap_queue_fallback"`
	QueueDepth             int32              `db:"queue_depth" json:"queue_depth"`
	Priority               int32              `db:"priority" json:"priority"`
	LastDispatchAt         pgtype.Timestamptz `db:"last_dispatch_at" json:"last_dispatch_at"`
	ModelAllowList         []string           `db:"model_allow_list" json:"model_allow_list"`
	CapabilityFlags        []string           `db:"capability_flags" json:"capability_flags"`
	CapQuotaTotal          pgtype.Numeric     `db:"cap_quota_total" json:"cap_quota_total"`
	QuotaUsedTotal         pgtype.Numeric     `db:"quota_used_total" json:"quota_used_total"`
	CapQuotaDaily          pgtype.Numeric     `db:"cap_quota_daily" json:"cap_quota_daily"`
	QuotaUsedDaily         pgtype.Numeric     `db:"quota_used_daily" json:"quota_used_daily"`
	QuotaWindowDailyStart  pgtype.Timestamptz `db:"quota_window_daily_start" json:"quota_window_daily_start"`
	CapQuotaWeekly         pgtype.Numeric     `db:"cap_quota_weekly" json:"cap_quota_weekly"`
	QuotaUsedWeekly        pgtype.Numeric     `db:"quota_used_weekly" json:"quota_used_weekly"`
	QuotaWindowWeeklyStart pgtype.Timestamptz `db:"quota_window_weekly_start" json:"quota_window_weekly_start"`
	QuotaStatus            string             `db:"quota_status" json:"quota_status"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt              pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedByActor         *string            `db:"created_by_actor" json:"created_by_actor"`
	LastModifiedByActor    *string            `db:"last_modified_by_actor" json:"last_modified_by_actor"`
	// F-RATE-001: when current rate-limit state began. NULL = not rate-limited.
	RateLimitedAt pgtype.Timestamptz `db:"rate_limited_at" json:"rate_limited_at"`
	// F-RATE-001: when account auto-recovers from rate-limit. now() < reset_at = currently rate-limited.
	RateLimitResetAt pgtype.Timestamptz `db:"rate_limit_reset_at" json:"rate_limit_reset_at"`
	// F-RATE-001 §1.4: structured reason for current rate-limit (5h/7d/both/RPM/TPM).
	RateLimitReason *string `db:"rate_limit_reason" json:"rate_limit_reason"`
	// F-RATE-001 §Phase D: 529 overload cooldown end. Distinct from rate-limit.
	OverloadUntil pgtype.Timestamptz `db:"overload_until" json:"overload_until"`
	// F-RATE-001 §Phase E: temp-unsched end (OAuth refresh window, custom rule match, or refresh-retry-exhaustion).
	TempUnschedulableUntil     pgtype.Timestamptz `db:"temp_unschedulable_until" json:"temp_unschedulable_until"`
	TempUnschedulableReason    *string            `db:"temp_unschedulable_reason" json:"temp_unschedulable_reason"`
	TempUnschedulableRuleIndex *int32             `db:"temp_unschedulable_rule_index" json:"temp_unschedulable_rule_index"`
	SessionWindow5hStart       pgtype.Timestamptz `db:"session_window_5h_start" json:"session_window_5h_start"`
	SessionWindow5hEnd         pgtype.Timestamptz `db:"session_window_5h_end" json:"session_window_5h_end"`
	SessionWindow5hStatus      *string            `db:"session_window_5h_status" json:"session_window_5h_status"`
	// F-RATE-001 Phase B handle403: OpenAI 403 counter; permanent disable at >=3 within 180-min window.
	OpenAI403Counter     int32              `db:"openai_403_counter" json:"openai_403_counter"`
	Openai403WindowStart pgtype.Timestamptz `db:"openai_403_window_start" json:"openai_403_window_start"`
	// F-RATE-001 Phase A: when true, only listed status codes trigger state change.
	CustomErrorCodesEnabled bool    `db:"custom_error_codes_enabled" json:"custom_error_codes_enabled"`
	CustomErrorCodes        []int32 `db:"custom_error_codes" json:"custom_error_codes"`
	// F-RATE-001 Phase A: when true, uncustomized errors do NOT mutate local state.
	PoolMode                 bool `db:"pool_mode" json:"pool_mode"`
	TempUnschedulableEnabled bool `db:"temp_unschedulable_enabled" json:"temp_unschedulable_enabled"`
	// F-RATE-001 §1.6: per-account match rules; jsonb array of { error_code, keywords[], duration_minutes, description }.
	TempUnschedulableRules []byte `db:"temp_unschedulable_rules" json:"temp_unschedulable_rules"`
	// F-RATE-001 §1.8: Antigravity-specific per-model cooldown map.
	ModelRateLimits []byte `db:"model_rate_limits" json:"model_rate_limits"`
	// HUAKAI bound: max N OAuth refresh attempts per window before permanent disable.
	RefreshAttemptCount       int32              `db:"refresh_attempt_count" json:"refresh_attempt_count"`
	RefreshAttemptWindowStart pgtype.Timestamptz `db:"refresh_attempt_window_start" json:"refresh_attempt_window_start"`
	// F-AUTH-005 invariant A8: CAS guard for credential persistence. Increments on every credential write.
	TokenVersion int32 `db:"token_version" json:"token_version"`
	// F-AUTH-005 H3: SHA(refresh_token + tenant_id). Used for diagnosing refresh races without leaking tokens. Never plaintext.
	RefreshTokenFingerprint *string            `db:"refresh_token_fingerprint" json:"refresh_token_fingerprint"`
	LastRefreshAt           pgtype.Timestamptz `db:"last_refresh_at" json:"last_refresh_at"`
	LastRefreshOutcome      *string            `db:"last_refresh_outcome" json:"last_refresh_outcome"`
	// F-AUTH-005 H4 provider-endpoint-scope: circuit-breaker state for upstream OAuth endpoint.
	OAuthEndpointHealth string `db:"oauth_endpoint_health" json:"oauth_endpoint_health"`
}

// F-RATE-001: append-only audit trail for state mutations. Operator dashboard query source.
type RateLimitAuditEvent struct {
	ID                 int64              `db:"id" json:"id"`
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	ProviderAccountID  int64              `db:"provider_account_id" json:"provider_account_id"`
	EventType          string             `db:"event_type" json:"event_type"`
	RateLimitReason    *string            `db:"rate_limit_reason" json:"rate_limit_reason"`
	UpstreamStatusCode *int32             `db:"upstream_status_code" json:"upstream_status_code"`
	UpstreamRequestID  *string            `db:"upstream_request_id" json:"upstream_request_id"`
	Payload            []byte             `db:"payload" json:"payload"`
	ActorID            *string            `db:"actor_id" json:"actor_id"`
	OccurredAt         pgtype.Timestamptz `db:"occurred_at" json:"occurred_at"`
}

// F-POOL-001 §5.2: routing rule. Per-Route override of Pool defaults per Q2. Optional score weights default 0 (compatibility mode).
type Route struct {
	ID                       int64              `db:"id" json:"id"`
	TenantID                 int64              `db:"tenant_id" json:"tenant_id"`
	Name                     string             `db:"name" json:"name"`
	UserGroupMatch           string             `db:"user_group_match" json:"user_group_match"`
	ModelPatternMatch        string             `db:"model_pattern_match" json:"model_pattern_match"`
	PoolGroupID              int64              `db:"pool_group_id" json:"pool_group_id"`
	StickyWaitMaxOverride    *int32             `db:"sticky_wait_max_override" json:"sticky_wait_max_override"`
	FallbackWaitMaxOverride  *int32             `db:"fallback_wait_max_override" json:"fallback_wait_max_override"`
	CapabilityPolicyOverride *string            `db:"capability_policy_override" json:"capability_policy_override"`
	TopKOverride             *int32             `db:"top_k_override" json:"top_k_override"`
	WeightPriority           int32              `db:"weight_priority" json:"weight_priority"`
	WeightLoadRate           int32              `db:"weight_load_rate" json:"weight_load_rate"`
	WeightLastUsed           int32              `db:"weight_last_used" json:"weight_last_used"`
	WeightRecentErrorRate    int32              `db:"weight_recent_error_rate" json:"weight_recent_error_rate"`
	WeightRecentLatency      int32              `db:"weight_recent_latency" json:"weight_recent_latency"`
	WeightQuotaHeadroom      int32              `db:"weight_quota_headroom" json:"weight_quota_headroom"`
	WeightFairnessDebt       int32              `db:"weight_fairness_debt" json:"weight_fairness_debt"`
	WeightSnapshotFreshness  int32              `db:"weight_snapshot_freshness" json:"weight_snapshot_freshness"`
	MatchPriority            int32              `db:"match_priority" json:"match_priority"`
	Enabled                  bool               `db:"enabled" json:"enabled"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	// F-GW-002 timeout axis 1 (TCP connect).
	ConnectTimeoutMs int32 `db:"connect_timeout_ms" json:"connect_timeout_ms"`
	// F-GW-002 timeout axis 2 (TLS).
	TlsHandshakeTimeoutMs int32 `db:"tls_handshake_timeout_ms" json:"tls_handshake_timeout_ms"`
	// F-GW-002 timeout axis 3 (request body write).
	RequestWriteTimeoutMs int32 `db:"request_write_timeout_ms" json:"request_write_timeout_ms"`
	// F-GW-002 timeout axis 4 (upstream response headers).
	ResponseHeaderTimeoutMs int32 `db:"response_header_timeout_ms" json:"response_header_timeout_ms"`
	// F-GW-002 timeout axis 5 (first event after headers).
	FirstTokenTimeoutMs int32 `db:"first_token_timeout_ms" json:"first_token_timeout_ms"`
	// F-GW-002 timeout axis 6 (gap between events).
	InterEventTimeoutMs int32 `db:"inter_event_timeout_ms" json:"inter_event_timeout_ms"`
	// F-GW-002 timeout axis 7 (whole stream cap).
	TotalStreamTimeoutMs int32 `db:"total_stream_timeout_ms" json:"total_stream_timeout_ms"`
	// F-GW-002 timeout axis 8 (flush to client).
	DownstreamWriteTimeoutMs int32 `db:"downstream_write_timeout_ms" json:"downstream_write_timeout_ms"`
	// F-GW-002 §5.1: bounded scanner buffer; 1 MiB default vs upstream 500 MiB; max 64 MiB cap.
	ScannerBufferMaxBytes int32 `db:"scanner_buffer_max_bytes" json:"scanner_buffer_max_bytes"`
	// F-GW-002 §Phase C-bis: drain time budget on client disconnect.
	DrainMaxSeconds int32 `db:"drain_max_seconds" json:"drain_max_seconds"`
	// F-GW-002 §Phase C-bis: drain byte budget on client disconnect.
	DrainMaxBytes int32 `db:"drain_max_bytes" json:"drain_max_bytes"`
	// F-GW-002 §Phase C-bis: drain cost budget on client disconnect.
	DrainMaxEstimatedCostUsd pgtype.Numeric `db:"drain_max_estimated_cost_usd" json:"drain_max_estimated_cost_usd"`
	// F-GW-002 H6: default off; client may opt in via Idempotent-Stream-Replay header.
	MidStreamFailoverDefault bool `db:"mid_stream_failover_default" json:"mid_stream_failover_default"`
	TokenizerFallbackEnabled bool `db:"tokenizer_fallback_enabled" json:"tokenizer_fallback_enabled"`
}

// Transactional outbox for cache invalidation. Consumer reads ORDER BY created_at; idempotent invalidation. Lag > threshold triggers alert (F-OBS-001 O5).
type SchedulerOutbox struct {
	ID                       int64              `db:"id" json:"id"`
	TenantID                 int64              `db:"tenant_id" json:"tenant_id"`
	EventType                string             `db:"event_type" json:"event_type"`
	PoolGroupID              *int64             `db:"pool_group_id" json:"pool_group_id"`
	ProviderAccountID        *int64             `db:"provider_account_id" json:"provider_account_id"`
	Payload                  []byte             `db:"payload" json:"payload"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ConsumedAt               pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
	ConsumerID               *string            `db:"consumer_id" json:"consumer_id"`
	LagAlertThresholdSeconds int32              `db:"lag_alert_threshold_seconds" json:"lag_alert_threshold_seconds"`
}

// F-POOL-001 Layer 1.5/1.5b: sticky session affinity. session_hash derived from cache_control / metadata.user_id / SessionContext per Phase A.
type StickyBinding struct {
	ID                int64              `db:"id" json:"id"`
	TenantID          int64              `db:"tenant_id" json:"tenant_id"`
	SessionHash       string             `db:"session_hash" json:"session_hash"`
	Model             string             `db:"model" json:"model"`
	ProviderAccountID int64              `db:"provider_account_id" json:"provider_account_id"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	RefreshedAt       pgtype.Timestamptz `db:"refreshed_at" json:"refreshed_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Multi-tenant scope; MVP uses single default tenant per DR-001.
type Tenant struct {
	ID        int64              `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Status    string             `db:"status" json:"status"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}

// F-OBS-001: immutable usage record (per docs/19 §Invariant 4). Hot store. Reconciliation appends rows in usage_record_reconciliation_events; original is never mutated.
type UsageRecord struct {
	ID                    int64              `db:"id" json:"id"`
	TenantID              int64              `db:"tenant_id" json:"tenant_id"`
	ClaimID               int64              `db:"claim_id" json:"claim_id"`
	APIKeyID              int64              `db:"api_key_id" json:"api_key_id"`
	UserID                int64              `db:"user_id" json:"user_id"`
	ProviderAccountID     int64              `db:"provider_account_id" json:"provider_account_id"`
	AcquisitionToken      pgtype.UUID        `db:"acquisition_token" json:"acquisition_token"`
	AttemptSeq            int32              `db:"attempt_seq" json:"attempt_seq"`
	TokensInput           int32              `db:"tokens_input" json:"tokens_input"`
	TokensOutput          int32              `db:"tokens_output" json:"tokens_output"`
	CacheCreationTokens   int32              `db:"cache_creation_tokens" json:"cache_creation_tokens"`
	CacheReadTokens       int32              `db:"cache_read_tokens" json:"cache_read_tokens"`
	CacheCreation5mTokens int32              `db:"cache_creation_5m_tokens" json:"cache_creation_5m_tokens"`
	CacheCreation1hTokens int32              `db:"cache_creation_1h_tokens" json:"cache_creation_1h_tokens"`
	ImageOutputTokens     int32              `db:"image_output_tokens" json:"image_output_tokens"`
	ActualCost            decimal.Decimal    `db:"actual_cost" json:"actual_cost"`
	InputCost             decimal.Decimal    `db:"input_cost" json:"input_cost"`
	OutputCost            decimal.Decimal    `db:"output_cost" json:"output_cost"`
	CacheCreationCost     decimal.Decimal    `db:"cache_creation_cost" json:"cache_creation_cost"`
	CacheReadCost         decimal.Decimal    `db:"cache_read_cost" json:"cache_read_cost"`
	ImageOutputCost       decimal.Decimal    `db:"image_output_cost" json:"image_output_cost"`
	EndClass              string             `db:"end_class" json:"end_class"`
	UsageSource           string             `db:"usage_source" json:"usage_source"`
	ConfidenceScore       pgtype.Numeric     `db:"confidence_score" json:"confidence_score"`
	PendingReconciliation bool               `db:"pending_reconciliation" json:"pending_reconciliation"`
	DrainOutcome          *string            `db:"drain_outcome" json:"drain_outcome"`
	RoutingReason         []byte             `db:"routing_reason" json:"routing_reason"`
	ProtocolLoss          []byte             `db:"protocol_loss" json:"protocol_loss"`
	RequestedAt           pgtype.Timestamptz `db:"requested_at" json:"requested_at"`
	UpstreamRequestAt     pgtype.Timestamptz `db:"upstream_request_at" json:"upstream_request_at"`
	FirstByteAt           pgtype.Timestamptz `db:"first_byte_at" json:"first_byte_at"`
	FirstEventAt          pgtype.Timestamptz `db:"first_event_at" json:"first_event_at"`
	LastEventAt           pgtype.Timestamptz `db:"last_event_at" json:"last_event_at"`
	SettledAt             pgtype.Timestamptz `db:"settled_at" json:"settled_at"`
	RequestedModel        string             `db:"requested_model" json:"requested_model"`
	UpstreamModel         *string            `db:"upstream_model" json:"upstream_model"`
	Stream                bool               `db:"stream" json:"stream"`
	// Slice 2: registry+router snapshot stamp at billing time. Format registry:<tid>:<v>;router:<rv>. Audit replay reads this to re-derive what routing config was active.
	SnapshotVersion *string `db:"snapshot_version" json:"snapshot_version"`
}

// F-OBS-001 H10: durable DLQ for Usage Record write failures. Operator-replayable; auto-replay cadence configurable.
type UsageRecordDlq struct {
	ID                  int64              `db:"id" json:"id"`
	TenantID            int64              `db:"tenant_id" json:"tenant_id"`
	ClaimID             int64              `db:"claim_id" json:"claim_id"`
	Payload             []byte             `db:"payload" json:"payload"`
	FailureReason       string             `db:"failure_reason" json:"failure_reason"`
	FailureAt           pgtype.Timestamptz `db:"failure_at" json:"failure_at"`
	ReplayAttempts      int32              `db:"replay_attempts" json:"replay_attempts"`
	LastReplayAt        pgtype.Timestamptz `db:"last_replay_at" json:"last_replay_at"`
	ReplayedAt          pgtype.Timestamptz `db:"replayed_at" json:"replayed_at"`
	ReplayFailureReason *string            `db:"replay_failure_reason" json:"replay_failure_reason"`
}

// F-OBS-001: append-only reconciliation events. Linked to immutable original Usage Record. Per-record reconciliation may produce paired billing_ledger_adjustments.
type UsageRecordReconciliationEvent struct {
	ID                        int64              `db:"id" json:"id"`
	TenantID                  int64              `db:"tenant_id" json:"tenant_id"`
	OriginalUsageRecordID     int64              `db:"original_usage_record_id" json:"original_usage_record_id"`
	AuthoritativeTokensInput  int32              `db:"authoritative_tokens_input" json:"authoritative_tokens_input"`
	AuthoritativeTokensOutput int32              `db:"authoritative_tokens_output" json:"authoritative_tokens_output"`
	AuthoritativeCost         pgtype.Numeric     `db:"authoritative_cost" json:"authoritative_cost"`
	CostDelta                 pgtype.Numeric     `db:"cost_delta" json:"cost_delta"`
	ReconciliationSource      string             `db:"reconciliation_source" json:"reconciliation_source"`
	ReconciledAt              pgtype.Timestamptz `db:"reconciled_at" json:"reconciled_at"`
}

// L0 minimum (2026-04-30 N+4a) end-user identity. No password column — HUAKAI authenticates via api_keys.
type User struct {
	ID          int64              `db:"id" json:"id"`
	TenantID    int64              `db:"tenant_id" json:"tenant_id"`
	Email       *string            `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	Status      string             `db:"status" json:"status"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
