// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pool_accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementInFlightCount = `-- name: DecrementInFlightCount :exec
UPDATE provider_accounts
SET
    in_flight_count = GREATEST(in_flight_count - 1, 0),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DecrementInFlightCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementInFlightCount, id)
	return err
}

const getAccountForRevalidation = `-- name: GetAccountForRevalidation :one
SELECT
    id,
    tenant_id,
    provider_id,
    channel_id,
    name,
    account_type,
    enabled,
    expires_at,
    health_state,
    health_state_until,
    credential_state,
    credentials,
    cap_concurrency,
    in_flight_count,
    cap_queue_sticky,
    cap_queue_fallback,
    queue_depth,
    priority,
    last_dispatch_at,
    model_allow_list,
    capability_flags,
    cap_quota_total,
    quota_used_total,
    cap_quota_daily,
    quota_used_daily,
    quota_window_daily_start,
    cap_quota_weekly,
    quota_used_weekly,
    quota_window_weekly_start,
    quota_status,
    created_at,
    updated_at,
    deleted_at,
    created_by_actor,
    last_modified_by_actor,
    rate_limited_at,
    rate_limit_reset_at,
    rate_limit_reason,
    overload_until,
    temp_unschedulable_until,
    temp_unschedulable_reason,
    temp_unschedulable_rule_index,
    session_window_5h_start,
    session_window_5h_end,
    session_window_5h_status,
    openai_403_counter,
    openai_403_window_start,
    custom_error_codes_enabled,
    custom_error_codes,
    pool_mode,
    temp_unschedulable_enabled,
    temp_unschedulable_rules,
    model_rate_limits,
    refresh_attempt_count,
    refresh_attempt_window_start,
    token_version,
    refresh_token_fingerprint,
    last_refresh_at,
    last_refresh_outcome,
    oauth_endpoint_health
FROM provider_accounts
WHERE id = $1
  AND tenant_id = $2
FOR UPDATE
`

type GetAccountForRevalidationParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

type GetAccountForRevalidationRow struct {
	ID                         int64              `db:"id" json:"id"`
	TenantID                   int64              `db:"tenant_id" json:"tenant_id"`
	ProviderID                 int64              `db:"provider_id" json:"provider_id"`
	ChannelID                  int64              `db:"channel_id" json:"channel_id"`
	Name                       string             `db:"name" json:"name"`
	AccountType                string             `db:"account_type" json:"account_type"`
	Enabled                    bool               `db:"enabled" json:"enabled"`
	ExpiresAt                  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	HealthState                string             `db:"health_state" json:"health_state"`
	HealthStateUntil           pgtype.Timestamptz `db:"health_state_until" json:"health_state_until"`
	CredentialState            string             `db:"credential_state" json:"credential_state"`
	Credentials                []byte             `db:"credentials" json:"credentials"`
	CapConcurrency             int32              `db:"cap_concurrency" json:"cap_concurrency"`
	InFlightCount              int32              `db:"in_flight_count" json:"in_flight_count"`
	CapQueueSticky             int32              `db:"cap_queue_sticky" json:"cap_queue_sticky"`
	CapQueueFallback           int32              `db:"cap_queue_fallback" json:"cap_queue_fallback"`
	QueueDepth                 int32              `db:"queue_depth" json:"queue_depth"`
	Priority                   int32              `db:"priority" json:"priority"`
	LastDispatchAt             pgtype.Timestamptz `db:"last_dispatch_at" json:"last_dispatch_at"`
	ModelAllowList             []string           `db:"model_allow_list" json:"model_allow_list"`
	CapabilityFlags            []string           `db:"capability_flags" json:"capability_flags"`
	CapQuotaTotal              pgtype.Numeric     `db:"cap_quota_total" json:"cap_quota_total"`
	QuotaUsedTotal             pgtype.Numeric     `db:"quota_used_total" json:"quota_used_total"`
	CapQuotaDaily              pgtype.Numeric     `db:"cap_quota_daily" json:"cap_quota_daily"`
	QuotaUsedDaily             pgtype.Numeric     `db:"quota_used_daily" json:"quota_used_daily"`
	QuotaWindowDailyStart      pgtype.Timestamptz `db:"quota_window_daily_start" json:"quota_window_daily_start"`
	CapQuotaWeekly             pgtype.Numeric     `db:"cap_quota_weekly" json:"cap_quota_weekly"`
	QuotaUsedWeekly            pgtype.Numeric     `db:"quota_used_weekly" json:"quota_used_weekly"`
	QuotaWindowWeeklyStart     pgtype.Timestamptz `db:"quota_window_weekly_start" json:"quota_window_weekly_start"`
	QuotaStatus                string             `db:"quota_status" json:"quota_status"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedByActor             *string            `db:"created_by_actor" json:"created_by_actor"`
	LastModifiedByActor        *string            `db:"last_modified_by_actor" json:"last_modified_by_actor"`
	RateLimitedAt              pgtype.Timestamptz `db:"rate_limited_at" json:"rate_limited_at"`
	RateLimitResetAt           pgtype.Timestamptz `db:"rate_limit_reset_at" json:"rate_limit_reset_at"`
	RateLimitReason            *string            `db:"rate_limit_reason" json:"rate_limit_reason"`
	OverloadUntil              pgtype.Timestamptz `db:"overload_until" json:"overload_until"`
	TempUnschedulableUntil     pgtype.Timestamptz `db:"temp_unschedulable_until" json:"temp_unschedulable_until"`
	TempUnschedulableReason    *string            `db:"temp_unschedulable_reason" json:"temp_unschedulable_reason"`
	TempUnschedulableRuleIndex *int32             `db:"temp_unschedulable_rule_index" json:"temp_unschedulable_rule_index"`
	SessionWindow5hStart       pgtype.Timestamptz `db:"session_window_5h_start" json:"session_window_5h_start"`
	SessionWindow5hEnd         pgtype.Timestamptz `db:"session_window_5h_end" json:"session_window_5h_end"`
	SessionWindow5hStatus      *string            `db:"session_window_5h_status" json:"session_window_5h_status"`
	OpenAI403Counter           int32              `db:"openai_403_counter" json:"openai_403_counter"`
	Openai403WindowStart       pgtype.Timestamptz `db:"openai_403_window_start" json:"openai_403_window_start"`
	CustomErrorCodesEnabled    bool               `db:"custom_error_codes_enabled" json:"custom_error_codes_enabled"`
	CustomErrorCodes           []int32            `db:"custom_error_codes" json:"custom_error_codes"`
	PoolMode                   bool               `db:"pool_mode" json:"pool_mode"`
	TempUnschedulableEnabled   bool               `db:"temp_unschedulable_enabled" json:"temp_unschedulable_enabled"`
	TempUnschedulableRules     []byte             `db:"temp_unschedulable_rules" json:"temp_unschedulable_rules"`
	ModelRateLimits            []byte             `db:"model_rate_limits" json:"model_rate_limits"`
	RefreshAttemptCount        int32              `db:"refresh_attempt_count" json:"refresh_attempt_count"`
	RefreshAttemptWindowStart  pgtype.Timestamptz `db:"refresh_attempt_window_start" json:"refresh_attempt_window_start"`
	TokenVersion               int32              `db:"token_version" json:"token_version"`
	RefreshTokenFingerprint    *string            `db:"refresh_token_fingerprint" json:"refresh_token_fingerprint"`
	LastRefreshAt              pgtype.Timestamptz `db:"last_refresh_at" json:"last_refresh_at"`
	LastRefreshOutcome         *string            `db:"last_refresh_outcome" json:"last_refresh_outcome"`
	OAuthEndpointHealth        string             `db:"oauth_endpoint_health" json:"oauth_endpoint_health"`
}

func (q *Queries) GetAccountForRevalidation(ctx context.Context, arg GetAccountForRevalidationParams) (GetAccountForRevalidationRow, error) {
	row := q.db.QueryRow(ctx, getAccountForRevalidation, arg.ID, arg.TenantID)
	var i GetAccountForRevalidationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProviderID,
		&i.ChannelID,
		&i.Name,
		&i.AccountType,
		&i.Enabled,
		&i.ExpiresAt,
		&i.HealthState,
		&i.HealthStateUntil,
		&i.CredentialState,
		&i.Credentials,
		&i.CapConcurrency,
		&i.InFlightCount,
		&i.CapQueueSticky,
		&i.CapQueueFallback,
		&i.QueueDepth,
		&i.Priority,
		&i.LastDispatchAt,
		&i.ModelAllowList,
		&i.CapabilityFlags,
		&i.CapQuotaTotal,
		&i.QuotaUsedTotal,
		&i.CapQuotaDaily,
		&i.QuotaUsedDaily,
		&i.QuotaWindowDailyStart,
		&i.CapQuotaWeekly,
		&i.QuotaUsedWeekly,
		&i.QuotaWindowWeeklyStart,
		&i.QuotaStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedByActor,
		&i.LastModifiedByActor,
		&i.RateLimitedAt,
		&i.RateLimitResetAt,
		&i.RateLimitReason,
		&i.OverloadUntil,
		&i.TempUnschedulableUntil,
		&i.TempUnschedulableReason,
		&i.TempUnschedulableRuleIndex,
		&i.SessionWindow5hStart,
		&i.SessionWindow5hEnd,
		&i.SessionWindow5hStatus,
		&i.OpenAI403Counter,
		&i.Openai403WindowStart,
		&i.CustomErrorCodesEnabled,
		&i.CustomErrorCodes,
		&i.PoolMode,
		&i.TempUnschedulableEnabled,
		&i.TempUnschedulableRules,
		&i.ModelRateLimits,
		&i.RefreshAttemptCount,
		&i.RefreshAttemptWindowStart,
		&i.TokenVersion,
		&i.RefreshTokenFingerprint,
		&i.LastRefreshAt,
		&i.LastRefreshOutcome,
		&i.OAuthEndpointHealth,
	)
	return i, err
}

const getModelRoutingForGroup = `-- name: GetModelRoutingForGroup :many
SELECT
    model,
    provider_account_ids
FROM model_routing_overrides
WHERE tenant_id = $1
  AND pool_group_id = $2
  AND model = $3
  AND enabled = true
  AND deleted_at IS NULL
`

type GetModelRoutingForGroupParams struct {
	TenantID    int64  `db:"tenant_id" json:"tenant_id"`
	PoolGroupID int64  `db:"pool_group_id" json:"pool_group_id"`
	Model       string `db:"model" json:"model"`
}

type GetModelRoutingForGroupRow struct {
	Model              string  `db:"model" json:"model"`
	ProviderAccountIds []int64 `db:"provider_account_ids" json:"provider_account_ids"`
}

func (q *Queries) GetModelRoutingForGroup(ctx context.Context, arg GetModelRoutingForGroupParams) ([]GetModelRoutingForGroupRow, error) {
	rows, err := q.db.Query(ctx, getModelRoutingForGroup, arg.TenantID, arg.PoolGroupID, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModelRoutingForGroupRow
	for rows.Next() {
		var i GetModelRoutingForGroupRow
		if err := rows.Scan(&i.Model, &i.ProviderAccountIds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementInFlightCount = `-- name: IncrementInFlightCount :execrows
UPDATE provider_accounts
SET
    in_flight_count = in_flight_count + 1,
    last_dispatch_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND tenant_id = $2
  AND in_flight_count < cap_concurrency
`

type IncrementInFlightCountParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) IncrementInFlightCount(ctx context.Context, arg IncrementInFlightCountParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementInFlightCount, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertProviderAccount = `-- name: InsertProviderAccount :one
INSERT INTO provider_accounts (
    tenant_id,
    provider_id,
    channel_id,
    name,
    account_type,
    enabled,
    expires_at,
    credentials,
    cap_concurrency,
    cap_queue_sticky,
    cap_queue_fallback,
    priority,
    model_allow_list,
    capability_flags,
    created_by_actor,
    last_modified_by_actor
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::bigint,
    $4::text,
    $5::text,
    COALESCE($6::boolean, true),
    $7::timestamptz,
    $8::jsonb,
    COALESCE($9::integer, 4),
    COALESCE($10::integer, 2),
    COALESCE($11::integer, 8),
    COALESCE($12::integer, 100),
    COALESCE($13::text[], ARRAY[]::text[]),
    COALESCE($14::text[], ARRAY[]::text[]),
    $15::text,
    $15::text
)
RETURNING id
`

type InsertProviderAccountParams struct {
	TenantID         int64              `db:"tenant_id" json:"tenant_id"`
	ProviderID       int64              `db:"provider_id" json:"provider_id"`
	ChannelID        int64              `db:"channel_id" json:"channel_id"`
	Name             string             `db:"name" json:"name"`
	AccountType      string             `db:"account_type" json:"account_type"`
	Enabled          *bool              `db:"enabled" json:"enabled"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Credentials      []byte             `db:"credentials" json:"credentials"`
	CapConcurrency   *int32             `db:"cap_concurrency" json:"cap_concurrency"`
	CapQueueSticky   *int32             `db:"cap_queue_sticky" json:"cap_queue_sticky"`
	CapQueueFallback *int32             `db:"cap_queue_fallback" json:"cap_queue_fallback"`
	Priority         *int32             `db:"priority" json:"priority"`
	ModelAllowList   []string           `db:"model_allow_list" json:"model_allow_list"`
	CapabilityFlags  []string           `db:"capability_flags" json:"capability_flags"`
	ActorID          *string            `db:"actor_id" json:"actor_id"`
}

func (q *Queries) InsertProviderAccount(ctx context.Context, arg InsertProviderAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertProviderAccount,
		arg.TenantID,
		arg.ProviderID,
		arg.ChannelID,
		arg.Name,
		arg.AccountType,
		arg.Enabled,
		arg.ExpiresAt,
		arg.Credentials,
		arg.CapConcurrency,
		arg.CapQueueSticky,
		arg.CapQueueFallback,
		arg.Priority,
		arg.ModelAllowList,
		arg.CapabilityFlags,
		arg.ActorID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAccountsForRefresh = `-- name: ListAccountsForRefresh :many
SELECT
    id,
    tenant_id,
    provider_id,
    expires_at
FROM provider_accounts
WHERE deleted_at IS NULL
  AND enabled
  AND (expires_at IS NULL OR expires_at < $1)
ORDER BY COALESCE(expires_at, NOW() + interval '1 year') ASC
LIMIT $2
`

type ListAccountsForRefreshParams struct {
	RefreshBefore pgtype.Timestamptz `db:"refresh_before" json:"refresh_before"`
	LimitCount    int32              `db:"limit_count" json:"limit_count"`
}

type ListAccountsForRefreshRow struct {
	ID         int64              `db:"id" json:"id"`
	TenantID   int64              `db:"tenant_id" json:"tenant_id"`
	ProviderID int64              `db:"provider_id" json:"provider_id"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

func (q *Queries) ListAccountsForRefresh(ctx context.Context, arg ListAccountsForRefreshParams) ([]ListAccountsForRefreshRow, error) {
	rows, err := q.db.Query(ctx, listAccountsForRefresh, arg.RefreshBefore, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsForRefreshRow
	for rows.Next() {
		var i ListAccountsForRefreshRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleAccounts = `-- name: ListEligibleAccounts :many
SELECT
    id,
    tenant_id,
    provider_id,
    channel_id,
    name,
    account_type,
    enabled,
    expires_at,
    health_state,
    health_state_until,
    credential_state,
    credentials,
    cap_concurrency,
    in_flight_count,
    cap_queue_sticky,
    cap_queue_fallback,
    queue_depth,
    priority,
    last_dispatch_at,
    model_allow_list,
    capability_flags,
    cap_quota_total,
    quota_used_total,
    cap_quota_daily,
    quota_used_daily,
    quota_window_daily_start,
    cap_quota_weekly,
    quota_used_weekly,
    quota_window_weekly_start,
    quota_status,
    created_at,
    updated_at,
    deleted_at,
    created_by_actor,
    last_modified_by_actor,
    rate_limited_at,
    rate_limit_reset_at,
    rate_limit_reason,
    overload_until,
    temp_unschedulable_until,
    temp_unschedulable_reason,
    temp_unschedulable_rule_index,
    session_window_5h_start,
    session_window_5h_end,
    session_window_5h_status,
    openai_403_counter,
    openai_403_window_start,
    custom_error_codes_enabled,
    custom_error_codes,
    pool_mode,
    temp_unschedulable_enabled,
    temp_unschedulable_rules,
    model_rate_limits,
    refresh_attempt_count,
    refresh_attempt_window_start,
    token_version,
    refresh_token_fingerprint,
    last_refresh_at,
    last_refresh_outcome,
    oauth_endpoint_health
FROM provider_accounts
WHERE tenant_id = $1
  AND channel_id = $2
  AND enabled = true
  AND deleted_at IS NULL
  AND health_state IN ('operational', 'degraded')
ORDER BY priority, last_dispatch_at NULLS FIRST
`

type ListEligibleAccountsParams struct {
	TenantID  int64 `db:"tenant_id" json:"tenant_id"`
	ChannelID int64 `db:"channel_id" json:"channel_id"`
}

type ListEligibleAccountsRow struct {
	ID                         int64              `db:"id" json:"id"`
	TenantID                   int64              `db:"tenant_id" json:"tenant_id"`
	ProviderID                 int64              `db:"provider_id" json:"provider_id"`
	ChannelID                  int64              `db:"channel_id" json:"channel_id"`
	Name                       string             `db:"name" json:"name"`
	AccountType                string             `db:"account_type" json:"account_type"`
	Enabled                    bool               `db:"enabled" json:"enabled"`
	ExpiresAt                  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	HealthState                string             `db:"health_state" json:"health_state"`
	HealthStateUntil           pgtype.Timestamptz `db:"health_state_until" json:"health_state_until"`
	CredentialState            string             `db:"credential_state" json:"credential_state"`
	Credentials                []byte             `db:"credentials" json:"credentials"`
	CapConcurrency             int32              `db:"cap_concurrency" json:"cap_concurrency"`
	InFlightCount              int32              `db:"in_flight_count" json:"in_flight_count"`
	CapQueueSticky             int32              `db:"cap_queue_sticky" json:"cap_queue_sticky"`
	CapQueueFallback           int32              `db:"cap_queue_fallback" json:"cap_queue_fallback"`
	QueueDepth                 int32              `db:"queue_depth" json:"queue_depth"`
	Priority                   int32              `db:"priority" json:"priority"`
	LastDispatchAt             pgtype.Timestamptz `db:"last_dispatch_at" json:"last_dispatch_at"`
	ModelAllowList             []string           `db:"model_allow_list" json:"model_allow_list"`
	CapabilityFlags            []string           `db:"capability_flags" json:"capability_flags"`
	CapQuotaTotal              pgtype.Numeric     `db:"cap_quota_total" json:"cap_quota_total"`
	QuotaUsedTotal             pgtype.Numeric     `db:"quota_used_total" json:"quota_used_total"`
	CapQuotaDaily              pgtype.Numeric     `db:"cap_quota_daily" json:"cap_quota_daily"`
	QuotaUsedDaily             pgtype.Numeric     `db:"quota_used_daily" json:"quota_used_daily"`
	QuotaWindowDailyStart      pgtype.Timestamptz `db:"quota_window_daily_start" json:"quota_window_daily_start"`
	CapQuotaWeekly             pgtype.Numeric     `db:"cap_quota_weekly" json:"cap_quota_weekly"`
	QuotaUsedWeekly            pgtype.Numeric     `db:"quota_used_weekly" json:"quota_used_weekly"`
	QuotaWindowWeeklyStart     pgtype.Timestamptz `db:"quota_window_weekly_start" json:"quota_window_weekly_start"`
	QuotaStatus                string             `db:"quota_status" json:"quota_status"`
	CreatedAt                  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
	CreatedByActor             *string            `db:"created_by_actor" json:"created_by_actor"`
	LastModifiedByActor        *string            `db:"last_modified_by_actor" json:"last_modified_by_actor"`
	RateLimitedAt              pgtype.Timestamptz `db:"rate_limited_at" json:"rate_limited_at"`
	RateLimitResetAt           pgtype.Timestamptz `db:"rate_limit_reset_at" json:"rate_limit_reset_at"`
	RateLimitReason            *string            `db:"rate_limit_reason" json:"rate_limit_reason"`
	OverloadUntil              pgtype.Timestamptz `db:"overload_until" json:"overload_until"`
	TempUnschedulableUntil     pgtype.Timestamptz `db:"temp_unschedulable_until" json:"temp_unschedulable_until"`
	TempUnschedulableReason    *string            `db:"temp_unschedulable_reason" json:"temp_unschedulable_reason"`
	TempUnschedulableRuleIndex *int32             `db:"temp_unschedulable_rule_index" json:"temp_unschedulable_rule_index"`
	SessionWindow5hStart       pgtype.Timestamptz `db:"session_window_5h_start" json:"session_window_5h_start"`
	SessionWindow5hEnd         pgtype.Timestamptz `db:"session_window_5h_end" json:"session_window_5h_end"`
	SessionWindow5hStatus      *string            `db:"session_window_5h_status" json:"session_window_5h_status"`
	OpenAI403Counter           int32              `db:"openai_403_counter" json:"openai_403_counter"`
	Openai403WindowStart       pgtype.Timestamptz `db:"openai_403_window_start" json:"openai_403_window_start"`
	CustomErrorCodesEnabled    bool               `db:"custom_error_codes_enabled" json:"custom_error_codes_enabled"`
	CustomErrorCodes           []int32            `db:"custom_error_codes" json:"custom_error_codes"`
	PoolMode                   bool               `db:"pool_mode" json:"pool_mode"`
	TempUnschedulableEnabled   bool               `db:"temp_unschedulable_enabled" json:"temp_unschedulable_enabled"`
	TempUnschedulableRules     []byte             `db:"temp_unschedulable_rules" json:"temp_unschedulable_rules"`
	ModelRateLimits            []byte             `db:"model_rate_limits" json:"model_rate_limits"`
	RefreshAttemptCount        int32              `db:"refresh_attempt_count" json:"refresh_attempt_count"`
	RefreshAttemptWindowStart  pgtype.Timestamptz `db:"refresh_attempt_window_start" json:"refresh_attempt_window_start"`
	TokenVersion               int32              `db:"token_version" json:"token_version"`
	RefreshTokenFingerprint    *string            `db:"refresh_token_fingerprint" json:"refresh_token_fingerprint"`
	LastRefreshAt              pgtype.Timestamptz `db:"last_refresh_at" json:"last_refresh_at"`
	LastRefreshOutcome         *string            `db:"last_refresh_outcome" json:"last_refresh_outcome"`
	OAuthEndpointHealth        string             `db:"oauth_endpoint_health" json:"oauth_endpoint_health"`
}

func (q *Queries) ListEligibleAccounts(ctx context.Context, arg ListEligibleAccountsParams) ([]ListEligibleAccountsRow, error) {
	rows, err := q.db.Query(ctx, listEligibleAccounts, arg.TenantID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleAccountsRow
	for rows.Next() {
		var i ListEligibleAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderID,
			&i.ChannelID,
			&i.Name,
			&i.AccountType,
			&i.Enabled,
			&i.ExpiresAt,
			&i.HealthState,
			&i.HealthStateUntil,
			&i.CredentialState,
			&i.Credentials,
			&i.CapConcurrency,
			&i.InFlightCount,
			&i.CapQueueSticky,
			&i.CapQueueFallback,
			&i.QueueDepth,
			&i.Priority,
			&i.LastDispatchAt,
			&i.ModelAllowList,
			&i.CapabilityFlags,
			&i.CapQuotaTotal,
			&i.QuotaUsedTotal,
			&i.CapQuotaDaily,
			&i.QuotaUsedDaily,
			&i.QuotaWindowDailyStart,
			&i.CapQuotaWeekly,
			&i.QuotaUsedWeekly,
			&i.QuotaWindowWeeklyStart,
			&i.QuotaStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedByActor,
			&i.LastModifiedByActor,
			&i.RateLimitedAt,
			&i.RateLimitResetAt,
			&i.RateLimitReason,
			&i.OverloadUntil,
			&i.TempUnschedulableUntil,
			&i.TempUnschedulableReason,
			&i.TempUnschedulableRuleIndex,
			&i.SessionWindow5hStart,
			&i.SessionWindow5hEnd,
			&i.SessionWindow5hStatus,
			&i.OpenAI403Counter,
			&i.Openai403WindowStart,
			&i.CustomErrorCodesEnabled,
			&i.CustomErrorCodes,
			&i.PoolMode,
			&i.TempUnschedulableEnabled,
			&i.TempUnschedulableRules,
			&i.ModelRateLimits,
			&i.RefreshAttemptCount,
			&i.RefreshAttemptWindowStart,
			&i.TokenVersion,
			&i.RefreshTokenFingerprint,
			&i.LastRefreshAt,
			&i.LastRefreshOutcome,
			&i.OAuthEndpointHealth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEligibleAccountsByPoolGroup = `-- name: ListEligibleAccountsByPoolGroup :many
SELECT
    pa.id,
    pa.tenant_id,
    pa.provider_id,
    pa.channel_id,
    pa.cap_concurrency,
    pa.in_flight_count,
    pa.priority,
    pa.last_dispatch_at,
    pa.model_allow_list,
    pa.cap_queue_sticky,
    pa.cap_queue_fallback
FROM provider_accounts pa
INNER JOIN channels c ON c.id = pa.channel_id
WHERE pa.tenant_id = $1
  AND c.pool_group_id = $2
  AND c.tenant_id = $1
  AND pa.enabled = true
  AND pa.deleted_at IS NULL
  AND pa.health_state IN ('operational', 'degraded')
ORDER BY pa.priority, pa.last_dispatch_at NULLS FIRST
`

type ListEligibleAccountsByPoolGroupParams struct {
	TenantID    int64 `db:"tenant_id" json:"tenant_id"`
	PoolGroupID int64 `db:"pool_group_id" json:"pool_group_id"`
}

type ListEligibleAccountsByPoolGroupRow struct {
	ID               int64              `db:"id" json:"id"`
	TenantID         int64              `db:"tenant_id" json:"tenant_id"`
	ProviderID       int64              `db:"provider_id" json:"provider_id"`
	ChannelID        int64              `db:"channel_id" json:"channel_id"`
	CapConcurrency   int32              `db:"cap_concurrency" json:"cap_concurrency"`
	InFlightCount    int32              `db:"in_flight_count" json:"in_flight_count"`
	Priority         int32              `db:"priority" json:"priority"`
	LastDispatchAt   pgtype.Timestamptz `db:"last_dispatch_at" json:"last_dispatch_at"`
	ModelAllowList   []string           `db:"model_allow_list" json:"model_allow_list"`
	CapQueueSticky   int32              `db:"cap_queue_sticky" json:"cap_queue_sticky"`
	CapQueueFallback int32              `db:"cap_queue_fallback" json:"cap_queue_fallback"`
}

// Phase C.2: pool-group-keyed eligibility lookup for the gateway selector.
// Joins channels → provider_accounts so a SelectionRequest with PoolGroupID
// (and no explicit ChannelID) can resolve to the candidate account set.
// cap_queue_sticky/fallback are returned so the selector can construct
// WaitPlan fallback when every eligible account is at concurrency cap.
func (q *Queries) ListEligibleAccountsByPoolGroup(ctx context.Context, arg ListEligibleAccountsByPoolGroupParams) ([]ListEligibleAccountsByPoolGroupRow, error) {
	rows, err := q.db.Query(ctx, listEligibleAccountsByPoolGroup, arg.TenantID, arg.PoolGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEligibleAccountsByPoolGroupRow
	for rows.Next() {
		var i ListEligibleAccountsByPoolGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProviderID,
			&i.ChannelID,
			&i.CapConcurrency,
			&i.InFlightCount,
			&i.Priority,
			&i.LastDispatchAt,
			&i.ModelAllowList,
			&i.CapQueueSticky,
			&i.CapQueueFallback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProviderAccount = `-- name: SoftDeleteProviderAccount :exec
UPDATE provider_accounts
SET
    deleted_at = COALESCE(deleted_at, NOW()),
    updated_at = NOW(),
    enabled = false,
    last_modified_by_actor = $1::text
WHERE id = $2::bigint
  AND tenant_id = $3::bigint
  AND deleted_at IS NULL
`

type SoftDeleteProviderAccountParams struct {
	ActorID  *string `db:"actor_id" json:"actor_id"`
	ID       int64   `db:"id" json:"id"`
	TenantID int64   `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) SoftDeleteProviderAccount(ctx context.Context, arg SoftDeleteProviderAccountParams) error {
	_, err := q.db.Exec(ctx, softDeleteProviderAccount, arg.ActorID, arg.ID, arg.TenantID)
	return err
}

const updateProviderAccountEnabled = `-- name: UpdateProviderAccountEnabled :exec
UPDATE provider_accounts
SET
    enabled = $1::boolean,
    updated_at = NOW(),
    last_modified_by_actor = $2::text
WHERE id = $3::bigint
  AND tenant_id = $4::bigint
  AND deleted_at IS NULL
`

type UpdateProviderAccountEnabledParams struct {
	Enabled  bool    `db:"enabled" json:"enabled"`
	ActorID  *string `db:"actor_id" json:"actor_id"`
	ID       int64   `db:"id" json:"id"`
	TenantID int64   `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateProviderAccountEnabled(ctx context.Context, arg UpdateProviderAccountEnabledParams) error {
	_, err := q.db.Exec(ctx, updateProviderAccountEnabled,
		arg.Enabled,
		arg.ActorID,
		arg.ID,
		arg.TenantID,
	)
	return err
}
