// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pool_audit.sql

package db

import (
	"context"
)

const insertPoolRoutingAuditEvent = `-- name: InsertPoolRoutingAuditEvent :exec
INSERT INTO pool_routing_audit_events (
    tenant_id,
    event_type,
    pool_group_id,
    provider_account_id,
    request_id,
    actor_id,
    actor_role,
    reason,
    payload,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    COALESCE($10, NOW())
)
`

type InsertPoolRoutingAuditEventParams struct {
	TenantID          int64       `db:"tenant_id" json:"tenant_id"`
	EventType         string      `db:"event_type" json:"event_type"`
	PoolGroupID       *int64      `db:"pool_group_id" json:"pool_group_id"`
	ProviderAccountID *int64      `db:"provider_account_id" json:"provider_account_id"`
	RequestID         *string     `db:"request_id" json:"request_id"`
	ActorID           *string     `db:"actor_id" json:"actor_id"`
	ActorRole         *string     `db:"actor_role" json:"actor_role"`
	Reason            *string     `db:"reason" json:"reason"`
	Payload           []byte      `db:"payload" json:"payload"`
	CreatedAt         interface{} `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertPoolRoutingAuditEvent(ctx context.Context, arg InsertPoolRoutingAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertPoolRoutingAuditEvent,
		arg.TenantID,
		arg.EventType,
		arg.PoolGroupID,
		arg.ProviderAccountID,
		arg.RequestID,
		arg.ActorID,
		arg.ActorRole,
		arg.Reason,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}
