// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: proto_policy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expireCurrentProtocolPolicy = `-- name: ExpireCurrentProtocolPolicy :exec
UPDATE protocol_policy_versions
SET effective_to = $2
WHERE tenant_id = $1
  AND effective_to IS NULL
`

type ExpireCurrentProtocolPolicyParams struct {
	TenantID    int64              `db:"tenant_id" json:"tenant_id"`
	EffectiveTo pgtype.Timestamptz `db:"effective_to" json:"effective_to"`
}

func (q *Queries) ExpireCurrentProtocolPolicy(ctx context.Context, arg ExpireCurrentProtocolPolicyParams) error {
	_, err := q.db.Exec(ctx, expireCurrentProtocolPolicy, arg.TenantID, arg.EffectiveTo)
	return err
}

const getActiveProtocolPolicy = `-- name: GetActiveProtocolPolicy :one

SELECT
    id,
    tenant_id,
    version,
    policy_data,
    effective_from,
    effective_to,
    created_at,
    created_by_actor
FROM protocol_policy_versions
WHERE tenant_id = $1
  AND effective_from <= NOW()
  AND (effective_to IS NULL OR effective_to > NOW())
ORDER BY effective_from DESC
LIMIT 1
`

// F-PROTO-002 protocol policy version registry queries.
// Backed by protocol_policy_versions table in docs/schema/protocol-translation.sql.
func (q *Queries) GetActiveProtocolPolicy(ctx context.Context, tenantID int64) (ProtocolPolicyVersion, error) {
	row := q.db.QueryRow(ctx, getActiveProtocolPolicy, tenantID)
	var i ProtocolPolicyVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.PolicyData,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.CreatedByActor,
	)
	return i, err
}

const getProtocolPolicyByVersion = `-- name: GetProtocolPolicyByVersion :one
SELECT
    id,
    tenant_id,
    version,
    policy_data,
    effective_from,
    effective_to,
    created_at,
    created_by_actor
FROM protocol_policy_versions
WHERE tenant_id = $1
  AND version = $2
`

type GetProtocolPolicyByVersionParams struct {
	TenantID int64  `db:"tenant_id" json:"tenant_id"`
	Version  string `db:"version" json:"version"`
}

func (q *Queries) GetProtocolPolicyByVersion(ctx context.Context, arg GetProtocolPolicyByVersionParams) (ProtocolPolicyVersion, error) {
	row := q.db.QueryRow(ctx, getProtocolPolicyByVersion, arg.TenantID, arg.Version)
	var i ProtocolPolicyVersion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Version,
		&i.PolicyData,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.CreatedByActor,
	)
	return i, err
}

const insertProtocolPolicyVersion = `-- name: InsertProtocolPolicyVersion :one
INSERT INTO protocol_policy_versions (
    tenant_id, version, policy_data, effective_from, effective_to, created_by_actor
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, created_at
`

type InsertProtocolPolicyVersionParams struct {
	TenantID       int64              `db:"tenant_id" json:"tenant_id"`
	Version        string             `db:"version" json:"version"`
	PolicyData     []byte             `db:"policy_data" json:"policy_data"`
	EffectiveFrom  pgtype.Timestamptz `db:"effective_from" json:"effective_from"`
	EffectiveTo    pgtype.Timestamptz `db:"effective_to" json:"effective_to"`
	CreatedByActor *string            `db:"created_by_actor" json:"created_by_actor"`
}

type InsertProtocolPolicyVersionRow struct {
	ID        int64              `db:"id" json:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertProtocolPolicyVersion(ctx context.Context, arg InsertProtocolPolicyVersionParams) (InsertProtocolPolicyVersionRow, error) {
	row := q.db.QueryRow(ctx, insertProtocolPolicyVersion,
		arg.TenantID,
		arg.Version,
		arg.PolicyData,
		arg.EffectiveFrom,
		arg.EffectiveTo,
		arg.CreatedByActor,
	)
	var i InsertProtocolPolicyVersionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
