// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: registry.sql

package db

import (
	"context"
)

const getModelByID = `-- name: GetModelByID :one
SELECT
    id,
    tenant_id,
    scope,
    canonical_id,
    protocol_family,
    default_provider_model_id,
    default_context_window,
    default_request_timeout_ms,
    pricing_class,
    model_owner,
    status
FROM models
WHERE id = $1::bigint
  AND deleted_at IS NULL
  AND (
        (scope = 'tenant' AND tenant_id = $2::bigint)
        OR (scope = 'global' AND tenant_id IS NULL)
      )
`

type GetModelByIDParams struct {
	ID       int64 `db:"id" json:"id"`
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
}

type GetModelByIDRow struct {
	ID                      int64  `db:"id" json:"id"`
	TenantID                *int64 `db:"tenant_id" json:"tenant_id"`
	Scope                   string `db:"scope" json:"scope"`
	CanonicalID             string `db:"canonical_id" json:"canonical_id"`
	ProtocolFamily          string `db:"protocol_family" json:"protocol_family"`
	DefaultProviderModelID  string `db:"default_provider_model_id" json:"default_provider_model_id"`
	DefaultContextWindow    int32  `db:"default_context_window" json:"default_context_window"`
	DefaultRequestTimeoutMs int32  `db:"default_request_timeout_ms" json:"default_request_timeout_ms"`
	PricingClass            string `db:"pricing_class" json:"pricing_class"`
	ModelOwner              string `db:"model_owner" json:"model_owner"`
	Status                  string `db:"status" json:"status"`
}

// Resolves the canonical model row, constrained to the requesting tenant
// (scope='tenant' AND tenant_id=$tenant) OR scope='global'. This blocks
// a misconfigured tenant alias from reaching another tenant's model row
// (codex N+5a P3 finding 2026-04-30 — defense in depth in addition to
// admin-write-time validation).
func (q *Queries) GetModelByID(ctx context.Context, arg GetModelByIDParams) (GetModelByIDRow, error) {
	row := q.db.QueryRow(ctx, getModelByID, arg.ID, arg.TenantID)
	var i GetModelByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Scope,
		&i.CanonicalID,
		&i.ProtocolFamily,
		&i.DefaultProviderModelID,
		&i.DefaultContextWindow,
		&i.DefaultRequestTimeoutMs,
		&i.PricingClass,
		&i.ModelOwner,
		&i.Status,
	)
	return i, err
}

const getTenantInheritGlobal = `-- name: GetTenantInheritGlobal :one
SELECT inherit_global_catalog
FROM model_registry_tenant_policies
WHERE tenant_id = $1::bigint
`

// Returns whether a tenant has opted into global-catalog inheritance.
// Missing row -> nothing returned -> resolver treats as false.
func (q *Queries) GetTenantInheritGlobal(ctx context.Context, tenantID int64) (bool, error) {
	row := q.db.QueryRow(ctx, getTenantInheritGlobal, tenantID)
	var inherit_global_catalog bool
	err := row.Scan(&inherit_global_catalog)
	return inherit_global_catalog, err
}

const getTenantSnapshotVersion = `-- name: GetTenantSnapshotVersion :one
SELECT version
FROM model_registry_snapshots
WHERE tenant_id = $1::bigint
`

// Returns the per-tenant registry version stamp. Missing row means the
// tenant has no admin writes yet; resolver treats as version 1.
func (q *Queries) GetTenantSnapshotVersion(ctx context.Context, tenantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getTenantSnapshotVersion, tenantID)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const listModelCapabilities = `-- name: ListModelCapabilities :many
SELECT
    capability,
    capability_value,
    capability_params,
    source
FROM model_registry_capabilities
WHERE (
        (tenant_id = $1::bigint AND scope = 'tenant')
        OR (tenant_id IS NULL AND scope = 'global')
      )
  AND model_id = $2::bigint
  AND deleted_at IS NULL
  AND enabled = true
ORDER BY capability
`

type ListModelCapabilitiesParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ModelID  int64 `db:"model_id" json:"model_id"`
}

type ListModelCapabilitiesRow struct {
	Capability       string  `db:"capability" json:"capability"`
	CapabilityValue  *string `db:"capability_value" json:"capability_value"`
	CapabilityParams []byte  `db:"capability_params" json:"capability_params"`
	Source           string  `db:"source" json:"source"`
}

// Returns capability rows visible to (tenant_id, model_id), including
// global capabilities for the same model. enabled rows only.
func (q *Queries) ListModelCapabilities(ctx context.Context, arg ListModelCapabilitiesParams) ([]ListModelCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listModelCapabilities, arg.TenantID, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelCapabilitiesRow
	for rows.Next() {
		var i ListModelCapabilitiesRow
		if err := rows.Scan(
			&i.Capability,
			&i.CapabilityValue,
			&i.CapabilityParams,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelPoolBindings = `-- name: ListModelPoolBindings :many
SELECT
    id,
    pool_group_id,
    priority,
    weight,
    selection_mode,
    provider_model_id_override,
    rpm_limit,
    tpm_limit,
    max_parallel_requests,
    fallback_class,
    reason
FROM model_pool_bindings
WHERE tenant_id = $1::bigint
  AND model_id = $2::bigint
  AND deleted_at IS NULL
  AND enabled = true
  AND (effective_from IS NULL OR effective_from <= now())
  AND (effective_until IS NULL OR effective_until > now())
ORDER BY priority ASC, id ASC
`

type ListModelPoolBindingsParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ModelID  int64 `db:"model_id" json:"model_id"`
}

type ListModelPoolBindingsRow struct {
	ID                      int64   `db:"id" json:"id"`
	PoolGroupID             int64   `db:"pool_group_id" json:"pool_group_id"`
	Priority                int32   `db:"priority" json:"priority"`
	Weight                  int32   `db:"weight" json:"weight"`
	SelectionMode           string  `db:"selection_mode" json:"selection_mode"`
	ProviderModelIDOverride *string `db:"provider_model_id_override" json:"provider_model_id_override"`
	RpmLimit                *int32  `db:"rpm_limit" json:"rpm_limit"`
	TpmLimit                *int32  `db:"tpm_limit" json:"tpm_limit"`
	MaxParallelRequests     *int32  `db:"max_parallel_requests" json:"max_parallel_requests"`
	FallbackClass           string  `db:"fallback_class" json:"fallback_class"`
	Reason                  string  `db:"reason" json:"reason"`
}

// Returns enabled bindings ordered by priority then id, filtered by the
// effective_from/until time window. ALWAYS tenant-scoped: pool_groups
// are tenant-owned so a global binding would leak pool_group ids across
// tenants (codex N+5a P1 finding 2026-04-30 — addressed by removing the
// scope column from model_pool_bindings entirely; bindings are inherently
// tenant-local even for global models). Slice 2 emits all candidates;
// Router selects index 0 only at L0 (AttemptBudget=1).
func (q *Queries) ListModelPoolBindings(ctx context.Context, arg ListModelPoolBindingsParams) ([]ListModelPoolBindingsRow, error) {
	rows, err := q.db.Query(ctx, listModelPoolBindings, arg.TenantID, arg.ModelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelPoolBindingsRow
	for rows.Next() {
		var i ListModelPoolBindingsRow
		if err := rows.Scan(
			&i.ID,
			&i.PoolGroupID,
			&i.Priority,
			&i.Weight,
			&i.SelectionMode,
			&i.ProviderModelIDOverride,
			&i.RpmLimit,
			&i.TpmLimit,
			&i.MaxParallelRequests,
			&i.FallbackClass,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupGlobalAlias = `-- name: LookupGlobalAlias :one
SELECT
    a.id                    AS alias_id,
    a.model_id,
    a.status                AS alias_status,
    a.disabled_reason,
    a.public_alias_display
FROM model_aliases a
WHERE a.scope = 'global'
  AND a.tenant_id IS NULL
  AND a.public_alias_normalized = $1::text
  AND a.deleted_at IS NULL
LIMIT 1
`

type LookupGlobalAliasRow struct {
	AliasID            int64   `db:"alias_id" json:"alias_id"`
	ModelID            int64   `db:"model_id" json:"model_id"`
	AliasStatus        string  `db:"alias_status" json:"alias_status"`
	DisabledReason     *string `db:"disabled_reason" json:"disabled_reason"`
	PublicAliasDisplay string  `db:"public_alias_display" json:"public_alias_display"`
}

// Step 2 of resolve. Only called when tenant lookup misses AND the tenant
// policy permits global inheritance.
func (q *Queries) LookupGlobalAlias(ctx context.Context, aliasLower string) (LookupGlobalAliasRow, error) {
	row := q.db.QueryRow(ctx, lookupGlobalAlias, aliasLower)
	var i LookupGlobalAliasRow
	err := row.Scan(
		&i.AliasID,
		&i.ModelID,
		&i.AliasStatus,
		&i.DisabledReason,
		&i.PublicAliasDisplay,
	)
	return i, err
}

const lookupTenantAlias = `-- name: LookupTenantAlias :one

SELECT
    a.id                    AS alias_id,
    a.model_id,
    a.status                AS alias_status,
    a.disabled_reason,
    a.public_alias_display
FROM model_aliases a
WHERE a.tenant_id = $1::bigint
  AND a.public_alias_normalized = $2::text
  AND a.scope = 'tenant'
  AND a.deleted_at IS NULL
LIMIT 1
`

type LookupTenantAliasParams struct {
	TenantID   int64  `db:"tenant_id" json:"tenant_id"`
	AliasLower string `db:"alias_lower" json:"alias_lower"`
}

type LookupTenantAliasRow struct {
	AliasID            int64   `db:"alias_id" json:"alias_id"`
	ModelID            int64   `db:"model_id" json:"model_id"`
	AliasStatus        string  `db:"alias_status" json:"alias_status"`
	DisabledReason     *string `db:"disabled_reason" json:"disabled_reason"`
	PublicAliasDisplay string  `db:"public_alias_display" json:"public_alias_display"`
}

// Slice 2 (N+5a) Model Registry queries.
// Per docs/process/plans/2026-04-30-n5-model-registry.md.
// Per CMB-7: SELECT-only at request time. Snapshot version increments
// happen via a future Phase E admin writer outside this package.
// Per CMB-1: NEVER select credentials; this package never joins
// provider_accounts.credentials, OAuth tokens, or api_keys.key_hash.
// Step 1 of resolve. Returns the tenant-scoped alias row regardless of
// status (active/disabled/deleted-protected). The Go resolver checks
// status: tenant disabled is an EXPLICIT DENY that blocks global fallback
// per D3 invariant (integration test #5).
func (q *Queries) LookupTenantAlias(ctx context.Context, arg LookupTenantAliasParams) (LookupTenantAliasRow, error) {
	row := q.db.QueryRow(ctx, lookupTenantAlias, arg.TenantID, arg.AliasLower)
	var i LookupTenantAliasRow
	err := row.Scan(
		&i.AliasID,
		&i.ModelID,
		&i.AliasStatus,
		&i.DisabledReason,
		&i.PublicAliasDisplay,
	)
	return i, err
}
