// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package modelroutingadmindb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// F-POOL-001 Layer 1: Model Routing config. Empty array = no override; selection skips Layer 1 and goes to Layer 1.5b.
type ModelRoutingOverride struct {
	ID                 int64              `db:"id" json:"id"`
	TenantID           int64              `db:"tenant_id" json:"tenant_id"`
	PoolGroupID        int64              `db:"pool_group_id" json:"pool_group_id"`
	Model              string             `db:"model" json:"model"`
	ProviderAccountIDs []int64            `db:"provider_account_ids" json:"provider_account_ids"`
	Enabled            bool               `db:"enabled" json:"enabled"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `db:"deleted_at" json:"deleted_at"`
}
