// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: model_routing_overrides.sql

package modelroutingadmindb

import (
	"context"
)

const createModelRoutingOverrideAdmin = `-- name: CreateModelRoutingOverrideAdmin :one

INSERT INTO model_routing_overrides (
    tenant_id,
    pool_group_id,
    model,
    provider_account_ids,
    enabled
) VALUES (
    $1::bigint,
    $2::bigint,
    $3::text,
    $4::bigint[],
    $5::boolean
)
RETURNING
    id,
    tenant_id,
    pool_group_id,
    model,
    provider_account_ids,
    enabled,
    created_at,
    updated_at,
    deleted_at
`

type CreateModelRoutingOverrideAdminParams struct {
	TenantID           int64   `db:"tenant_id" json:"tenant_id"`
	PoolGroupID        int64   `db:"pool_group_id" json:"pool_group_id"`
	Model              string  `db:"model" json:"model"`
	ProviderAccountIDs []int64 `db:"provider_account_ids" json:"provider_account_ids"`
	Enabled            bool    `db:"enabled" json:"enabled"`
}

// 模型路由强制 pin 的租户域管理查询；消费查询仍由 pool_accounts.sql 负责。
func (q *Queries) CreateModelRoutingOverrideAdmin(ctx context.Context, arg CreateModelRoutingOverrideAdminParams) (ModelRoutingOverride, error) {
	row := q.db.QueryRow(ctx, createModelRoutingOverrideAdmin,
		arg.TenantID,
		arg.PoolGroupID,
		arg.Model,
		arg.ProviderAccountIDs,
		arg.Enabled,
	)
	var i ModelRoutingOverride
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PoolGroupID,
		&i.Model,
		&i.ProviderAccountIDs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteModelRoutingOverrideAdmin = `-- name: DeleteModelRoutingOverrideAdmin :one
UPDATE model_routing_overrides
SET
    enabled = false,
    deleted_at = NOW(),
    updated_at = NOW()
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND deleted_at IS NULL
RETURNING
    id,
    tenant_id,
    pool_group_id,
    model,
    provider_account_ids,
    enabled,
    created_at,
    updated_at,
    deleted_at
`

type DeleteModelRoutingOverrideAdminParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ID       int64 `db:"id" json:"id"`
}

func (q *Queries) DeleteModelRoutingOverrideAdmin(ctx context.Context, arg DeleteModelRoutingOverrideAdminParams) (ModelRoutingOverride, error) {
	row := q.db.QueryRow(ctx, deleteModelRoutingOverrideAdmin, arg.TenantID, arg.ID)
	var i ModelRoutingOverride
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PoolGroupID,
		&i.Model,
		&i.ProviderAccountIDs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getModelRoutingOverrideAdminForUpdate = `-- name: GetModelRoutingOverrideAdminForUpdate :one
SELECT
    id,
    tenant_id,
    pool_group_id,
    model,
    provider_account_ids,
    enabled,
    created_at,
    updated_at,
    deleted_at
FROM model_routing_overrides
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND deleted_at IS NULL
FOR UPDATE
`

type GetModelRoutingOverrideAdminForUpdateParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ID       int64 `db:"id" json:"id"`
}

func (q *Queries) GetModelRoutingOverrideAdminForUpdate(ctx context.Context, arg GetModelRoutingOverrideAdminForUpdateParams) (ModelRoutingOverride, error) {
	row := q.db.QueryRow(ctx, getModelRoutingOverrideAdminForUpdate, arg.TenantID, arg.ID)
	var i ModelRoutingOverride
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PoolGroupID,
		&i.Model,
		&i.ProviderAccountIDs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listModelRoutingOverridesAdmin = `-- name: ListModelRoutingOverridesAdmin :many
SELECT
    id,
    tenant_id,
    pool_group_id,
    model,
    provider_account_ids,
    enabled,
    created_at,
    updated_at,
    deleted_at
FROM model_routing_overrides
WHERE tenant_id = $1::bigint
  AND deleted_at IS NULL
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListModelRoutingOverridesAdmin(ctx context.Context, tenantID int64) ([]ModelRoutingOverride, error) {
	rows, err := q.db.Query(ctx, listModelRoutingOverridesAdmin, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelRoutingOverride
	for rows.Next() {
		var i ModelRoutingOverride
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PoolGroupID,
			&i.Model,
			&i.ProviderAccountIDs,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockModelRoutingAccountsForPool = `-- name: LockModelRoutingAccountsForPool :many
SELECT pa.id
FROM provider_accounts pa
JOIN channels c
  ON c.id = pa.channel_id
 AND c.tenant_id = pa.tenant_id
 AND c.deleted_at IS NULL
WHERE pa.tenant_id = $1::bigint
  AND c.pool_group_id = $2::bigint
  AND pa.id = ANY($3::bigint[])
  AND pa.deleted_at IS NULL
FOR KEY SHARE OF pa, c
`

type LockModelRoutingAccountsForPoolParams struct {
	TenantID           int64   `db:"tenant_id" json:"tenant_id"`
	PoolGroupID        int64   `db:"pool_group_id" json:"pool_group_id"`
	ProviderAccountIDs []int64 `db:"provider_account_ids" json:"provider_account_ids"`
}

func (q *Queries) LockModelRoutingAccountsForPool(ctx context.Context, arg LockModelRoutingAccountsForPoolParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockModelRoutingAccountsForPool, arg.TenantID, arg.PoolGroupID, arg.ProviderAccountIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockModelRoutingPoolForTenant = `-- name: LockModelRoutingPoolForTenant :one
SELECT id
FROM pool_groups
WHERE tenant_id = $1::bigint
  AND id = $2::bigint
  AND deleted_at IS NULL
FOR KEY SHARE
`

type LockModelRoutingPoolForTenantParams struct {
	TenantID int64 `db:"tenant_id" json:"tenant_id"`
	ID       int64 `db:"id" json:"id"`
}

func (q *Queries) LockModelRoutingPoolForTenant(ctx context.Context, arg LockModelRoutingPoolForTenantParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockModelRoutingPoolForTenant, arg.TenantID, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateModelRoutingOverrideAdmin = `-- name: UpdateModelRoutingOverrideAdmin :one
UPDATE model_routing_overrides
SET
    provider_account_ids = $1::bigint[],
    enabled = $2::boolean,
    updated_at = NOW()
WHERE tenant_id = $3::bigint
  AND id = $4::bigint
  AND deleted_at IS NULL
RETURNING
    id,
    tenant_id,
    pool_group_id,
    model,
    provider_account_ids,
    enabled,
    created_at,
    updated_at,
    deleted_at
`

type UpdateModelRoutingOverrideAdminParams struct {
	ProviderAccountIDs []int64 `db:"provider_account_ids" json:"provider_account_ids"`
	Enabled            bool    `db:"enabled" json:"enabled"`
	TenantID           int64   `db:"tenant_id" json:"tenant_id"`
	ID                 int64   `db:"id" json:"id"`
}

func (q *Queries) UpdateModelRoutingOverrideAdmin(ctx context.Context, arg UpdateModelRoutingOverrideAdminParams) (ModelRoutingOverride, error) {
	row := q.db.QueryRow(ctx, updateModelRoutingOverrideAdmin,
		arg.ProviderAccountIDs,
		arg.Enabled,
		arg.TenantID,
		arg.ID,
	)
	var i ModelRoutingOverride
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PoolGroupID,
		&i.Model,
		&i.ProviderAccountIDs,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
