// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package modelroutingadmindb

import (
	"context"
)

type Querier interface {
	// 模型路由强制 pin 的租户域管理查询；消费查询仍由 pool_accounts.sql 负责。
	CreateModelRoutingOverrideAdmin(ctx context.Context, arg CreateModelRoutingOverrideAdminParams) (ModelRoutingOverride, error)
	DeleteModelRoutingOverrideAdmin(ctx context.Context, arg DeleteModelRoutingOverrideAdminParams) (ModelRoutingOverride, error)
	GetModelRoutingOverrideAdminForUpdate(ctx context.Context, arg GetModelRoutingOverrideAdminForUpdateParams) (ModelRoutingOverride, error)
	ListModelRoutingOverridesAdmin(ctx context.Context, tenantID int64) ([]ModelRoutingOverride, error)
	LockModelRoutingAccountsForPool(ctx context.Context, arg LockModelRoutingAccountsForPoolParams) ([]int64, error)
	LockModelRoutingPoolForTenant(ctx context.Context, arg LockModelRoutingPoolForTenantParams) (int64, error)
	UpdateModelRoutingOverrideAdmin(ctx context.Context, arg UpdateModelRoutingOverrideAdminParams) (ModelRoutingOverride, error)
}

var _ Querier = (*Queries)(nil)
